import assert from "node:assert/strict";
import test from "node:test";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import * as primitives from "../dist/index.js";

const expectedExports = [
  "Accordion",
  "AccordionItem",
  "ActionRail",
  "Alert",
  "AddressField",
  "AddressFieldSet",
  "ArticleBlock",
  "AudioPlayer",
  "Badge",
  "Bookmark",
  "Breadcrumbs",
  "Bubble",
  "Button",
  "ButtonGroup",
  "Card",
  "CardBody",
  "CardFooter",
  "CardGrid",
  "CardHeader",
  "Cards",
  "ChatPrompt",
  "CheckboxField",
  "CheckboxGroup",
  "Cluster",
  "CodeBlock",
  "ColorPicker",
  "ConsoleFooter",
  "DataTable",
  "DateField",
  "DateRangeField",
  "DateTimeField",
  "DateTimeRangeField",
  "DecimalQuantityField",
  "Dialog",
  "DurationField",
  "EmailField",
  "Explorer",
  "Fab",
  "Favorite",
  "FileDropzone",
  "FilterBar",
  "Gallery",
  "Grid",
  "Gutter",
  "Icon",
  "IconButton",
  "IconButtonGroup",
  "IconGrid",
  "ImageFrame",
  "IntegerQuantityField",
  "JsonPreview",
  "LastNameField",
  "Map",
  "MapBeacon",
  "MapBox",
  "MapPath",
  "MapPoint",
  "MiddleNameField",
  "Modal",
  "NavItem",
  "Navbar",
  "OrderedList",
  "Pagination",
  "Pane",
  "Pill",
  "Popover",
  "Progress",
  "RadioGroup",
  "SecretField",
  "SearchField",
  "SelectField",
  "Sheet",
  "Split",
  "Spinner",
  "Stack",
  "StarRating",
  "StatusDot",
  "Surface",
  "TableOfContents",
  "TaggedCrudField",
  "TelephoneField",
  "Tabs",
  "TaskList",
  "TextArea",
  "TextCompletionField",
  "TextInput",
  "TimePickerField",
  "TimeRangeField",
  "Toast",
  "TodoList",
  "Tooltip",
  "ToggleSection",
  "Toolbar",
  "Tree",
  "UnorderedList",
  "UrlField",
  "VideoFrame",
  "ViewToggle",
  "WebsiteField",
  "FirstNameField",
  "NameFieldSet",
];

test("T0: primitive package exports the governed public surface", () => {
  for (const exportName of expectedExports) {
    assert.equal(typeof primitives[exportName], "function", `missing primitive export ${exportName}`);
  }
  assert.equal(primitives.LANDER_PRIMITIVES_VERSION, "0.1.1");
});

test("T0: basic primitives render stable primitive markers", () => {
  const markup = renderToStaticMarkup(React.createElement(React.Fragment, null,
    React.createElement(primitives.Button, null, "Save"),
    React.createElement(primitives.Badge, null, "Ready"),
    React.createElement(primitives.Card, { title: "Card", footer: "Footer" }, "Body"),
    React.createElement(primitives.SearchField, { label: "Search", value: "schema", readOnly: true }),
    React.createElement(primitives.JsonPreview, { value: { name: "Thing" } }),
  ));

  for (const marker of ["button", "badge", "card", "card-header", "card-body", "card-footer", "search-field", "json-preview"]) {
    assert.match(markup, new RegExp(`data-mdwrk-primitive="${marker}"`));
  }
  assert.match(markup, /Thing/);
});
