import {
  aggregateRatingNode,
  articleNode,
  blogPostingNode,
  bookNode,
  breadcrumbListSchema,
  buildJsonLdGraph,
  carouselSchema,
  claimReviewNode,
  courseInstanceNode,
  courseListSchema,
  courseNode,
  datasetNode,
  discussionForumPostingNode,
  educationQaPageSchema,
  employerAggregateRatingNode,
  estimatedSalaryNode,
  eventNode,
  faqPageSchema,
  faqSchema,
  howToNode,
  imageObjectSchema,
  itemListNode,
  jobPostingNode,
  localBusinessNode,
  loyaltyProgramNode,
  mathSolverNode,
  merchantListingNode,
  merchantReturnPolicyNode,
  movieNode,
  offerShippingDetailsNode,
  organizationNode,
  paywalledContentSchema,
  productGroupNode,
  productNode,
  productSnippetNode,
  profilePageNode,
  qaPageSchema,
  readActionNode,
  recipeNode,
  reviewNode,
  softwareApplicationNode,
  softwareSourceCodeNode,
  speakableSpecificationNode,
  stableId,
  techArticleNode,
  vacationRentalNode,
  vehicleListingNode,
  videoObjectNode,
  webApplicationNode,
  webPageSchema,
  webSiteSchema,
} from "../dist/index.js";

const canonicalUrl = "https://example.test/docs/structured-data";
const organization = organizationNode({
  id: stableId("https://example.test", "organization"),
  name: "Example",
  url: "https://example.test",
  logo: { src: "https://example.test/logo.png", alt: "Example logo" },
});
const website = webSiteSchema({
  id: stableId("https://example.test", "website"),
  name: "Example site",
  url: "https://example.test",
  publisher: organization,
});
const image = imageObjectSchema({
  name: "Screenshot",
  url: "https://example.test/screenshot.png",
  width: 1200,
  height: 630,
});
const breadcrumb = breadcrumbListSchema({
  items: [
    { label: "Home", href: "https://example.test/" },
    { label: "Docs", href: "https://example.test/docs" },
  ],
});
const page = webPageSchema({
  id: stableId(canonicalUrl, "web-page"),
  name: "Structured data docs",
  description: "Documents structured data builders.",
  url: canonicalUrl,
  image,
  breadcrumb,
  isPartOf: website,
});

const rating = aggregateRatingNode({ ratingValue: 5, reviewCount: 1 });
const softwareApplication = softwareApplicationNode({
  name: "Example App",
  url: "https://example.test/app",
  applicationCategory: "DeveloperApplication",
});
const courseInstance = courseInstanceNode({
  name: "Structured data workshop May 2026",
  courseMode: "online",
  startDate: "2026-05-06",
});
const product = productNode({
  name: "Example Product",
  url: "https://example.test/product",
  brand: organization,
  aggregateRating: rating,
  review: reviewNode({
    name: "Visible review",
    itemReviewed: softwareApplication,
    reviewRating: rating,
    author: organization,
    reviewBody: "This review exists visibly on the page.",
  }),
});
const readAction = readActionNode("https://example.test/books/read");
const estimatedSalary = estimatedSalaryNode({
  name: "Structured data engineer salary",
  currency: "USD",
  minValue: 100000,
  maxValue: 140000,
  unitText: "YEAR",
});

export const nodes = [
  organization,
  website,
  page,
  softwareApplication,
  webApplicationNode({
    name: "Example Web App",
    url: "https://example.test/app",
    applicationCategory: "DeveloperApplication",
  }),
  articleNode({
    name: "Article",
    headline: "Article headline",
    url: canonicalUrl,
    author: organization,
    publisher: organization,
  }),
  techArticleNode({
    name: "Tech Article",
    headline: "Tech Article headline",
    url: canonicalUrl,
    author: organization,
  }),
  blogPostingNode({
    name: "Launch note",
    headline: "Launch note",
    url: "https://example.test/blog/launch",
    datePublished: "2026-05-06",
    publisher: organization,
  }),
  breadcrumb,
  faqPageSchema({ items: [{ question: "What is this?", answer: "A structured data test." }] }),
  qaPageSchema({
    question: "Can this emit QAPage?",
    answer: "Yes, when the page is a true Q and A surface.",
  }),
  educationQaPageSchema({
    question: "What does the lesson prove?",
    answer: "That education Q and A markup is explicit.",
  }),
  howToNode({
    name: "Install Example",
    description: "Install the example app.",
    url: "https://example.test/docs/install",
    steps: [{ name: "Install", text: "Run the installer." }],
  }),
  itemListNode({
    name: "Packages",
    items: [{ name: "structured-data", url: "https://example.test/packages/structured-data" }],
  }),
  carouselSchema({
    name: "Featured items",
    items: [{ name: "Feature one", url: "https://example.test/features/one" }],
  }),
  softwareSourceCodeNode({
    name: "structured-data package",
    url: "https://example.test/packages/structured-data",
    codeRepository: "https://github.com/example/repo",
    programmingLanguage: "TypeScript",
  }),
  product,
  merchantListingNode({
    name: "Example Merchant Listing",
    url: "https://example.test/merchant-listing",
    brand: organization,
    offers: { "@type": "Offer", price: "10.00", priceCurrency: "USD" },
  }),
  productSnippetNode({
    name: "Example Product Snippet",
    url: "https://example.test/product-snippet",
    brand: organization,
    aggregateRating: rating,
  }),
  datasetNode({
    name: "Example dataset",
    description: "Generated structured data fixture.",
    url: "https://example.test/dataset.json",
    creator: organization,
    keywords: ["structured-data", "json-ld"],
  }),
  eventNode({
    name: "Launch event",
    url: "https://example.test/events/launch",
    startDate: "2026-05-06T12:00:00Z",
    organizer: organization,
  }),
  videoObjectNode({
    name: "Demo video",
    url: "https://example.test/videos/demo",
    thumbnailUrl: "https://example.test/videos/demo.png",
    uploadDate: "2026-05-06",
  }),
  image,
  profilePageNode({
    name: "Maintainer profile",
    url: "https://example.test/team/maintainer",
    mainEntity: organization,
  }),
  reviewNode({
    name: "Visible review",
    itemReviewed: softwareApplication,
    reviewRating: rating,
    author: organization,
    reviewBody: "This review exists visibly on the page.",
  }),
  rating,
  courseNode({
    name: "Structured data workshop",
    description: "Learn JSON-LD builders.",
    url: "https://example.test/courses/structured-data",
    provider: organization,
    hasCourseInstance: courseInstance,
  }),
  courseInstance,
  courseListSchema({
    name: "Courses",
    items: [{ name: "Structured data workshop", item: courseInstance }],
  }),
  discussionForumPostingNode({
    name: "Structured data support thread",
    headline: "Structured data support thread",
    url: "https://example.test/community/structured-data",
    author: organization,
    articleBody: "Discussion content is visible on the page.",
  }),
  bookNode({
    name: "Structured Data Handbook",
    url: "https://example.test/books/structured-data",
    author: organization,
    isbn: "9780000000000",
    readAction,
  }),
  readAction,
  claimReviewNode({
    name: "Structured data fact check",
    url: "https://example.test/fact-check/structured-data",
    claimReviewed: "Structured data must match visible page content.",
    author: organization,
    reviewRating: rating,
  }),
  employerAggregateRatingNode({ ratingValue: 4.8, reviewCount: 12 }),
  estimatedSalary,
  jobPostingNode({
    name: "Structured data engineer",
    title: "Structured data engineer",
    description: "Work on JSON-LD builders.",
    url: "https://example.test/jobs/structured-data",
    datePosted: "2026-05-06",
    hiringOrganization: organization,
    baseSalary: estimatedSalary,
  }),
  localBusinessNode({
    name: "Example Office",
    url: "https://example.test/office",
    address: "100 Example Way",
    telephone: "+1-555-0100",
  }),
  loyaltyProgramNode({
    name: "Example Member Program",
    url: "https://example.test/members",
    provider: organization,
  }),
  mathSolverNode({
    name: "Markdown math solver",
    url: "https://example.test/math",
    mathExpression: "x + 1 = 2",
  }),
  merchantReturnPolicyNode({
    name: "Return policy",
    url: "https://example.test/returns",
    merchantReturnDays: 30,
  }),
  offerShippingDetailsNode({
    name: "Shipping policy",
    shippingDestination: "US",
  }),
  movieNode({
    name: "Structured Data Demo",
    url: "https://example.test/movie",
    director: organization,
  }),
  productGroupNode({
    name: "Example Product Family",
    url: "https://example.test/products/family",
    hasVariant: product,
  }),
  recipeNode({
    name: "Structured data recipe",
    url: "https://example.test/recipes/structured-data",
    recipeIngredient: ["Visible content", "Typed builder"],
    recipeInstructions: [{ name: "Render", text: "Render the visible recipe step." }],
    author: organization,
  }),
  speakableSpecificationNode({ cssSelector: [".answer-summary"] }),
  paywalledContentSchema({
    name: "Subscriber guide",
    url: "https://example.test/subscriber-guide",
    cssSelector: [".subscriber-only"],
  }),
  vacationRentalNode({
    name: "Example Rental",
    url: "https://example.test/rentals/example",
    address: "100 Example Way",
  }),
  vehicleListingNode({
    name: "Example Vehicle",
    url: "https://example.test/vehicles/example",
    brand: organization,
    vehicleIdentificationNumber: "EXAMPLEVIN123",
  }),
];

export const expectedTypes = [
  "Organization",
  "WebSite",
  "WebPage",
  "SoftwareApplication",
  "WebApplication",
  "Article",
  "TechArticle",
  "BlogPosting",
  "BreadcrumbList",
  "FAQPage",
  "QAPage",
  "QAPage",
  "HowTo",
  "ItemList",
  "ItemList",
  "SoftwareSourceCode",
  "Product",
  "Product",
  "Product",
  "Dataset",
  "Event",
  "VideoObject",
  "ImageObject",
  "ProfilePage",
  "Review",
  "AggregateRating",
  "Course",
  "CourseInstance",
  "ItemList",
  "DiscussionForumPosting",
  "Book",
  "ReadAction",
  "ClaimReview",
  "EmployerAggregateRating",
  "MonetaryAmountDistribution",
  "JobPosting",
  "LocalBusiness",
  "MemberProgram",
  "MathSolver",
  "MerchantReturnPolicy",
  "OfferShippingDetails",
  "Movie",
  "ProductGroup",
  "Recipe",
  "SpeakableSpecification",
  "WebPage",
  "VacationRental",
  "Vehicle",
];

export const legacyFaq = faqSchema([{ question: "Legacy?", answer: "Still supported." }]);

export const generatedGraph = buildJsonLdGraph(
  {
    product: {
      name: "Example",
      slug: "example",
      tagline: "Tagline",
      description: "Description",
      category: "Software",
      canonicalUrl: "https://example.test",
      logo: { src: "https://example.test/logo.png" },
    },
  },
  {
    kind: "blog",
    slug: "/blog/launch",
    title: "Example Launch",
    description: "Long enough description.",
    h1: "Example Launch",
    canonicalUrl: "https://example.test/blog/launch",
    breadcrumbs: [{ label: "Home", href: "/" }],
    faq: [{ question: "Is this visible?", answer: "Yes." }],
    datePublished: "2026-05-06",
  },
);
