import React from "react";
import * as structuredDataReact from "@mdwrk/lander-react-structured-data";
import { GeneratedPropertyProps, renderGeneratedPropertyCard } from "../shared.js";

export interface SchemaPropertyServiceOutputProps extends GeneratedPropertyProps<Record<string, unknown>> {}

export function SchemaPropertyServiceOutput({ value, description = "The tangible thing generated by the service, e.g. a passport, permit, etc.", examples, body, className, emitStructuredData = true, structuredDataOverrides, viewModel }: SchemaPropertyServiceOutputProps) {
  return renderGeneratedPropertyCard({
    StructuredDataComponent: structuredDataReact.ServiceOutputPropertyStructuredData,
    defaultEyebrow: "Property",
    kind: "schema-property-service-output",
    shellClassName: "lander-semantic--schema-property-service-output",
    title: "serviceOutput",
    value,
    description,
    examples,
    body,
    className,
    emitStructuredData,
    structuredDataOverrides,
    viewModel,
  });
}
