import React from "react";
import * as structuredDataReact from "@mdwrk/lander-react-structured-data";
import type { ServiceOutputPropertyInput } from "@mdwrk/structured-data";
import { GeneratedPropertyUiProps, renderGeneratedPropertyCard } from "../shared.js";

export interface SchemaPropertyServiceOutputProps extends ServiceOutputPropertyInput, GeneratedPropertyUiProps<ServiceOutputPropertyInput> {}

export function SchemaPropertyServiceOutput({ value: legacyValue, description = "The tangible thing generated by the service, e.g. a passport, permit, etc.", examples, body, className, emitStructuredData = true, structuredDataOverrides, viewModel, ...rest }: SchemaPropertyServiceOutputProps) {
  const explicitValue = legacyValue;
  const directValue = rest;
  const value = Object.keys(directValue).length > 0
    ? explicitValue && typeof explicitValue === "object" && !Array.isArray(explicitValue)
      ? { ...explicitValue, ...directValue }
      : directValue
    : (explicitValue ?? directValue);
  return renderGeneratedPropertyCard({
    StructuredDataComponent: structuredDataReact.ServiceOutputPropertyStructuredData,
    defaultEyebrow: "Property",
    kind: "schema-property-service-output",
    shellClassName: "lander-semantic--schema-property-service-output",
    title: "serviceOutput",
    value,
    description,
    examples,
    body,
    className,
    emitStructuredData,
    structuredDataOverrides,
    viewModel,
  });
}
