import React from "react";
import * as structuredDataReact from "@mdwrk/lander-react-structured-data";
import { GeneratedPropertyProps, renderGeneratedPropertyCard } from "../shared.js";

export interface SchemaPropertyProducesProps extends GeneratedPropertyProps<Record<string, unknown>> {}

export function SchemaPropertyProduces({ value, description = "The tangible thing generated by the service, e.g. a passport, permit, etc.", examples, body, className, emitStructuredData = true, structuredDataOverrides, viewModel }: SchemaPropertyProducesProps) {
  return renderGeneratedPropertyCard({
    StructuredDataComponent: structuredDataReact.ProducesPropertyStructuredData,
    defaultEyebrow: "Property",
    kind: "schema-property-produces",
    shellClassName: "lander-semantic--schema-property-produces",
    title: "produces",
    value,
    description,
    examples,
    body,
    className,
    emitStructuredData,
    structuredDataOverrides,
    viewModel,
  });
}
