import React from "react";
import * as structuredDataReact from "@mdwrk/lander-react-structured-data";
import type { ProducesPropertyInput } from "@mdwrk/structured-data";
import { GeneratedPropertyUiProps, renderGeneratedPropertyCard } from "../shared.js";

export interface SchemaPropertyProducesProps extends ProducesPropertyInput, GeneratedPropertyUiProps<ProducesPropertyInput> {}

export function SchemaPropertyProduces({ value: legacyValue, description = "The tangible thing generated by the service, e.g. a passport, permit, etc.", examples, body, className, emitStructuredData = true, structuredDataOverrides, viewModel, ...rest }: SchemaPropertyProducesProps) {
  const explicitValue = legacyValue;
  const directValue = rest;
  const value = Object.keys(directValue).length > 0
    ? explicitValue && typeof explicitValue === "object" && !Array.isArray(explicitValue)
      ? { ...explicitValue, ...directValue }
      : directValue
    : (explicitValue ?? directValue);
  return renderGeneratedPropertyCard({
    StructuredDataComponent: structuredDataReact.ProducesPropertyStructuredData,
    defaultEyebrow: "Property",
    kind: "schema-property-produces",
    shellClassName: "lander-semantic--schema-property-produces",
    title: "produces",
    value,
    description,
    examples,
    body,
    className,
    emitStructuredData,
    structuredDataOverrides,
    viewModel,
  });
}
