import {
  actionNode,
  administrativeAreaNode,
  aggregateOfferNode,
  aggregateRatingNode,
  alignmentObjectNode,
  answerNode,
  articleNode,
  audienceNode,
  audioObjectNode,
  brandNode,
  broadcastChannelNode,
  broadcastFrequencySpecificationNode,
  broadcastServiceNode,
  cableOrSatelliteServiceNode,
  categoryCodeNode,
  categoryCodeSetNode,
  civicStructureNode,
  classNode,
  blogPostingNode,
  bookNode,
  broadcastEventNode,
  breadcrumbListSchema,
  buildJsonLdGraph,
  carouselSchema,
  certificationNode,
  claimNode,
  claimReviewNode,
  clipNode,
  commentNode,
  constraintNodeNode,
  courseInstanceNode,
  courseListSchema,
  courseNode,
  contactPointNode,
  correctionCommentNode,
  countryNode,
  creativeWorkNode,
  creativeWorkSeasonNode,
  creativeWorkSeriesNode,
  credentialNode,
  creditCardNode,
  cssSelectorTypeNode,
  dataCatalogNode,
  dataDownloadNode,
  dataFeedItemNode,
  dataFeedNode,
  datasetNode,
  definedRegionNode,
  definedTermNode,
  definedTermSetNode,
  deliveryChargeSpecificationNode,
  demandNode,
  distanceNode,
  discussionForumPostingNode,
  durationNode,
  educationalOccupationalCredentialNode,
  educationalOrganizationNode,
  energyConsumptionDetailsNode,
  energyNode,
  entryPointNode,
  educationQaPageSchema,
  enumerationNode,
  episodeNode,
  employerAggregateRatingNode,
  estimatedSalaryNode,
  eventNode,
  faqPageSchema,
  faqSchema,
  financialProductNode,
  geneNode,
  geoCoordinatesNode,
  geospatialGeometryNode,
  geoShapeNode,
  grantNode,
  hyperTocEntryNode,
  healthInsurancePlanNode,
  healthPlanCostSharingSpecificationNode,
  healthPlanFormularyNode,
  healthPlanNetworkNode,
  howToItemNode,
  howToNode,
  howToSectionNode,
  howToStepNode,
  howToSupplyNode,
  howToToolNode,
  imageGalleryNode,
  imageObjectSchema,
  intangibleNode,
  interactionCounterNode,
  integerNode,
  itemListNode,
  jobPostingNode,
  learningResourceNode,
  languageNode,
  lifestyleModificationNode,
  listItemNode,
  loanOrCreditNode,
  localBusinessNode,
  loyaltyProgramNode,
  locationFeatureSpecificationNode,
  massNode,
  mapNode,
  mathSolverNode,
  mediaGalleryNode,
  mediaObjectNode,
  mediaSubscriptionNode,
  menuItemNode,
  menuSectionNode,
  medicalAudienceNode,
  medicalCauseNode,
  medicalCodeNode,
  medicalConditionNode,
  medicalConditionStageNode,
  medicalContraindicationNode,
  medicalDeviceNode,
  medicalEntityNode,
  medicalGuidelineNode,
  medicalIntangibleNode,
  medicalProcedureNode,
  medicalRiskFactorNode,
  medicalSignNode,
  medicalSignOrSymptomNode,
  medicalStudyNode,
  medicalTestNode,
  medicalTherapyNode,
  memberProgramTierNode,
  merchantListingNode,
  maximumDoseScheduleNode,
  monetaryAmountNode,
  merchantReturnPolicyNode,
  merchantReturnPolicySeasonalOverrideNode,
  movieNode,
  musicAlbumNode,
  musicCompositionNode,
  musicGroupNode,
  musicPlaylistNode,
  musicRecordingNode,
  musicReleaseNode,
  newsArticleNode,
  nutritionInformationNode,
  occupationNode,
  occupationalExperienceRequirementsNode,
  offerCatalogNode,
  offerNode,
  offerShippingDetailsNode,
  openingHoursSpecificationNode,
  operatingSystemNode,
  organizationNode,
  paywalledContentSchema,
  propertyNode,
  propertyValueNode,
  productGroupNode,
  productModelNode,
  productNode,
  productSnippetNode,
  programMembershipNode,
  profilePageNode,
  publicationEventNode,
  repaymentSpecificationNode,
  qaPageSchema,
  quantitativeValueDistributionNode,
  quantitativeValueNode,
  questionNode,
  quizNode,
  readActionNode,
  ratingNode,
  recipeNode,
  reviewNode,
  scheduleNode,
  seriesNode,
  serviceNode,
  serviceChannelNode,
  servicePeriodNode,
  shippingConditionsNode,
  shippingDeliveryTimeNode,
  shippingRateSettingsNode,
  shippingServiceNode,
  solveMathActionNode,
  softwareApplicationNode,
  softwareSourceCodeNode,
  statisticalVariableNode,
  substanceNode,
  taxonNode,
  superficialAnatomyNode,
  speakableSpecificationNode,
  stableId,
  structuredValueNode,
  typeAndQuantityNode,
  techArticleNode,
  therapeuticProcedureNode,
  thingNode,
  textObjectNode,
  tripNode,
  unitPriceSpecificationNode,
  urlNode,
  vacationRentalNode,
  vehicleListingNode,
  videoObjectNode,
  virtualLocationNode,
  warrantyPromiseNode,
  medicalWebPageNode,
  webApplicationNode,
  webContentNode,
  webPageElementNode,
  webPageSchema,
  webSiteSchema,
  runtimePlatformNode,
  xPathTypeNode,
} from "../dist/index.js";

const canonicalUrl = "https://example.test/docs/structured-data";
const organization = organizationNode({
  id: stableId("https://example.test", "organization"),
  name: "Example",
  url: "https://example.test",
  logo: { src: "https://example.test/logo.png", alt: "Example logo" },
});
const website = webSiteSchema({
  id: stableId("https://example.test", "website"),
  name: "Example site",
  url: "https://example.test",
  publisher: organization,
});
const image = imageObjectSchema({
  name: "Screenshot",
  url: "https://example.test/screenshot.png",
  width: 1200,
  height: 630,
});
const breadcrumb = breadcrumbListSchema({
  items: [
    { label: "Home", href: "https://example.test/" },
    { label: "Docs", href: "https://example.test/docs" },
  ],
});
const page = webPageSchema({
  id: stableId(canonicalUrl, "web-page"),
  name: "Structured data docs",
  description: "Documents structured data builders.",
  url: canonicalUrl,
  image,
  breadcrumb,
  isPartOf: website,
});

const rating = aggregateRatingNode({ ratingValue: 5, reviewCount: 1 });
const softwareApplication = softwareApplicationNode({
  name: "Example App",
  url: "https://example.test/app",
  applicationCategory: "DeveloperApplication",
});
const courseInstance = courseInstanceNode({
  name: "Structured data workshop May 2026",
  courseMode: "online",
  startDate: "2026-05-06",
});
const product = productNode({
  name: "Example Product",
  url: "https://example.test/product",
  brand: organization,
  aggregateRating: rating,
  review: reviewNode({
    name: "Visible review",
    itemReviewed: softwareApplication,
    reviewRating: rating,
    author: organization,
    reviewBody: "This review exists visibly on the page.",
  }),
});
const readAction = readActionNode("https://example.test/books/read");
const estimatedSalary = estimatedSalaryNode({
  name: "Structured data engineer salary",
  currency: "USD",
  minValue: 100000,
  maxValue: 140000,
  unitText: "YEAR",
});

export const nodes = [
  actionNode({
    name: "Read docs",
    target: "https://example.test/docs/structured-data",
  }),
  administrativeAreaNode({
    name: "Illinois",
    containedInPlace: { "@type": "Place", name: "United States" },
  }),
  organization,
  website,
  page,
  aggregateOfferNode({
    name: "Offer range",
    lowPrice: "10.00",
    highPrice: "30.00",
    offerCount: 3,
    offers: [{ "@type": "Offer", price: "10.00", priceCurrency: "USD" }],
  }),
  thingNode({
    name: "Prompt asset",
    sameAs: ["https://example.test/things/prompt-asset"],
  }),
  intangibleNode({
    name: "Service commitment",
    description: "Non-physical asset.",
  }),
  structuredValueNode({
    name: "Prompt budget",
    description: "Structured record.",
  }),
  alignmentObjectNode({
    name: "Curriculum alignment",
    alignmentType: "educationalSubject",
    targetName: "Prompt operations",
  }),
  audienceNode({
    name: "Operators",
    audienceType: "Prompt operators",
    geographicArea: { "@type": "AdministrativeArea", name: "Illinois" },
  }),
  audioObjectNode({
    name: "Release call",
    contentUrl: "https://example.test/audio/release-call.mp3",
    transcript: "Release call transcript.",
  }),
  brandNode({
    name: "Example Brand",
    slogan: "Prompt systems that ship.",
    review: [reviewNode({ name: "Brand review", itemReviewed: softwareApplication, author: organization, reviewBody: "Trusted." })],
  }),
  broadcastChannelNode({
    name: "Primary channel",
    broadcastChannelId: "CH-7",
    providesBroadcastService: { "@type": "BroadcastService", name: "Prompt Radio" },
  }),
  broadcastFrequencySpecificationNode({
    name: "HD terrestrial slot",
    broadcastFrequencyValue: 101.7,
    broadcastSignalModulation: "QAM",
  }),
  broadcastServiceNode({
    name: "Prompt Radio",
    broadcastDisplayName: "Prompt Radio 101",
    areaServed: { "@type": "AdministrativeArea", name: "Illinois" },
    hasBroadcastChannel: [{ "@type": "BroadcastChannel", name: "Primary channel" }],
  }),
  softwareApplication,
  webApplicationNode({
    name: "Example Web App",
    url: "https://example.test/app",
    applicationCategory: "DeveloperApplication",
  }),
  articleNode({
    name: "Article",
    headline: "Article headline",
    url: canonicalUrl,
    author: organization,
    publisher: organization,
  }),
  newsArticleNode({
    name: "News Article",
    headline: "News article headline",
    url: "https://example.test/news/launch",
    datePublished: "2026-05-06",
    publisher: organization,
  }),
  techArticleNode({
    name: "Tech Article",
    headline: "Tech Article headline",
    url: canonicalUrl,
    author: organization,
  }),
  blogPostingNode({
    name: "Launch note",
    headline: "Launch note",
    url: "https://example.test/blog/launch",
    datePublished: "2026-05-06",
    publisher: organization,
  }),
  breadcrumb,
  certificationNode({
    name: "Accessibility Certification",
    certificationIdentification: "CERT-42",
    certificationStatus: "Active",
    issuedBy: organization,
  }),
  cableOrSatelliteServiceNode({
    name: "Prompt cable",
    areaServed: { "@type": "AdministrativeArea", name: "Midwest" },
    provider: organization,
  }),
  civicStructureNode({
    name: "Prompt library",
    publicAccess: true,
    openingHours: ["Mo-Fr 09:00-17:00"],
  }),
  claimNode({
    name: "Latency claim",
    text: "Latency is below target.",
    appearance: [articleNode({ name: "Benchmark report", headline: "Benchmark report", url: "https://example.test/report" })],
  }),
  constraintNodeNode({
    name: "Prompt shape",
    constraintProperty: "deliveryStage",
    numConstraints: 3,
  }),
  commentNode({
    name: "Operator note",
    text: "Looks good.",
    author: organization,
    upvoteCount: 3,
  }),
  contactPointNode({
    name: "Support",
    contactType: "Support",
    email: "support@example.test",
    availableLanguage: ["English"],
  }),
  correctionCommentNode({
    name: "Correction",
    text: "The previous metric was stale.",
    sharedContent: articleNode({ name: "Release report", headline: "Release report", url: "https://example.test/release-report" }),
  }),
  faqPageSchema({ items: [{ question: "What is this?", answer: "A structured data test." }] }),
  qaPageSchema({
    question: "Can this emit QAPage?",
    acceptedAnswer: { text: "Yes, when the page is a true Q and A surface." },
    suggestedAnswer: [{ text: "Only if the page is not actually Q and A." }],
    answerCount: 2,
  }),
  educationQaPageSchema({
    question: "What does the lesson prove?",
    answer: "That education Q and A markup is explicit.",
  }),
  answerNode({
    text: "This answer exists as a reusable node.",
    author: organization,
  }),
  questionNode({
    name: "What is a flashcard question?",
    eduQuestionType: "Flashcard",
    acceptedAnswer: { text: "A question with an accepted answer." },
    suggestedAnswer: [{ text: "A random distractor." }],
    answerCount: 2,
  }),
  quizNode({
    name: "Structured data quiz",
    hasPart: [
      {
        name: "What kind of page is this?",
        eduQuestionType: "Flashcard",
        acceptedAnswer: { text: "A quiz page." },
        suggestedAnswer: [{ text: "A product page." }],
        answerCount: 2,
      },
    ],
  }),
  howToNode({
    name: "Install Example",
    description: "Install the example app.",
    url: "https://example.test/docs/install",
    steps: [{ name: "Install", text: "Run the installer." }],
  }),
  itemListNode({
    name: "Packages",
    items: [{ name: "structured-data", url: "https://example.test/packages/structured-data" }],
  }),
  carouselSchema({
    name: "Featured items",
    items: [{ name: "Feature one", url: "https://example.test/features/one" }],
  }),
  softwareSourceCodeNode({
    name: "structured-data package",
    url: "https://example.test/packages/structured-data",
    codeRepository: "https://github.com/example/repo",
    programmingLanguage: "TypeScript",
  }),
  product,
  merchantListingNode({
    name: "Example Merchant Listing",
    url: "https://example.test/merchant-listing",
    brand: organization,
    offers: { "@type": "Offer", price: "10.00", priceCurrency: "USD" },
  }),
  productSnippetNode({
    name: "Example Product Snippet",
    url: "https://example.test/product-snippet",
    brand: organization,
    aggregateRating: rating,
  }),
  datasetNode({
    name: "Example dataset",
    description: "Generated structured data fixture.",
    url: "https://example.test/dataset.json",
    creator: organization,
    keywords: ["structured-data", "json-ld"],
  }),
  eventNode({
    name: "Launch event",
    url: "https://example.test/events/launch",
    startDate: "2026-05-06T12:00:00Z",
    organizer: organization,
  }),
  videoObjectNode({
    name: "Demo video",
    url: "https://example.test/videos/demo",
    thumbnailUrl: "https://example.test/videos/demo.png",
    uploadDate: "2026-05-06",
  }),
  image,
  profilePageNode({
    name: "Maintainer profile",
    url: "https://example.test/team/maintainer",
    mainEntity: organization,
  }),
  reviewNode({
    name: "Visible review",
    itemReviewed: softwareApplication,
    reviewRating: rating,
    author: organization,
    reviewBody: "This review exists visibly on the page.",
  }),
  rating,
  courseNode({
    name: "Structured data workshop",
    description: "Learn JSON-LD builders.",
    url: "https://example.test/courses/structured-data",
    provider: organization,
    hasCourseInstance: courseInstance,
  }),
  courseInstance,
  countryNode({
    name: "United States",
    containedInPlace: { "@type": "Place", name: "North America" },
  }),
  creativeWorkNode({
    name: "Operator handbook",
    text: "Visible body text.",
    author: organization,
  }),
  creativeWorkSeasonNode({
    name: "Season One",
    seasonNumber: 1,
    numberOfEpisodes: 8,
    episode: [{ "@type": "Episode", name: "Episode 1" }],
  }),
  creativeWorkSeriesNode({
    name: "Prompt Ops Series",
    issn: "1234-5678",
    startDate: "2025-01-01",
  }),
  categoryCodeNode({
    name: "PromptOps",
    termCode: "PO-1",
    codeValue: "prompt-ops",
  }),
  categoryCodeSetNode({
    name: "Ops glossary",
    hasCategoryCode: [{ "@type": "CategoryCode", name: "PromptOps" }],
  }),
  classNode({
    name: "PromptEntity",
    description: "A top-level modeled class.",
  }),
  credentialNode({
    name: "Release badge",
    credentialCategory: "badge",
    recognizedBy: organization,
  }),
  creditCardNode({
    name: "Prompt rewards card",
    interestRate: 14.9,
    feesAndCommissionsSpecification: "No annual fee.",
  }),
  cssSelectorTypeNode({}),
  dataCatalogNode({
    name: "Prompt data catalog",
    dataset: [{ "@type": "Dataset", name: "Release metrics" }],
    measurementMethod: "survey",
  }),
  dataDownloadNode({
    name: "Release dataset export",
    contentUrl: "https://example.test/export.csv",
    encodingFormat: "text/csv",
  }),
  dataFeedNode({
    name: "Prompt activity feed",
    dataFeedElement: [{ "@type": "DataFeedItem", name: "Release one" }],
    dateModified: "2026-05-27",
  }),
  dataFeedItemNode({
    name: "Release one",
    item: { "@type": "Thing", name: "Prompt Studio" },
    dateCreated: "2026-05-27",
  }),
  courseListSchema({
    name: "Courses",
    items: [{ name: "Structured data workshop", item: courseInstance }],
  }),
  discussionForumPostingNode({
    name: "Structured data support thread",
    headline: "Structured data support thread",
    url: "https://example.test/community/structured-data",
    author: organization,
    articleBody: "Discussion content is visible on the page.",
  }),
  definedRegionNode({
    name: "US Midwest",
    addressCountry: "US",
    postalCodePrefix: "60",
  }),
  definedTermNode({
    name: "Prompt drift",
    termCode: "PD-01",
    about: { "@type": "Thing", name: "Model behavior change" },
  }),
  definedTermSetNode({
    name: "Prompt glossary",
    hasDefinedTerm: [{ "@type": "DefinedTerm", name: "Prompt drift" }],
  }),
  deliveryChargeSpecificationNode({
    name: "Domestic shipping",
    price: "15.00",
    priceCurrency: "USD",
  }),
  demandNode({
    name: "Enterprise seats",
    itemOffered: { "@type": "Product", name: "Prompt Studio Enterprise" },
    seller: organization,
  }),
  distanceNode({}),
  durationNode({}),
  educationalOccupationalCredentialNode({
    name: "Release badge",
    credentialCategory: "badge",
    educationalLevel: "Intermediate",
    competencyRequired: ["Prompt validation"],
  }),
  educationalOrganizationNode({
    name: "MdWrk Academy",
    url: "https://example.test/academy",
    address: "Chicago, IL",
  }),
  energyNode({}),
  energyConsumptionDetailsNode({
    name: "Washer profile",
    description: "Efficiency profile.",
  }),
  entryPointNode({
    name: "Prompt API entry",
    urlTemplate: "https://example.test/api/prompts/{id}",
    httpMethod: "GET",
  }),
  enumerationNode({
    name: "PromptStates",
    description: "Enumeration of prompt states.",
  }),
  episodeNode({
    name: "Pilot",
    episodeNumber: 1,
    partOfSeries: { "@type": "CreativeWorkSeries", name: "Prompt Ops Series" },
  }),
  integerNode({}),
  financialProductNode({
    name: "Prompt Rewards",
    annualPercentageRate: 18.2,
    provider: organization,
  }),
  geneNode({
    name: "PROMPT1",
    hasBioPolymerSequence: "ATCGATCG",
    associatedDisease: [{ "@type": "MedicalCondition", name: "Prompt fatigue" }],
  }),
  geoCoordinatesNode({
    latitude: 41.8781,
    longitude: -87.6298,
    addressCountry: "US",
  }),
  geospatialGeometryNode({
    name: "Service boundary",
    geoContains: { "@type": "Place", name: "Chicago" },
    geoWithin: { "@type": "Place", name: "Illinois" },
  }),
  geoShapeNode({
    box: "41.8 -87.7 41.9 -87.6",
    addressCountry: "US",
  }),
  grantNode({
    name: "Prompt research grant",
    fundedItem: [articleNode({ name: "Prompt research", headline: "Prompt research", url: "https://example.test/research" })],
  }),
  hyperTocEntryNode({
    name: "Section A",
    text: "Jump here.",
    position: 1,
    target: { "@type": "Thing", name: "Section A", url: "https://example.test/guide#a" },
  }),
  healthInsurancePlanNode({
    name: "PromptCare Gold",
    healthPlanId: "HIOS-12345",
    contactPoint: { "@type": "ContactPoint", name: "Support" },
    healthPlanDrugTier: "Generic",
  }),
  healthPlanCostSharingSpecificationNode({
    name: "Primary care",
    healthPlanCoinsuranceRate: 0.2,
    healthPlanCopay: { "@type": "PriceSpecification", price: "25.00", priceCurrency: "USD" },
  }),
  healthPlanFormularyNode({
    name: "Drug list",
    healthPlanDrugTier: "Generic",
    offersPrescriptionByMail: true,
  }),
  healthPlanNetworkNode({
    name: "Preferred network",
    healthPlanNetworkId: "NW-100",
    healthPlanNetworkTier: "Tier 1",
  }),
  howToItemNode({
    name: "Filter",
    requiredQuantity: "1",
  }),
  howToSectionNode({
    name: "Preparation",
    steps: "Gather materials.",
  }),
  howToStepNode({
    name: "Mix",
    text: "Mix the ingredients.",
    position: 1,
  }),
  howToSupplyNode({
    name: "Paper",
    requiredQuantity: "2 sheets",
    estimatedCost: { "@type": "MonetaryAmount", name: "$5" },
  }),
  howToToolNode({
    name: "Scissors",
    requiredQuantity: "1",
  }),
  imageGalleryNode({
    name: "Image gallery",
    hasPart: [{ "@type": "ImageObject", name: "Overview panel" }],
  }),
  languageNode({
    name: "English",
    alternateName: "en-US",
  }),
  lifestyleModificationNode({
    name: "Lifestyle coaching",
    code: { "@type": "MedicalCode", name: "LM-1" },
  }),
  interactionCounterNode({
    name: "Views",
    userInteractionCount: 42,
    interactionService: { "@type": "WebSite", name: "Docs" },
  }),
  quantitativeValueNode({
    name: "Latency",
    value: 120,
    unitText: "ms",
  }),
  loanOrCreditNode({
    name: "Equipment financing",
    amount: "25000",
    loanTerm: "P24M",
    requiredCollateral: "Laptop inventory",
  }),
  quantitativeValueDistributionNode({
    name: "Latency band",
    median: 130,
    percentile10: 100,
    percentile90: 180,
    duration: "P30D",
  }),
  monetaryAmountNode({
    name: "Budget",
    currency: "USD",
    value: 5000,
  }),
  ratingNode({
    name: "Operator score",
    ratingValue: 4.8,
    author: organization,
  }),
  massNode({}),
  listItemNode({
    name: "Step 1",
    item: { "@type": "Thing", name: "Prompt audit" },
    position: 1,
  }),
  propertyNode({
    name: "deploymentStage",
    domainIncludes: [{ "@type": "Class", name: "PromptEntity" }],
    rangeIncludes: [{ "@type": "Class", name: "PromptStage" }],
  }),
  propertyValueNode({
    name: "Latency",
    value: 120,
    unitText: "ms",
  }),
  urlNode({}),
  bookNode({
    name: "Structured Data Handbook",
    url: "https://example.test/books/structured-data",
    author: organization,
    isbn: "9780000000000",
    readAction,
  }),
  readAction,
  claimReviewNode({
    name: "Structured data fact check",
    url: "https://example.test/fact-check/structured-data",
    claimReviewed: "Structured data must match visible page content.",
    author: organization,
    reviewRating: rating,
  }),
  employerAggregateRatingNode({ ratingValue: 4.8, reviewCount: 12 }),
  estimatedSalary,
  jobPostingNode({
    name: "Structured data engineer",
    title: "Structured data engineer",
    description: "Work on JSON-LD builders.",
    url: "https://example.test/jobs/structured-data",
    datePosted: "2026-05-06",
    hiringOrganization: organization,
    baseSalary: estimatedSalary,
  }),
  localBusinessNode({
    name: "Example Office",
    url: "https://example.test/office",
    address: "100 Example Way",
    telephone: "+1-555-0100",
  }),
  locationFeatureSpecificationNode({
    name: "Accessible entrance",
    propertyID: "entrance_access",
    value: true,
    hoursAvailable: ["Mo-Fr 09:00-17:00"],
  }),
  mapNode({
    name: "Campus map",
    text: "Level one and level two.",
    mapType: "Venue",
  }),
  medicalEntityNode({
    name: "Clinical guidance entity",
  }),
  medicalIntangibleNode({
    name: "Clinical recommendation",
  }),
  medicalAudienceNode({
    name: "Adults with hypertension",
    audienceType: "Adult patients",
  }),
  medicalCauseNode({
    name: "Smoking",
  }),
  medicalCodeNode({
    name: "ICD sample",
    codeValue: "I10",
    codingSystem: "ICD-10",
  }),
  medicalConditionNode({
    name: "Hypertension",
  }),
  medicalConditionStageNode({
    name: "Stage 1 hypertension",
  }),
  medicalContraindicationNode({
    name: "Do not combine therapies",
  }),
  medicalDeviceNode({
    name: "Blood pressure cuff",
  }),
  medicalGuidelineNode({
    name: "Hypertension guidance",
  }),
  medicalProcedureNode({
    name: "Blood pressure monitoring",
  }),
  medicalRiskFactorNode({
    name: "Smoking risk factor",
  }),
  medicalSignNode({
    name: "Elevated blood pressure",
  }),
  medicalSignOrSymptomNode({
    name: "Headache",
  }),
  medicalStudyNode({
    name: "Longitudinal hypertension study",
    status: "Active",
  }),
  medicalTestNode({
    name: "Blood pressure reading",
  }),
  medicalTherapyNode({
    name: "Lifestyle counseling",
  }),
  medicalWebPageNode({
    name: "Medical page",
    lastReviewed: "2026-05-31",
  }),
  loyaltyProgramNode({
    name: "Example Member Program",
    url: "https://example.test/members",
    provider: organization,
  }),
  maximumDoseScheduleNode({
    name: "Maximum daily dose",
    doseUnit: "mg",
    frequency: "daily",
  }),
  mathSolverNode({
    name: "Markdown math solver",
    url: "https://example.test/math",
    mathExpression: "x + 1 = 2",
    potentialAction: solveMathActionNode({
      target: "https://example.test/math?q={mathExpression}",
      mathExpressionInput: "required name=mathExpression",
      eduQuestionType: ["Algebra"],
    }),
    learningResource: learningResourceNode({
      name: "Math Solver learning resource",
      url: "https://example.test/math/resource",
      learningResourceType: "Math Solver",
      teaches: ["Algebra"],
    }),
  }),
  learningResourceNode({
    name: "Math Solver learning resource",
    url: "https://example.test/math/resource",
    learningResourceType: "Math Solver",
    teaches: ["Algebra"],
  }),
  mediaGalleryNode({
    name: "Media gallery",
    hasPart: [{ "@type": "MediaObject", name: "Walkthrough clip" }],
  }),
  mediaObjectNode({
    name: "Release montage",
    contentUrl: "https://example.test/media.mp4",
    encodingFormat: "video/mp4",
  }),
  mediaSubscriptionNode({
    name: "Pro streaming",
    authenticatingAuthority: organization,
    expectsAcceptanceOf: [{ "@type": "Thing", name: "Terms of service" }],
  }),
  memberProgramTierNode({
    name: "Gold tier",
    membershipPointsRequired: 5000,
    hasTierBenefit: ["Priority support"],
  }),
  programMembershipNode({
    name: "Partner program",
    hostingOrganization: organization,
    membershipNumber: "PM-42",
    programName: "Partners",
  }),
  publicationEventNode({
    name: "Launch publication",
    publishedBy: organization,
    startDate: "2026-05-27T10:00:00Z",
  }),
  repaymentSpecificationNode({
    name: "Standard repayment",
    numberOfLoanPayments: 12,
    loanPaymentFrequency: 1,
  }),
  scheduleNode({
    name: "Release calendar",
    repeatFrequency: "P1W",
    byDay: ["Monday"],
    startDate: "2026-05-27",
    endDate: "2026-06-27",
  }),
  seriesNode({
    name: "Operations series",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
  }),
  serviceNode({
    name: "Prompt advisory",
    serviceType: "Consulting",
    areaServed: { "@type": "AdministrativeArea", name: "Illinois" },
    provider: organization,
  }),
  serviceChannelNode({
    name: "Web support",
    processingTime: "P1D",
    serviceUrl: "https://example.test/support",
  }),
  servicePeriodNode({
    name: "Handling window",
    cutoffTime: "17:00:00-05:00",
    startDate: "2026-05-27",
    endDate: "2026-06-27",
  }),
  shippingConditionsNode({
    name: "Domestic parcel conditions",
    shippingDestination: { "@type": "DefinedRegion", name: "US" },
    shippingOrigin: { "@type": "Place", name: "Chicago" },
  }),
  shippingDeliveryTimeNode({
    name: "Ground delivery",
    cutoffTime: "17:00:00-05:00",
  }),
  shippingRateSettingsNode({
    name: "US shipping rates",
    shippingDestination: { "@type": "DefinedRegion", name: "US" },
  }),
  shippingServiceNode({
    name: "Ground shipping",
    shippingConditions: { "@type": "Thing", name: "Standard conditions" },
  }),
  statisticalVariableNode({
    name: "Incident volume",
    measurementMethod: "count",
    measurementTechnique: "manual review",
    populationType: { "@type": "Audience", name: "Operators" },
  }),
  substanceNode({
    name: "Caffeine",
    activeIngredient: "Caffeine",
  }),
  taxonNode({
    name: "Promptidae",
    parentTaxon: { "@type": "Taxon", name: "Automation" },
    taxonRank: "family",
  }),
  superficialAnatomyNode({
    name: "Upper arm",
    associatedPathophysiology: "Localized inflammation.",
  }),
  runtimePlatformNode({
    name: "Node.js runtime",
    applicationCategory: "DeveloperApplication",
    operatingSystem: "Cross-platform",
  }),
  operatingSystemNode({
    name: "PromptOS",
    applicationCategory: "SystemApplication",
    softwareVersion: "1.0.0",
  }),
  solveMathActionNode({
    target: "https://example.test/math?q={mathExpression}",
    mathExpressionInput: "required name=mathExpression",
    eduQuestionType: ["Algebra"],
  }),
  merchantReturnPolicyNode({
    name: "Return policy",
    url: "https://example.test/returns",
    merchantReturnDays: 30,
  }),
  merchantReturnPolicySeasonalOverrideNode({
    name: "Holiday returns",
    merchantReturnDays: 60,
    startDate: "2026-11-15",
    endDate: "2027-01-15",
  }),
  menuItemNode({
    name: "Launch latte",
    offers: [offerNode({ name: "Cup", price: "6.00", priceCurrency: "USD" })],
    suitableForDiet: ["https://schema.org/VegetarianDiet"],
  }),
  menuSectionNode({
    name: "Release drinks",
    hasMenuItem: [{ "@type": "MenuItem", name: "Launch latte" }],
  }),
  offerShippingDetailsNode({
    name: "Shipping policy",
    shippingDestination: "US",
  }),
  movieNode({
    name: "Structured Data Demo",
    url: "https://example.test/movie",
    director: organization,
  }),
  musicAlbumNode({
    name: "Release Waves",
    byArtist: [{ "@type": "MusicGroup", name: "MDWRK Ensemble" }],
    track: [{ "@type": "MusicRecording", name: "Deploy Overture" }],
    numTracks: 1,
  }),
  musicCompositionNode({
    name: "Deploy Overture",
    composer: [{ "@type": "Person", name: "Casey Prompt" }],
    lyricist: [{ "@type": "Person", name: "Jordan Schema" }],
  }),
  musicGroupNode({
    name: "MDWRK Ensemble",
    album: [{ "@type": "MusicAlbum", name: "Release Waves" }],
    track: [{ "@type": "MusicRecording", name: "Deploy Overture" }],
  }),
  musicPlaylistNode({
    name: "Launch queue",
    track: [{ "@type": "MusicRecording", name: "Deploy Overture" }],
    numTracks: 1,
  }),
  musicRecordingNode({
    name: "Deploy Overture",
    byArtist: [{ "@type": "MusicGroup", name: "MDWRK Ensemble" }],
    inAlbum: [{ "@type": "MusicAlbum", name: "Release Waves" }],
    duration: "PT3M",
  }),
  musicReleaseNode({
    name: "Release Waves v1",
    catalogNumber: "REL-001",
    musicReleaseFormat: "Digital",
    recordLabel: organization,
  }),
  clipNode({
    name: "Key moment",
    url: "https://example.test/videos/demo?t=15",
    startOffset: 15,
    endOffset: 45,
  }),
  broadcastEventNode({
    name: "Live structured data stream",
    startDate: "2026-05-06T12:00:00Z",
    endDate: "2026-05-06T13:00:00Z",
    isLiveBroadcast: true,
  }),
  productGroupNode({
    name: "Example Product Family",
    url: "https://example.test/products/family",
    hasVariant: product,
  }),
  productModelNode({
    name: "Prompt Device 2",
    brand: organization,
    model: "PD-2",
    isVariantOf: { "@type": "ProductGroup", name: "Prompt Device Family" },
  }),
  recipeNode({
    name: "Structured data recipe",
    url: "https://example.test/recipes/structured-data",
    recipeIngredient: ["Visible content", "Typed builder"],
    recipeInstructions: [{ name: "Render", text: "Render the visible recipe step." }],
    author: organization,
  }),
  nutritionInformationNode({
    name: "Nutrition facts",
    servingSize: "1 bar",
    calories: "200 kcal",
    proteinContent: "10 g",
  }),
  occupationNode({
    name: "Prompt operations engineer",
    educationRequirements: "BS or equivalent",
    skills: ["Prompt evaluation"],
  }),
  occupationalExperienceRequirementsNode({
    name: "Prompt operations track record",
    monthsOfExperience: 24,
    occupationalExperienceProperties: { "@type": "PropertyValue", name: "Incidents handled", value: 12 },
  }),
  offerNode({
    name: "Starter offer",
    price: "10.00",
    priceCurrency: "USD",
    seller: organization,
  }),
  offerCatalogNode({
    name: "Offer catalog",
    numberOfItems: 2,
    itemListElement: [{ "@type": "Offer", name: "Starter" }],
  }),
  openingHoursSpecificationNode({
    name: "Weekday hours",
    opens: "09:00",
    closes: "17:00",
    dayOfWeek: ["Monday", "Tuesday"],
  }),
  speakableSpecificationNode({ cssSelector: [".answer-summary"] }),
  therapeuticProcedureNode({
    name: "Guided breathing exercise",
  }),
  textObjectNode({
    name: "Launch transcript",
    text: "Transcript body",
    encodingFormat: "text/plain",
  }),
  tripNode({
    name: "Operator summit trip",
    departureTime: "2026-06-10T09:00:00Z",
    arrivalTime: "2026-06-10T12:00:00Z",
    tripOrigin: { "@type": "Place", name: "Chicago" },
    itinerary: [{ "@type": "Place", name: "Austin" }],
    provider: organization,
  }),
  typeAndQuantityNode({
    name: "Bundle quantity",
    amountOfThisGood: 2,
    businessFunction: "http://purl.org/goodrelations/v1#Sell",
    typeOfGood: { "@type": "Product", name: "Prompt Device" },
    unitCode: "C62",
  }),
  unitPriceSpecificationNode({
    name: "Seat price",
    price: "29.00",
    priceCurrency: "USD",
    unitCode: "MON",
    referenceQuantity: 1,
  }),
  warrantyPromiseNode({
    name: "Limited warranty",
    durationOfWarranty: 12,
    warrantyScope: "https://schema.org/Labor-BringIn",
  }),
  webContentNode({
    name: "Knowledge base article",
    text: "Visible body text.",
    author: organization,
  }),
  webPageElementNode({
    name: "Hero banner",
    text: "Top of page banner.",
    cssSelector: [".hero-banner"],
    xpath: ["//*[@id='hero-banner']"],
  }),
  paywalledContentSchema({
    name: "Subscriber guide",
    url: "https://example.test/subscriber-guide",
    cssSelector: [".subscriber-only"],
  }),
  vacationRentalNode({
    name: "Example Rental",
    url: "https://example.test/rentals/example",
    address: "100 Example Way",
  }),
  virtualLocationNode({
    name: "Virtual office",
    url: "https://example.test/meet",
  }),
  vehicleListingNode({
    name: "Example Vehicle",
    url: "https://example.test/vehicles/example",
    brand: organization,
    vehicleIdentificationNumber: "EXAMPLEVIN123",
  }),
  xPathTypeNode({}),
];

export const expectedTypes = [
  "Action",
  "AdministrativeArea",
  "Organization",
  "WebSite",
  "WebPage",
  "AggregateOffer",
  "Thing",
  "Intangible",
  "StructuredValue",
  "AlignmentObject",
  "Audience",
  "AudioObject",
  "Brand",
  "BroadcastChannel",
  "BroadcastFrequencySpecification",
  "BroadcastService",
  "SoftwareApplication",
  "WebApplication",
  "Article",
  "NewsArticle",
  "TechArticle",
  "BlogPosting",
  "BreadcrumbList",
  "Certification",
  "CableOrSatelliteService",
  "CivicStructure",
  "Claim",
  "ConstraintNode",
  "Comment",
  "ContactPoint",
  "CorrectionComment",
  "FAQPage",
  "QAPage",
  "QAPage",
  "Answer",
  "Question",
  "Quiz",
  "HowTo",
  "ItemList",
  "ItemList",
  "SoftwareSourceCode",
  "Product",
  "Product",
  "Product",
  "Dataset",
  "Event",
  "VideoObject",
  "ImageObject",
  "ProfilePage",
  "Review",
  "AggregateRating",
  "Course",
  "CourseInstance",
  "Country",
  "CreativeWork",
  "CreativeWorkSeason",
  "CreativeWorkSeries",
  "CategoryCode",
  "CategoryCodeSet",
  "Class",
  "Credential",
  "CreditCard",
  "CssSelectorType",
  "DataCatalog",
  "DataDownload",
  "DataFeed",
  "DataFeedItem",
  "ItemList",
  "DiscussionForumPosting",
  "DefinedRegion",
  "DefinedTerm",
  "DefinedTermSet",
  "DeliveryChargeSpecification",
  "Demand",
  "Distance",
  "Duration",
  "EducationalOccupationalCredential",
  "EducationalOrganization",
  "Energy",
  "EnergyConsumptionDetails",
  "EntryPoint",
  "Enumeration",
  "Episode",
  "Integer",
  "FinancialProduct",
  "Gene",
  "GeoCoordinates",
  "GeospatialGeometry",
  "GeoShape",
  "Grant",
  "HyperTocEntry",
  "HealthInsurancePlan",
  "HealthPlanCostSharingSpecification",
  "HealthPlanFormulary",
  "HealthPlanNetwork",
  "HowToItem",
  "HowToSection",
  "HowToStep",
  "HowToSupply",
  "HowToTool",
  "ImageGallery",
  "Language",
  "LifestyleModification",
  "InteractionCounter",
  "QuantitativeValue",
  "LoanOrCredit",
  "QuantitativeValueDistribution",
  "MonetaryAmount",
  "Rating",
  "Mass",
  "ListItem",
  "Property",
  "PropertyValue",
  "URL",
  "Book",
  "ReadAction",
  "ClaimReview",
  "EmployerAggregateRating",
  "MonetaryAmountDistribution",
  "JobPosting",
  "LocalBusiness",
  "LocationFeatureSpecification",
  "Map",
  "MedicalEntity",
  "MedicalIntangible",
  "MedicalAudience",
  "MedicalCause",
  "MedicalCode",
  "MedicalCondition",
  "MedicalConditionStage",
  "MedicalContraindication",
  "MedicalDevice",
  "MedicalGuideline",
  "MedicalProcedure",
  "MedicalRiskFactor",
  "MedicalSign",
  "MedicalSignOrSymptom",
  "MedicalStudy",
  "MedicalTest",
  "MedicalTherapy",
  "MedicalWebPage",
  "MemberProgram",
  "MaximumDoseSchedule",
  "MathSolver",
  "LearningResource",
  "MediaGallery",
  "MediaObject",
  "MediaSubscription",
  "MemberProgramTier",
  "ProgramMembership",
  "PublicationEvent",
  "RepaymentSpecification",
  "Schedule",
  "Series",
  "Service",
  "ServiceChannel",
  "ServicePeriod",
  "ShippingConditions",
  "ShippingDeliveryTime",
  "ShippingRateSettings",
  "ShippingService",
  "StatisticalVariable",
  "Substance",
  "Taxon",
  "SuperficialAnatomy",
  "RuntimePlatform",
  "OperatingSystem",
  "SolveMathAction",
  "MerchantReturnPolicy",
  "MerchantReturnPolicySeasonalOverride",
  "MenuItem",
  "MenuSection",
  "OfferShippingDetails",
  "Movie",
  "MusicAlbum",
  "MusicComposition",
  "MusicGroup",
  "MusicPlaylist",
  "MusicRecording",
  "MusicRelease",
  "Clip",
  "BroadcastEvent",
  "ProductGroup",
  "ProductModel",
  "Recipe",
  "NutritionInformation",
  "Occupation",
  "OccupationalExperienceRequirements",
  "Offer",
  "OfferCatalog",
  "OpeningHoursSpecification",
  "SpeakableSpecification",
  "TherapeuticProcedure",
  "TextObject",
  "Trip",
  "TypeAndQuantityNode",
  "UnitPriceSpecification",
  "WarrantyPromise",
  "WebContent",
  "WebPageElement",
  "WebPage",
  "VacationRental",
  "VirtualLocation",
  "Vehicle",
  "XPathType",
];

export const legacyFaq = faqSchema([{ question: "Legacy?", answer: "Still supported." }]);

export const generatedGraph = buildJsonLdGraph(
  {
    product: {
      name: "Example",
      slug: "example",
      tagline: "Tagline",
      description: "Description",
      category: "Software",
      canonicalUrl: "https://example.test",
      logo: { src: "https://example.test/logo.png" },
    },
  },
  {
    kind: "blog",
    slug: "/blog/launch",
    title: "Example Launch",
    description: "Long enough description.",
    h1: "Example Launch",
    canonicalUrl: "https://example.test/blog/launch",
    breadcrumbs: [{ label: "Home", href: "/" }],
    faq: [{ question: "Is this visible?", answer: "Yes." }],
    datePublished: "2026-05-06",
  },
);
