export { SchemaPropertyHasCertification } from "./components/schema-property-has-certification.js";
export type { SchemaPropertyHasCertificationProps } from "./components/schema-property-has-certification.js";
export { SchemaPropertyHasCredential } from "./components/schema-property-has-credential.js";
export type { SchemaPropertyHasCredentialProps } from "./components/schema-property-has-credential.js";
export { SchemaPropertyHasDefinedTerm } from "./components/schema-property-has-defined-term.js";
export type { SchemaPropertyHasDefinedTermProps } from "./components/schema-property-has-defined-term.js";
export { SchemaPropertyHasDriveThroughService } from "./components/schema-property-has-drive-through-service.js";
export type { SchemaPropertyHasDriveThroughServiceProps } from "./components/schema-property-has-drive-through-service.js";
export { SchemaPropertyHasEnergyConsumptionDetails } from "./components/schema-property-has-energy-consumption-details.js";
export type { SchemaPropertyHasEnergyConsumptionDetailsProps } from "./components/schema-property-has-energy-consumption-details.js";
export { SchemaPropertyHasEnergyEfficiencyCategory } from "./components/schema-property-has-energy-efficiency-category.js";
export type { SchemaPropertyHasEnergyEfficiencyCategoryProps } from "./components/schema-property-has-energy-efficiency-category.js";
export { SchemaPropertyHasGS1DigitalLink } from "./components/schema-property-has-g-s1-digital-link.js";
export type { SchemaPropertyHasGS1DigitalLinkProps } from "./components/schema-property-has-g-s1-digital-link.js";
export { SchemaPropertyHasMap } from "./components/schema-property-has-map.js";
export type { SchemaPropertyHasMapProps } from "./components/schema-property-has-map.js";
export { SchemaPropertyHasMeasurement } from "./components/schema-property-has-measurement.js";
export type { SchemaPropertyHasMeasurementProps } from "./components/schema-property-has-measurement.js";
export { SchemaPropertyHasMemberProgram } from "./components/schema-property-has-member-program.js";
export type { SchemaPropertyHasMemberProgramProps } from "./components/schema-property-has-member-program.js";
export { SchemaPropertyHasMenuItem } from "./components/schema-property-has-menu-item.js";
export type { SchemaPropertyHasMenuItemProps } from "./components/schema-property-has-menu-item.js";
export { SchemaPropertyHasMenuSection } from "./components/schema-property-has-menu-section.js";
export type { SchemaPropertyHasMenuSectionProps } from "./components/schema-property-has-menu-section.js";
export { SchemaPropertyHasMerchantReturnPolicy } from "./components/schema-property-has-merchant-return-policy.js";
export type { SchemaPropertyHasMerchantReturnPolicyProps } from "./components/schema-property-has-merchant-return-policy.js";
export { SchemaPropertyHasMolecularFunction } from "./components/schema-property-has-molecular-function.js";
export type { SchemaPropertyHasMolecularFunctionProps } from "./components/schema-property-has-molecular-function.js";
export { SchemaPropertyHasOccupation } from "./components/schema-property-has-occupation.js";
export type { SchemaPropertyHasOccupationProps } from "./components/schema-property-has-occupation.js";
export { SchemaPropertyHasOfferCatalog } from "./components/schema-property-has-offer-catalog.js";
export type { SchemaPropertyHasOfferCatalogProps } from "./components/schema-property-has-offer-catalog.js";
export { SchemaPropertyHasPart } from "./components/schema-property-has-part.js";
export type { SchemaPropertyHasPartProps } from "./components/schema-property-has-part.js";
export { SchemaPropertyHasParticipationOffer } from "./components/schema-property-has-participation-offer.js";
export type { SchemaPropertyHasParticipationOfferProps } from "./components/schema-property-has-participation-offer.js";
export { SchemaPropertyHasPOS } from "./components/schema-property-has-pos.js";
export type { SchemaPropertyHasPOSProps } from "./components/schema-property-has-pos.js";
export { SchemaPropertyHasRepresentation } from "./components/schema-property-has-representation.js";
export type { SchemaPropertyHasRepresentationProps } from "./components/schema-property-has-representation.js";
export { SchemaPropertyHasShippingService } from "./components/schema-property-has-shipping-service.js";
export type { SchemaPropertyHasShippingServiceProps } from "./components/schema-property-has-shipping-service.js";
export { SchemaPropertyHasSponsorshipOffer } from "./components/schema-property-has-sponsorship-offer.js";
export type { SchemaPropertyHasSponsorshipOfferProps } from "./components/schema-property-has-sponsorship-offer.js";
export { SchemaPropertyHasTierBenefit } from "./components/schema-property-has-tier-benefit.js";
export type { SchemaPropertyHasTierBenefitProps } from "./components/schema-property-has-tier-benefit.js";
export { SchemaPropertyHasTierRequirement } from "./components/schema-property-has-tier-requirement.js";
export type { SchemaPropertyHasTierRequirementProps } from "./components/schema-property-has-tier-requirement.js";
export { SchemaPropertyHasTiers } from "./components/schema-property-has-tiers.js";
export type { SchemaPropertyHasTiersProps } from "./components/schema-property-has-tiers.js";
export { SchemaPropertyHasVariant } from "./components/schema-property-has-variant.js";
export type { SchemaPropertyHasVariantProps } from "./components/schema-property-has-variant.js";
export { SchemaPropertyHeadline } from "./components/schema-property-headline.js";
export type { SchemaPropertyHeadlineProps } from "./components/schema-property-headline.js";
export { SchemaPropertyHealthCondition } from "./components/schema-property-health-condition.js";
export type { SchemaPropertyHealthConditionProps } from "./components/schema-property-health-condition.js";
export { SchemaPropertyHealthPlanCoinsuranceOption } from "./components/schema-property-health-plan-coinsurance-option.js";
export type { SchemaPropertyHealthPlanCoinsuranceOptionProps } from "./components/schema-property-health-plan-coinsurance-option.js";
export { SchemaPropertyHealthPlanCoinsuranceRate } from "./components/schema-property-health-plan-coinsurance-rate.js";
export type { SchemaPropertyHealthPlanCoinsuranceRateProps } from "./components/schema-property-health-plan-coinsurance-rate.js";
export { SchemaPropertyHealthPlanCopay } from "./components/schema-property-health-plan-copay.js";
export type { SchemaPropertyHealthPlanCopayProps } from "./components/schema-property-health-plan-copay.js";
export { SchemaPropertyHealthPlanCopayOption } from "./components/schema-property-health-plan-copay-option.js";
export type { SchemaPropertyHealthPlanCopayOptionProps } from "./components/schema-property-health-plan-copay-option.js";
export { SchemaPropertyHealthPlanCostSharing } from "./components/schema-property-health-plan-cost-sharing.js";
export type { SchemaPropertyHealthPlanCostSharingProps } from "./components/schema-property-health-plan-cost-sharing.js";
export { SchemaPropertyHealthPlanDrugOption } from "./components/schema-property-health-plan-drug-option.js";
export type { SchemaPropertyHealthPlanDrugOptionProps } from "./components/schema-property-health-plan-drug-option.js";
export { SchemaPropertyHealthPlanDrugTier } from "./components/schema-property-health-plan-drug-tier.js";
export type { SchemaPropertyHealthPlanDrugTierProps } from "./components/schema-property-health-plan-drug-tier.js";
export { SchemaPropertyHealthPlanId } from "./components/schema-property-health-plan-id.js";
export type { SchemaPropertyHealthPlanIdProps } from "./components/schema-property-health-plan-id.js";
export { SchemaPropertyHealthPlanMarketingUrl } from "./components/schema-property-health-plan-marketing-url.js";
export type { SchemaPropertyHealthPlanMarketingUrlProps } from "./components/schema-property-health-plan-marketing-url.js";
export { SchemaPropertyHealthPlanNetworkId } from "./components/schema-property-health-plan-network-id.js";
export type { SchemaPropertyHealthPlanNetworkIdProps } from "./components/schema-property-health-plan-network-id.js";
export { SchemaPropertyHealthPlanNetworkTier } from "./components/schema-property-health-plan-network-tier.js";
export type { SchemaPropertyHealthPlanNetworkTierProps } from "./components/schema-property-health-plan-network-tier.js";
export { SchemaPropertyHealthPlanPharmacyCategory } from "./components/schema-property-health-plan-pharmacy-category.js";
export type { SchemaPropertyHealthPlanPharmacyCategoryProps } from "./components/schema-property-health-plan-pharmacy-category.js";
export { SchemaPropertyHeight } from "./components/schema-property-height.js";
export type { SchemaPropertyHeightProps } from "./components/schema-property-height.js";
export { SchemaPropertyHighPrice } from "./components/schema-property-high-price.js";
export type { SchemaPropertyHighPriceProps } from "./components/schema-property-high-price.js";
export { SchemaPropertyHomeLocation } from "./components/schema-property-home-location.js";
export type { SchemaPropertyHomeLocationProps } from "./components/schema-property-home-location.js";
export { SchemaPropertyHonorificPrefix } from "./components/schema-property-honorific-prefix.js";
export type { SchemaPropertyHonorificPrefixProps } from "./components/schema-property-honorific-prefix.js";
export { SchemaPropertyHonorificSuffix } from "./components/schema-property-honorific-suffix.js";
export type { SchemaPropertyHonorificSuffixProps } from "./components/schema-property-honorific-suffix.js";
export { SchemaPropertyHostingOrganization } from "./components/schema-property-hosting-organization.js";
export type { SchemaPropertyHostingOrganizationProps } from "./components/schema-property-hosting-organization.js";
export { SchemaPropertyHoursAvailable } from "./components/schema-property-hours-available.js";
export type { SchemaPropertyHoursAvailableProps } from "./components/schema-property-hours-available.js";
export { SchemaPropertyHowPerformed } from "./components/schema-property-how-performed.js";
export type { SchemaPropertyHowPerformedProps } from "./components/schema-property-how-performed.js";
export { SchemaPropertyHttpMethod } from "./components/schema-property-http-method.js";
export type { SchemaPropertyHttpMethodProps } from "./components/schema-property-http-method.js";
export { SchemaPropertyIdentifier } from "./components/schema-property-identifier.js";
export type { SchemaPropertyIdentifierProps } from "./components/schema-property-identifier.js";
export { SchemaPropertyIdentifyingExam } from "./components/schema-property-identifying-exam.js";
export type { SchemaPropertyIdentifyingExamProps } from "./components/schema-property-identifying-exam.js";
export { SchemaPropertyIdentifyingTest } from "./components/schema-property-identifying-test.js";
export type { SchemaPropertyIdentifyingTestProps } from "./components/schema-property-identifying-test.js";
export { SchemaPropertyImage } from "./components/schema-property-image.js";
export type { SchemaPropertyImageProps } from "./components/schema-property-image.js";
export { SchemaPropertyInAlbum } from "./components/schema-property-in-album.js";
export type { SchemaPropertyInAlbumProps } from "./components/schema-property-in-album.js";
export { SchemaPropertyInBroadcastLineup } from "./components/schema-property-in-broadcast-lineup.js";
export type { SchemaPropertyInBroadcastLineupProps } from "./components/schema-property-in-broadcast-lineup.js";
export { SchemaPropertyIncludedComposition } from "./components/schema-property-included-composition.js";
export type { SchemaPropertyIncludedCompositionProps } from "./components/schema-property-included-composition.js";
export { SchemaPropertyIncludedDataCatalog } from "./components/schema-property-included-data-catalog.js";
export type { SchemaPropertyIncludedDataCatalogProps } from "./components/schema-property-included-data-catalog.js";
export { SchemaPropertyIncludedInDataCatalog } from "./components/schema-property-included-in-data-catalog.js";
export type { SchemaPropertyIncludedInDataCatalogProps } from "./components/schema-property-included-in-data-catalog.js";
export { SchemaPropertyIncludedInHealthInsurancePlan } from "./components/schema-property-included-in-health-insurance-plan.js";
export type { SchemaPropertyIncludedInHealthInsurancePlanProps } from "./components/schema-property-included-in-health-insurance-plan.js";
export { SchemaPropertyIncludesHealthPlanFormulary } from "./components/schema-property-includes-health-plan-formulary.js";
export type { SchemaPropertyIncludesHealthPlanFormularyProps } from "./components/schema-property-includes-health-plan-formulary.js";
export { SchemaPropertyIncludesHealthPlanNetwork } from "./components/schema-property-includes-health-plan-network.js";
export type { SchemaPropertyIncludesHealthPlanNetworkProps } from "./components/schema-property-includes-health-plan-network.js";
export { SchemaPropertyIncludesObject } from "./components/schema-property-includes-object.js";
export type { SchemaPropertyIncludesObjectProps } from "./components/schema-property-includes-object.js";
export { SchemaPropertyInCodeSet } from "./components/schema-property-in-code-set.js";
export type { SchemaPropertyInCodeSetProps } from "./components/schema-property-in-code-set.js";
export { SchemaPropertyIncreasesRiskOf } from "./components/schema-property-increases-risk-of.js";
export type { SchemaPropertyIncreasesRiskOfProps } from "./components/schema-property-increases-risk-of.js";
export { SchemaPropertyInDefinedTermSet } from "./components/schema-property-in-defined-term-set.js";
export type { SchemaPropertyInDefinedTermSetProps } from "./components/schema-property-in-defined-term-set.js";
export { SchemaPropertyIneligibleRegion } from "./components/schema-property-ineligible-region.js";
export type { SchemaPropertyIneligibleRegionProps } from "./components/schema-property-ineligible-region.js";
export { SchemaPropertyInLanguage } from "./components/schema-property-in-language.js";
export type { SchemaPropertyInLanguageProps } from "./components/schema-property-in-language.js";
export { SchemaPropertyInPlaylist } from "./components/schema-property-in-playlist.js";
export type { SchemaPropertyInPlaylistProps } from "./components/schema-property-in-playlist.js";
export { SchemaPropertyInProductGroupWithID } from "./components/schema-property-in-product-group-with-id.js";
export type { SchemaPropertyInProductGroupWithIDProps } from "./components/schema-property-in-product-group-with-id.js";
export { SchemaPropertyInstallUrl } from "./components/schema-property-install-url.js";
export type { SchemaPropertyInstallUrlProps } from "./components/schema-property-install-url.js";
export { SchemaPropertyInStoreReturnsOffered } from "./components/schema-property-in-store-returns-offered.js";
export type { SchemaPropertyInStoreReturnsOfferedProps } from "./components/schema-property-in-store-returns-offered.js";
export { SchemaPropertyInstrument } from "./components/schema-property-instrument.js";
export type { SchemaPropertyInstrumentProps } from "./components/schema-property-instrument.js";
export { SchemaPropertyInteractingDrug } from "./components/schema-property-interacting-drug.js";
export type { SchemaPropertyInteractingDrugProps } from "./components/schema-property-interacting-drug.js";
export { SchemaPropertyInteractionService } from "./components/schema-property-interaction-service.js";
export type { SchemaPropertyInteractionServiceProps } from "./components/schema-property-interaction-service.js";
export { SchemaPropertyInteractionStatistic } from "./components/schema-property-interaction-statistic.js";
export type { SchemaPropertyInteractionStatisticProps } from "./components/schema-property-interaction-statistic.js";