export { SchemaPropertyDeliveryTime } from "./components/schema-property-delivery-time.js";
export type { SchemaPropertyDeliveryTimeProps } from "./components/schema-property-delivery-time.js";
export { SchemaPropertyDepartment } from "./components/schema-property-department.js";
export type { SchemaPropertyDepartmentProps } from "./components/schema-property-department.js";
export { SchemaPropertyDepartureTime } from "./components/schema-property-departure-time.js";
export type { SchemaPropertyDepartureTimeProps } from "./components/schema-property-departure-time.js";
export { SchemaPropertyDepth } from "./components/schema-property-depth.js";
export type { SchemaPropertyDepthProps } from "./components/schema-property-depth.js";
export { SchemaPropertyDescription } from "./components/schema-property-description.js";
export type { SchemaPropertyDescriptionProps } from "./components/schema-property-description.js";
export { SchemaPropertyDevice } from "./components/schema-property-device.js";
export type { SchemaPropertyDeviceProps } from "./components/schema-property-device.js";
export { SchemaPropertyDiagnosis } from "./components/schema-property-diagnosis.js";
export type { SchemaPropertyDiagnosisProps } from "./components/schema-property-diagnosis.js";
export { SchemaPropertyDiagram } from "./components/schema-property-diagram.js";
export type { SchemaPropertyDiagramProps } from "./components/schema-property-diagram.js";
export { SchemaPropertyDietFeatures } from "./components/schema-property-diet-features.js";
export type { SchemaPropertyDietFeaturesProps } from "./components/schema-property-diet-features.js";
export { SchemaPropertyDifferentialDiagnosis } from "./components/schema-property-differential-diagnosis.js";
export type { SchemaPropertyDifferentialDiagnosisProps } from "./components/schema-property-differential-diagnosis.js";
export { SchemaPropertyDigitalSourceType } from "./components/schema-property-digital-source-type.js";
export type { SchemaPropertyDigitalSourceTypeProps } from "./components/schema-property-digital-source-type.js";
export { SchemaPropertyDirector } from "./components/schema-property-director.js";
export type { SchemaPropertyDirectorProps } from "./components/schema-property-director.js";
export { SchemaPropertyDirectors } from "./components/schema-property-directors.js";
export type { SchemaPropertyDirectorsProps } from "./components/schema-property-directors.js";
export { SchemaPropertyDisambiguatingDescription } from "./components/schema-property-disambiguating-description.js";
export type { SchemaPropertyDisambiguatingDescriptionProps } from "./components/schema-property-disambiguating-description.js";
export { SchemaPropertyDiscussionUrl } from "./components/schema-property-discussion-url.js";
export type { SchemaPropertyDiscussionUrlProps } from "./components/schema-property-discussion-url.js";
export { SchemaPropertyDisplayLocation } from "./components/schema-property-display-location.js";
export type { SchemaPropertyDisplayLocationProps } from "./components/schema-property-display-location.js";
export { SchemaPropertyDissolutionDate } from "./components/schema-property-dissolution-date.js";
export type { SchemaPropertyDissolutionDateProps } from "./components/schema-property-dissolution-date.js";
export { SchemaPropertyDistinguishingSign } from "./components/schema-property-distinguishing-sign.js";
export type { SchemaPropertyDistinguishingSignProps } from "./components/schema-property-distinguishing-sign.js";
export { SchemaPropertyDistribution } from "./components/schema-property-distribution.js";
export type { SchemaPropertyDistributionProps } from "./components/schema-property-distribution.js";
export { SchemaPropertyDiversityPolicy } from "./components/schema-property-diversity-policy.js";
export type { SchemaPropertyDiversityPolicyProps } from "./components/schema-property-diversity-policy.js";
export { SchemaPropertyDiversityStaffingReport } from "./components/schema-property-diversity-staffing-report.js";
export type { SchemaPropertyDiversityStaffingReportProps } from "./components/schema-property-diversity-staffing-report.js";
export { SchemaPropertyDoesNotShip } from "./components/schema-property-does-not-ship.js";
export type { SchemaPropertyDoesNotShipProps } from "./components/schema-property-does-not-ship.js";
export { SchemaPropertyDomainIncludes } from "./components/schema-property-domain-includes.js";
export type { SchemaPropertyDomainIncludesProps } from "./components/schema-property-domain-includes.js";
export { SchemaPropertyDoorTime } from "./components/schema-property-door-time.js";
export type { SchemaPropertyDoorTimeProps } from "./components/schema-property-door-time.js";
export { SchemaPropertyDosageForm } from "./components/schema-property-dosage-form.js";
export type { SchemaPropertyDosageFormProps } from "./components/schema-property-dosage-form.js";
export { SchemaPropertyDoseSchedule } from "./components/schema-property-dose-schedule.js";
export type { SchemaPropertyDoseScheduleProps } from "./components/schema-property-dose-schedule.js";
export { SchemaPropertyDoseUnit } from "./components/schema-property-dose-unit.js";
export type { SchemaPropertyDoseUnitProps } from "./components/schema-property-dose-unit.js";
export { SchemaPropertyDoseValue } from "./components/schema-property-dose-value.js";
export type { SchemaPropertyDoseValueProps } from "./components/schema-property-dose-value.js";
export { SchemaPropertyDownloadUrl } from "./components/schema-property-download-url.js";
export type { SchemaPropertyDownloadUrlProps } from "./components/schema-property-download-url.js";
export { SchemaPropertyDownPayment } from "./components/schema-property-down-payment.js";
export type { SchemaPropertyDownPaymentProps } from "./components/schema-property-down-payment.js";
export { SchemaPropertyDownvoteCount } from "./components/schema-property-downvote-count.js";
export type { SchemaPropertyDownvoteCountProps } from "./components/schema-property-downvote-count.js";
export { SchemaPropertyDrug } from "./components/schema-property-drug.js";
export type { SchemaPropertyDrugProps } from "./components/schema-property-drug.js";
export { SchemaPropertyDrugClass } from "./components/schema-property-drug-class.js";
export type { SchemaPropertyDrugClassProps } from "./components/schema-property-drug-class.js";
export { SchemaPropertyDrugUnit } from "./components/schema-property-drug-unit.js";
export type { SchemaPropertyDrugUnitProps } from "./components/schema-property-drug-unit.js";
export { SchemaPropertyDuns } from "./components/schema-property-duns.js";
export type { SchemaPropertyDunsProps } from "./components/schema-property-duns.js";
export { SchemaPropertyDuplicateTherapy } from "./components/schema-property-duplicate-therapy.js";
export type { SchemaPropertyDuplicateTherapyProps } from "./components/schema-property-duplicate-therapy.js";
export { SchemaPropertyDuration } from "./components/schema-property-duration.js";
export type { SchemaPropertyDurationProps } from "./components/schema-property-duration.js";
export { SchemaPropertyDurationOfWarranty } from "./components/schema-property-duration-of-warranty.js";
export type { SchemaPropertyDurationOfWarrantyProps } from "./components/schema-property-duration-of-warranty.js";
export { SchemaPropertyEarlyPrepaymentPenalty } from "./components/schema-property-early-prepayment-penalty.js";
export type { SchemaPropertyEarlyPrepaymentPenaltyProps } from "./components/schema-property-early-prepayment-penalty.js";
export { SchemaPropertyEditEIDR } from "./components/schema-property-edit-eidr.js";
export type { SchemaPropertyEditEIDRProps } from "./components/schema-property-edit-eidr.js";
export { SchemaPropertyEditor } from "./components/schema-property-editor.js";
export type { SchemaPropertyEditorProps } from "./components/schema-property-editor.js";
export { SchemaPropertyEducationalAlignment } from "./components/schema-property-educational-alignment.js";
export type { SchemaPropertyEducationalAlignmentProps } from "./components/schema-property-educational-alignment.js";
export { SchemaPropertyEducationalFramework } from "./components/schema-property-educational-framework.js";
export type { SchemaPropertyEducationalFrameworkProps } from "./components/schema-property-educational-framework.js";
export { SchemaPropertyEducationalLevel } from "./components/schema-property-educational-level.js";
export type { SchemaPropertyEducationalLevelProps } from "./components/schema-property-educational-level.js";
export { SchemaPropertyEducationalUse } from "./components/schema-property-educational-use.js";
export type { SchemaPropertyEducationalUseProps } from "./components/schema-property-educational-use.js";
export { SchemaPropertyEducationRequirements } from "./components/schema-property-education-requirements.js";
export type { SchemaPropertyEducationRequirementsProps } from "./components/schema-property-education-requirements.js";
export { SchemaPropertyElevation } from "./components/schema-property-elevation.js";
export type { SchemaPropertyElevationProps } from "./components/schema-property-elevation.js";
export { SchemaPropertyEligibleCustomerType } from "./components/schema-property-eligible-customer-type.js";
export type { SchemaPropertyEligibleCustomerTypeProps } from "./components/schema-property-eligible-customer-type.js";
export { SchemaPropertyEligibleDuration } from "./components/schema-property-eligible-duration.js";
export type { SchemaPropertyEligibleDurationProps } from "./components/schema-property-eligible-duration.js";
export { SchemaPropertyEligibleQuantity } from "./components/schema-property-eligible-quantity.js";
export type { SchemaPropertyEligibleQuantityProps } from "./components/schema-property-eligible-quantity.js";
export { SchemaPropertyEligibleRegion } from "./components/schema-property-eligible-region.js";
export type { SchemaPropertyEligibleRegionProps } from "./components/schema-property-eligible-region.js";
export { SchemaPropertyEligibleTransactionVolume } from "./components/schema-property-eligible-transaction-volume.js";
export type { SchemaPropertyEligibleTransactionVolumeProps } from "./components/schema-property-eligible-transaction-volume.js";
export { SchemaPropertyEmail } from "./components/schema-property-email.js";
export type { SchemaPropertyEmailProps } from "./components/schema-property-email.js";
export { SchemaPropertyEmbeddedTextCaption } from "./components/schema-property-embedded-text-caption.js";
export type { SchemaPropertyEmbeddedTextCaptionProps } from "./components/schema-property-embedded-text-caption.js";
export { SchemaPropertyEmbedUrl } from "./components/schema-property-embed-url.js";
export type { SchemaPropertyEmbedUrlProps } from "./components/schema-property-embed-url.js";
export { SchemaPropertyEmployee } from "./components/schema-property-employee.js";
export type { SchemaPropertyEmployeeProps } from "./components/schema-property-employee.js";
export { SchemaPropertyEmployees } from "./components/schema-property-employees.js";
export type { SchemaPropertyEmployeesProps } from "./components/schema-property-employees.js";
export { SchemaPropertyEncodesBioChemEntity } from "./components/schema-property-encodes-bio-chem-entity.js";
export type { SchemaPropertyEncodesBioChemEntityProps } from "./components/schema-property-encodes-bio-chem-entity.js";
export { SchemaPropertyEncodesCreativeWork } from "./components/schema-property-encodes-creative-work.js";
export type { SchemaPropertyEncodesCreativeWorkProps } from "./components/schema-property-encodes-creative-work.js";
export { SchemaPropertyEncoding } from "./components/schema-property-encoding.js";
export type { SchemaPropertyEncodingProps } from "./components/schema-property-encoding.js";
export { SchemaPropertyEncodingFormat } from "./components/schema-property-encoding-format.js";
export type { SchemaPropertyEncodingFormatProps } from "./components/schema-property-encoding-format.js";
export { SchemaPropertyEncodings } from "./components/schema-property-encodings.js";
export type { SchemaPropertyEncodingsProps } from "./components/schema-property-encodings.js";
export { SchemaPropertyEncodingType } from "./components/schema-property-encoding-type.js";
export type { SchemaPropertyEncodingTypeProps } from "./components/schema-property-encoding-type.js";
export { SchemaPropertyEndDate } from "./components/schema-property-end-date.js";
export type { SchemaPropertyEndDateProps } from "./components/schema-property-end-date.js";
export { SchemaPropertyEndOffset } from "./components/schema-property-end-offset.js";
export type { SchemaPropertyEndOffsetProps } from "./components/schema-property-end-offset.js";
export { SchemaPropertyEndorsers } from "./components/schema-property-endorsers.js";
export type { SchemaPropertyEndorsersProps } from "./components/schema-property-endorsers.js";
export { SchemaPropertyEndTime } from "./components/schema-property-end-time.js";
export type { SchemaPropertyEndTimeProps } from "./components/schema-property-end-time.js";
export { SchemaPropertyEnergyEfficiencyScaleMax } from "./components/schema-property-energy-efficiency-scale-max.js";
export type { SchemaPropertyEnergyEfficiencyScaleMaxProps } from "./components/schema-property-energy-efficiency-scale-max.js";
export { SchemaPropertyEnergyEfficiencyScaleMin } from "./components/schema-property-energy-efficiency-scale-min.js";
export type { SchemaPropertyEnergyEfficiencyScaleMinProps } from "./components/schema-property-energy-efficiency-scale-min.js";
export { SchemaPropertyEpidemiology } from "./components/schema-property-epidemiology.js";
export type { SchemaPropertyEpidemiologyProps } from "./components/schema-property-epidemiology.js";
export { SchemaPropertyEpisode } from "./components/schema-property-episode.js";
export type { SchemaPropertyEpisodeProps } from "./components/schema-property-episode.js";
export { SchemaPropertyEpisodeNumber } from "./components/schema-property-episode-number.js";
export type { SchemaPropertyEpisodeNumberProps } from "./components/schema-property-episode-number.js";
export { SchemaPropertyEpisodes } from "./components/schema-property-episodes.js";
export type { SchemaPropertyEpisodesProps } from "./components/schema-property-episodes.js";
export { SchemaPropertyError } from "./components/schema-property-error.js";
export type { SchemaPropertyErrorProps } from "./components/schema-property-error.js";
export { SchemaPropertyEstimatedCost } from "./components/schema-property-estimated-cost.js";
export type { SchemaPropertyEstimatedCostProps } from "./components/schema-property-estimated-cost.js";