import { SchemaPropertyUsesDevice, SchemaPropertyUsesHealthPlanIdStandard, SchemaPropertyUtterances, SchemaPropertyValidFor, SchemaPropertyValidForMemberTier, SchemaPropertyValidFrom, SchemaPropertyValidIn, SchemaPropertyValidThrough, SchemaPropertyValue, SchemaPropertyValueAddedTaxIncluded, SchemaPropertyValueReference, SchemaPropertyVariableMeasured, SchemaPropertyVariesBy, SchemaPropertyVatID, SchemaPropertyVersion, SchemaPropertyVideo, SchemaPropertyVideoFormat, SchemaPropertyVideoFrameSize, SchemaPropertyVideoQuality, SchemaPropertyWarning, SchemaPropertyWarranty, SchemaPropertyWarrantyScope, SchemaPropertyWeight, SchemaPropertyWeightPercentage, SchemaPropertyWidth, SchemaPropertyWordCount, SchemaPropertyWorkExample, SchemaPropertyWorkFeatured, SchemaPropertyWorkLocation, SchemaPropertyWorkPerformed, SchemaPropertyWorksFor, SchemaPropertyWorkTranslation, SchemaPropertyWorstRating, SchemaPropertyXpath, SchemaPropertyYield } from "./exports-013.js";

export const SCHEMAORG_PROPERTY_COMPONENTS_013 = Object.freeze({
  "usesDevice": SchemaPropertyUsesDevice,
  "usesHealthPlanIdStandard": SchemaPropertyUsesHealthPlanIdStandard,
  "utterances": SchemaPropertyUtterances,
  "validFor": SchemaPropertyValidFor,
  "validForMemberTier": SchemaPropertyValidForMemberTier,
  "validFrom": SchemaPropertyValidFrom,
  "validIn": SchemaPropertyValidIn,
  "validThrough": SchemaPropertyValidThrough,
  "value": SchemaPropertyValue,
  "valueAddedTaxIncluded": SchemaPropertyValueAddedTaxIncluded,
  "valueReference": SchemaPropertyValueReference,
  "variableMeasured": SchemaPropertyVariableMeasured,
  "variesBy": SchemaPropertyVariesBy,
  "vatID": SchemaPropertyVatID,
  "version": SchemaPropertyVersion,
  "video": SchemaPropertyVideo,
  "videoFormat": SchemaPropertyVideoFormat,
  "videoFrameSize": SchemaPropertyVideoFrameSize,
  "videoQuality": SchemaPropertyVideoQuality,
  "warning": SchemaPropertyWarning,
  "warranty": SchemaPropertyWarranty,
  "warrantyScope": SchemaPropertyWarrantyScope,
  "weight": SchemaPropertyWeight,
  "weightPercentage": SchemaPropertyWeightPercentage,
  "width": SchemaPropertyWidth,
  "wordCount": SchemaPropertyWordCount,
  "workExample": SchemaPropertyWorkExample,
  "workFeatured": SchemaPropertyWorkFeatured,
  "workLocation": SchemaPropertyWorkLocation,
  "workPerformed": SchemaPropertyWorkPerformed,
  "worksFor": SchemaPropertyWorksFor,
  "workTranslation": SchemaPropertyWorkTranslation,
  "worstRating": SchemaPropertyWorstRating,
  "xpath": SchemaPropertyXpath,
  "yield": SchemaPropertyYield,
});
