import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';

const testRoot = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(testRoot, '..', '..', '..', '..');
const distRoot = path.resolve(testRoot, '..', 'dist');
const distIndex = path.join(distRoot, 'index.js');
const smokeIndex = path.join(distRoot, 'index.smoke.mjs');
const structuredDataDist = path.join(repoRoot, 'packages', 'contracts', 'structured-data', 'dist', 'index.js').replace(/\\/g, '/');
const contractDist = path.join(repoRoot, 'packages', 'contracts', 'lander-content-contract', 'dist', 'index.js').replace(/\\/g, '/');

fs.writeFileSync(
  smokeIndex,
  fs.readFileSync(distIndex, 'utf8').replace('"@mdwrk/structured-data"', `"file:///${structuredDataDist}"`),
);

const {
  ActionStructuredData,
  AdministrativeAreaStructuredData,
  AboutPageStructuredData,
  AggregateOfferStructuredData,
  AggregateRatingStructuredData,
  AlignmentObjectStructuredData,
  AnswerStructuredData,
  ArticleStructuredData,
  AudienceStructuredData,
  AudioObjectStructuredData,
  ThingStructuredData,
  IntangibleStructuredData,
  StructuredValueStructuredData,
  TypeAndQuantityNodeStructuredData,
  UnitPriceSpecificationStructuredData,
  WarrantyPromiseStructuredData,
  BrandStructuredData,
  BroadcastChannelStructuredData,
  BroadcastFrequencySpecificationStructuredData,
  BroadcastServiceStructuredData,
  CableOrSatelliteServiceStructuredData,
  CategoryCodeSetStructuredData,
  CategoryCodeStructuredData,
  CivicStructureStructuredData,
  BlogPostingStructuredData,
  BookStructuredData,
  BroadcastEventStructuredData,
  BreadcrumbListStructuredData,
  CertificationStructuredData,
  ClassStructuredData,
  ClaimStructuredData,
  CommentStructuredData,
  ConstraintNodeStructuredData,
  ContactPointStructuredData,
  CorrectionCommentStructuredData,
  CheckoutPageStructuredData,
  ClaimReviewStructuredData,
  ClipStructuredData,
  CollectionPageStructuredData,
  ContactPageStructuredData,
  CourseInstanceStructuredData,
  CourseStructuredData,
  CountryStructuredData,
  CreativeWorkSeasonStructuredData,
  CreativeWorkSeriesStructuredData,
  CreativeWorkStructuredData,
  CredentialStructuredData,
  CreditCardStructuredData,
  CssSelectorTypeStructuredData,
  DataCatalogStructuredData,
  DataDownloadStructuredData,
  DataFeedItemStructuredData,
  DataFeedStructuredData,
  DatasetStructuredData,
  DefinedRegionStructuredData,
  DefinedTermSetStructuredData,
  DefinedTermStructuredData,
  DeliveryChargeSpecificationStructuredData,
  DemandStructuredData,
  DistanceStructuredData,
  DiscussionForumPostingStructuredData,
  DurationStructuredData,
  EducationalOccupationalCredentialStructuredData,
  EducationalOrganizationStructuredData,
  EnergyConsumptionDetailsStructuredData,
  EnergyStructuredData,
  EntryPointStructuredData,
  EnumerationStructuredData,
  EpisodeStructuredData,
  EmployerAggregateRatingStructuredData,
  EventStructuredData,
  FAQPageStructuredData,
  FinancialProductStructuredData,
  GeneStructuredData,
  GeoCoordinatesStructuredData,
  GeospatialGeometryStructuredData,
  GeoShapeStructuredData,
  GrantStructuredData,
  HyperTocEntryStructuredData,
  HealthInsurancePlanStructuredData,
  HealthPlanCostSharingSpecificationStructuredData,
  HealthPlanFormularyStructuredData,
  HealthPlanNetworkStructuredData,
  HowToStructuredData,
  HowToItemStructuredData,
  HowToSectionStructuredData,
  HowToStepStructuredData,
  HowToSupplyStructuredData,
  HowToToolStructuredData,
  ImageGalleryStructuredData,
  ImageObjectStructuredData,
  InteractionCounterStructuredData,
  IntegerStructuredData,
  QuantitativeValueStructuredData,
  QuantitativeValueDistributionStructuredData,
  MonetaryAmountStructuredData,
  RatingStructuredData,
  ItemPageStructuredData,
  ItemListStructuredData,
  JobPostingStructuredData,
  JsonLd,
  LanguageStructuredData,
  LifestyleModificationStructuredData,
  ListItemStructuredData,
  LoanOrCreditStructuredData,
  LearningResourceStructuredData,
  LocalBusinessStructuredData,
  LocationFeatureSpecificationStructuredData,
  MassStructuredData,
  MapStructuredData,
  MathSolverStructuredData,
  MediaGalleryStructuredData,
  MediaObjectStructuredData,
  MediaSubscriptionStructuredData,
  MenuItemStructuredData,
  MenuSectionStructuredData,
  MedicalAudienceStructuredData,
  MedicalCauseStructuredData,
  MedicalCodeStructuredData,
  MedicalConditionStructuredData,
  MedicalConditionStageStructuredData,
  MedicalContraindicationStructuredData,
  MedicalDeviceStructuredData,
  MedicalEntityStructuredData,
  MedicalGuidelineStructuredData,
  MedicalIntangibleStructuredData,
  MedicalProcedureStructuredData,
  MedicalRiskFactorStructuredData,
  MedicalSignStructuredData,
  MedicalSignOrSymptomStructuredData,
  MedicalStudyStructuredData,
  MedicalTestStructuredData,
  MedicalTherapyStructuredData,
  MedicalWebPageStructuredData,
  MemberProgramStructuredData,
  MaximumDoseScheduleStructuredData,
  MemberProgramTierStructuredData,
  MerchantReturnPolicyStructuredData,
  MerchantReturnPolicySeasonalOverrideStructuredData,
  MonetaryAmountDistributionStructuredData,
  MovieStructuredData,
  MusicAlbumStructuredData,
  MusicCompositionStructuredData,
  MusicGroupStructuredData,
  MusicPlaylistStructuredData,
  MusicRecordingStructuredData,
  MusicReleaseStructuredData,
  NewsArticleStructuredData,
  NutritionInformationStructuredData,
  OccupationStructuredData,
  OccupationalExperienceRequirementsStructuredData,
  OfferCatalogStructuredData,
  OfferStructuredData,
  OfferShippingDetailsStructuredData,
  OpeningHoursSpecificationStructuredData,
  OrganizationStructuredData,
  PropertyStructuredData,
  PropertyValueStructuredData,
  ProductGroupStructuredData,
  ProductModelStructuredData,
  ProductStructuredData,
  ProgramMembershipStructuredData,
  ProfilePageStructuredData,
  PublicationEventStructuredData,
  RepaymentSpecificationStructuredData,
  QAPageStructuredData,
  QuestionStructuredData,
  QuizStructuredData,
  ReadActionStructuredData,
  RealEstateListingStructuredData,
  RecipeStructuredData,
  ReviewStructuredData,
  ScheduleStructuredData,
  SearchResultsPageStructuredData,
  SeriesStructuredData,
  ServiceStructuredData,
  ServiceChannelStructuredData,
  ServicePeriodStructuredData,
  ShippingConditionsStructuredData,
  ShippingDeliveryTimeStructuredData,
  ShippingRateSettingsStructuredData,
  ShippingServiceStructuredData,
  SolveMathActionStructuredData,
  SoftwareApplicationStructuredData,
  RuntimePlatformStructuredData,
  OperatingSystemStructuredData,
  SoftwareSourceCodeStructuredData,
  StatisticalVariableStructuredData,
  SubstanceStructuredData,
  TaxonStructuredData,
  SuperficialAnatomyStructuredData,
  SpeakableSpecificationStructuredData,
  TechArticleStructuredData,
  TherapeuticProcedureStructuredData,
  TextObjectStructuredData,
  TripStructuredData,
  UrlStructuredData,
  VacationRentalStructuredData,
  VehicleStructuredData,
  VirtualLocationStructuredData,
  VideoGalleryStructuredData,
  VideoObjectStructuredData,
  WebApplicationStructuredData,
  WebContentStructuredData,
  WebPageStructuredData,
  WebPageElementStructuredData,
  WebSiteStructuredData,
  XPathTypeStructuredData,
  buildLanderJsonLdGraph,
  landerStructuredDataIntentRegistry,
  renderStructuredDataIntent,
} = await import(`file:///${smokeIndex.replace(/\\/g, '/')}`);
fs.rmSync(smokeIndex, { force: true });

const templatesDistRoot = path.join(repoRoot, 'packages', 'core', 'lander-page-templates', 'dist');
const templatesSmokeRoot = path.join(repoRoot, 'packages', 'core', 'lander-page-templates', '.smoke-dist');
fs.rmSync(templatesSmokeRoot, { recursive: true, force: true });
fs.cpSync(templatesDistRoot, templatesSmokeRoot, { recursive: true });
for (const file of fs.readdirSync(templatesSmokeRoot, { recursive: true })) {
  if (typeof file !== 'string' || !file.endsWith('.js')) continue;
  const target = path.join(templatesSmokeRoot, file);
  fs.writeFileSync(
    target,
    fs.readFileSync(target, 'utf8').replaceAll('"@mdwrk/lander-content-contract"', `"file:///${contractDist}"`),
  );
}

const presetsDistRoot = path.join(repoRoot, 'packages', 'core', 'lander-page-template-presets', 'dist');
const presetsSmokeRoot = path.join(repoRoot, 'packages', 'core', 'lander-page-template-presets', '.smoke-dist');
fs.rmSync(presetsSmokeRoot, { recursive: true, force: true });
fs.cpSync(presetsDistRoot, presetsSmokeRoot, { recursive: true });
const templateSmokeIndex = path.join(templatesSmokeRoot, 'index.js').replace(/\\/g, '/');
for (const file of fs.readdirSync(path.join(presetsSmokeRoot, 'presets'))) {
  if (!file.endsWith('.js')) continue;
  const target = path.join(presetsSmokeRoot, 'presets', file);
  fs.writeFileSync(
    target,
    fs.readFileSync(target, 'utf8').replaceAll('"@mdwrk/lander-page-templates"', `"file:///${templateSmokeIndex}"`),
  );
}
const { createEducationPathPreset } = await import(`file:///${path.join(presetsSmokeRoot, 'index.js').replace(/\\/g, '/')}`);
const { buildPageSpecsFromGraph } = await import(`file:///${templateSmokeIndex}`);

const site = {
  product: {
    name: 'MdWrk',
    slug: 'mdwrk',
    tagline: 'Local-first Markdown workspace',
    description: 'MdWrk is a local-first Markdown workspace with reusable lander packages.',
    category: 'ProductivityApplication',
    canonicalUrl: 'https://mdwrk.test',
    logo: { src: 'https://mdwrk.test/favicon.svg', alt: 'MdWrk logo' },
    sameAs: ['https://github.com/groupsum/mdwrk-pages'],
  },
  pages: [],
  pageByPath: new Map(),
  diagnostics: [],
  seo: {
    defaultImage: { src: 'https://mdwrk.test/og.png', alt: 'MdWrk preview image', width: 1200, height: 630 },
  },
};

const page = {
  kind: 'package',
  slug: '/packages/structured-data/',
  path: '/packages/structured-data/',
  title: 'Structured Data Package | MdWrk',
  description: 'The structured data package emits JSON-LD nodes for lander pages.',
  h1: 'Structured Data Package',
  intro: 'Use this page to validate every lander structured data rich-result family.',
  canonicalUrl: 'https://mdwrk.test/packages/structured-data/',
  breadcrumbs: [
    { label: 'MdWrk', href: '/' },
    { label: 'Packages', href: '/packages/' },
    { label: 'Structured Data Package', href: '/packages/structured-data/' },
  ],
  internalLinks: [],
  wordCount: 120,
  sections: [
    {
      id: 'install',
      kind: 'markdown',
      title: 'Install',
      body: 'Install and use the structured data package.',
    },
  ],
  faq: [{ question: 'Does the lander emit JSON-LD?', answer: 'Yes, visible FAQ content is mirrored into FAQPage JSON-LD.' }],
  seo: {
    keywords: ['structured-data', 'json-ld'],
    image: { src: 'https://mdwrk.test/package.png', alt: 'Structured data package screenshot' },
  },
  schema: [
    { kind: 'WebPage' },
    { kind: 'Organization' },
    { kind: 'WebSite' },
    { kind: 'SoftwareApplication' },
    { kind: 'WebApplication' },
    { kind: 'SoftwareSourceCode', data: { codeRepository: 'https://github.com/groupsum/mdwrk-pages' } },
    { kind: 'TechArticle' },
    { kind: 'Article' },
    { kind: 'NewsArticle', data: { datePublished: '2026-05-06' } },
    { kind: 'BlogPosting', data: { datePublished: '2026-05-06' } },
    { kind: 'FAQPage' },
    { kind: 'QAPage', data: { question: 'How does QAPage work?', acceptedAnswer: { text: 'It renders a single question page.' }, suggestedAnswer: [{ text: 'It is used for FAQs.' }], answerCount: 2 } },
    { kind: 'Quiz', data: { hasPart: [{ name: 'What is this?', acceptedAnswer: { text: 'A quiz.' }, suggestedAnswer: [{ text: 'A dataset.' }], answerCount: 2, eduQuestionType: 'Flashcard' }] } },
    { kind: 'Question', data: { name: 'Flashcard prompt', acceptedAnswer: { text: 'Flashcard answer' }, suggestedAnswer: [{ text: 'Wrong answer' }], answerCount: 2, eduQuestionType: 'Flashcard' } },
    { kind: 'Answer', data: { text: 'Standalone answer' } },
    { kind: 'BreadcrumbList' },
    { kind: 'Dataset', data: { keywords: ['structured-data', 'json-ld'] } },
    { kind: 'ImageObject' },
    { kind: 'ItemList' },
    { kind: 'HowTo' },
    { kind: 'Product' },
    { kind: 'ProfilePage' },
    { kind: 'LearningResource', data: { learningResourceType: 'Math Solver', teaches: ['Algebra'] } },
    { kind: 'SolveMathAction', data: { target: 'https://mdwrk.test/math?q={mathExpression}', mathExpressionInput: 'required name=mathExpression', eduQuestionType: ['Algebra'] } },
    { kind: 'MathSolver', data: { mathExpression: 'x+1=2' } },
    {
      kind: 'VideoObject',
      data: {
        thumbnailUrl: 'https://mdwrk.test/video.png',
        uploadDate: '2026-05-06',
        embedUrl: 'https://mdwrk.test/video',
        clip: [{ name: 'Key moment', url: 'https://mdwrk.test/video?t=10', startOffset: 10, endOffset: 20 }],
        publication: [{ name: 'Live stream', startDate: '2026-05-06T12:00:00Z', isLiveBroadcast: true }],
      },
    },
    { kind: 'Clip', data: { name: 'Key moment', url: 'https://mdwrk.test/video?t=10', startOffset: 10, endOffset: 20 } },
    { kind: 'BroadcastEvent', data: { name: 'Live stream', startDate: '2026-05-06T12:00:00Z', isLiveBroadcast: true } },
  ],
};

const graph = buildLanderJsonLdGraph(site, page);
const types = graph['@graph'].map((node) => node['@type']);

for (const type of [
  'WebPage',
  'Organization',
  'WebSite',
  'SoftwareApplication',
  'WebApplication',
  'SoftwareSourceCode',
  'TechArticle',
  'Article',
  'NewsArticle',
  'BlogPosting',
  'FAQPage',
  'QAPage',
  'Quiz',
  'Question',
  'Answer',
  'BreadcrumbList',
  'Dataset',
  'ImageObject',
  'ItemList',
  'HowTo',
  'Product',
  'ProfilePage',
  'LearningResource',
  'SolveMathAction',
  'MathSolver',
  'VideoObject',
  'Clip',
  'BroadcastEvent',
]) {
  assert.ok(types.includes(type), `missing ${type}`);
}

assert.equal(graph['@context'], 'https://schema.org');
assert.ok(graph['@id'].endsWith('#jsonld'));
assert.equal(graph['@graph'].find((node) => node['@type'] === 'FAQPage').mainEntity.length, 1);
assert.equal(graph['@graph'].find((node) => node['@type'] === 'BreadcrumbList').itemListElement.length, 3);

const typedCases = [
  ['Action', ActionStructuredData, { data: { name: 'Read docs', target: 'https://mdwrk.test/docs' } }],
  ['AdministrativeArea', AdministrativeAreaStructuredData, { data: { name: 'Illinois', containedInPlace: { '@type': 'Place', name: 'United States' } } }],
  ['AboutPage', AboutPageStructuredData, { data: { name: 'About Page', url: 'https://mdwrk.test/about', about: 'https://mdwrk.test/#org' } }],
  ['AggregateOffer', AggregateOfferStructuredData, { data: { name: 'Offer range', lowPrice: '10.00', highPrice: '30.00', offerCount: 3, offers: [{ '@type': 'Offer', price: '10.00', priceCurrency: 'USD' }] } }],
  ['Thing', ThingStructuredData, { data: { name: 'Thing', sameAs: ['https://mdwrk.test/thing'] } }],
  ['Intangible', IntangibleStructuredData, { data: { name: 'Intangible', description: 'Non-physical asset.' } }],
  ['StructuredValue', StructuredValueStructuredData, { data: { name: 'Structured value', description: 'Structured record.' } }],
  ['WebPage', WebPageStructuredData, { data: { name: 'Page', url: 'https://mdwrk.test/page', description: 'page' } }],
  ['CheckoutPage', CheckoutPageStructuredData, { data: { name: 'Checkout', url: 'https://mdwrk.test/checkout', offers: [{ '@type': 'Offer', price: '10.00', priceCurrency: 'USD' }] } }],
  ['CollectionPage', CollectionPageStructuredData, { data: { name: 'Collection', url: 'https://mdwrk.test/collection', hasPart: [{ '@type': 'Thing', name: 'Entry' }] } }],
  ['ContactPage', ContactPageStructuredData, { data: { name: 'Contact', url: 'https://mdwrk.test/contact', significantLinks: ['https://mdwrk.test/contact/email'] } }],
  ['WebSite', WebSiteStructuredData, { data: { name: 'Site', url: 'https://mdwrk.test', description: 'site' } }],
  ['Organization', OrganizationStructuredData, { data: { name: 'MdWrk', url: 'https://mdwrk.test' } }],
  ['SoftwareApplication', SoftwareApplicationStructuredData, { data: { name: 'MdWrk App', url: 'https://mdwrk.test/app' } }],
  ['WebApplication', WebApplicationStructuredData, { data: { name: 'MdWrk Web App', url: 'https://mdwrk.test/web-app' } }],
  ['AlignmentObject', AlignmentObjectStructuredData, { data: { name: 'Curriculum alignment', alignmentType: 'educationalSubject', targetName: 'Prompt operations' } }],
  ['Article', ArticleStructuredData, { data: { name: 'Article', url: 'https://mdwrk.test/article' } }],
  ['Audience', AudienceStructuredData, { data: { name: 'Operators', audienceType: 'Prompt operators', geographicArea: { '@type': 'AdministrativeArea', name: 'Illinois' } } }],
  ['AudioObject', AudioObjectStructuredData, { data: { name: 'Release call', contentUrl: 'https://mdwrk.test/audio.mp3', transcript: 'Release transcript.' } }],
  ['Brand', BrandStructuredData, { data: { name: 'Brand', slogan: 'Prompt systems that ship.', review: [{ '@type': 'Review', name: 'Trusted.' }] } }],
  ['BroadcastChannel', BroadcastChannelStructuredData, { data: { name: 'Primary channel', broadcastChannelId: 'CH-7', providesBroadcastService: { '@type': 'BroadcastService', name: 'Prompt Radio' } } }],
  ['BroadcastFrequencySpecification', BroadcastFrequencySpecificationStructuredData, { data: { name: 'HD terrestrial slot', broadcastFrequencyValue: 101.7, broadcastSignalModulation: 'QAM' } }],
  ['BroadcastService', BroadcastServiceStructuredData, { data: { name: 'Prompt Radio', broadcastDisplayName: 'Prompt Radio 101', areaServed: { '@type': 'AdministrativeArea', name: 'Illinois' }, hasBroadcastChannel: [{ '@type': 'BroadcastChannel', name: 'Primary channel' }] } }],
  ['CategoryCode', CategoryCodeStructuredData, { data: { name: 'PromptOps', termCode: 'PO-1', codeValue: 'prompt-ops' } }],
  ['CategoryCodeSet', CategoryCodeSetStructuredData, { data: { name: 'Ops glossary', hasCategoryCode: [{ '@type': 'CategoryCode', name: 'PromptOps' }] } }],
  ['CableOrSatelliteService', CableOrSatelliteServiceStructuredData, { data: { name: 'Prompt cable', areaServed: { '@type': 'AdministrativeArea', name: 'Midwest' }, provider: { '@type': 'Organization', name: 'MdWrk' } } }],
  ['NewsArticle', NewsArticleStructuredData, { data: { name: 'News Article', url: 'https://mdwrk.test/news-article' } }],
  ['TechArticle', TechArticleStructuredData, { data: { name: 'Tech Article', url: 'https://mdwrk.test/tech-article' } }],
  ['BlogPosting', BlogPostingStructuredData, { data: { name: 'Blog Posting', url: 'https://mdwrk.test/blog-posting' } }],
  ['BreadcrumbList', BreadcrumbListStructuredData, { data: { items: [{ label: 'Home', href: 'https://mdwrk.test/' }] } }],
  ['Certification', CertificationStructuredData, { data: { name: 'Certification', certificationIdentification: 'CERT-42', issuedBy: { '@type': 'Organization', name: 'MdWrk' } } }],
  ['CivicStructure', CivicStructureStructuredData, { data: { name: 'Prompt library', publicAccess: true, openingHours: ['Mo-Fr 09:00-17:00'] } }],
  ['Class', ClassStructuredData, { data: { name: 'PromptEntity', description: 'A top-level modeled class.' } }],
  ['Claim', ClaimStructuredData, { data: { name: 'Claim', text: 'Latency is below target.', appearance: [{ '@type': 'CreativeWork', name: 'Benchmark report' }] } }],
  ['ConstraintNode', ConstraintNodeStructuredData, { data: { name: 'Prompt shape', constraintProperty: 'deliveryStage', numConstraints: 3 } }],
  ['Comment', CommentStructuredData, { data: { name: 'Comment', text: 'Looks good.', author: { '@type': 'Person', name: 'MdWrk' } } }],
  ['ContactPoint', ContactPointStructuredData, { data: { name: 'Support', contactType: 'Support', email: 'support@mdwrk.test', availableLanguage: ['English'] } }],
  ['CorrectionComment', CorrectionCommentStructuredData, { data: { name: 'Correction', text: 'Previous metric was stale.', sharedContent: { '@type': 'CreativeWork', name: 'Release report' } } }],
  ['FAQPage', FAQPageStructuredData, { data: { items: [{ question: 'Q?', answer: 'A.' }] } }],
  ['QAPage', QAPageStructuredData, { data: { question: 'Q?', acceptedAnswer: { text: 'A.' }, suggestedAnswer: [{ text: 'B.' }], answerCount: 2, url: 'https://mdwrk.test/qa' } }],
  ['Quiz', QuizStructuredData, { data: { name: 'Quiz', hasPart: [{ name: 'Q?', acceptedAnswer: { text: 'A.' }, suggestedAnswer: [{ text: 'B.' }], answerCount: 2, eduQuestionType: 'Flashcard' }] } }],
  ['Question', QuestionStructuredData, { data: { name: 'Q?', acceptedAnswer: { text: 'A.' }, suggestedAnswer: [{ text: 'B.' }], answerCount: 2, eduQuestionType: 'Flashcard' } }],
  ['Answer', AnswerStructuredData, { data: { text: 'A.' } }],
  ['HowTo', HowToStructuredData, { data: { name: 'How To', url: 'https://mdwrk.test/how-to', steps: [{ name: 'Step 1', text: 'Do it.' }] } }],
  ['HowToItem', HowToItemStructuredData, { data: { name: 'Filter', requiredQuantity: '1' } }],
  ['HowToSection', HowToSectionStructuredData, { data: { name: 'Preparation', steps: 'Gather materials.' } }],
  ['HowToStep', HowToStepStructuredData, { data: { name: 'Mix', text: 'Mix the ingredients.', position: 1 } }],
  ['HowToSupply', HowToSupplyStructuredData, { data: { name: 'Paper', requiredQuantity: '2 sheets', estimatedCost: { '@type': 'MonetaryAmount', name: '$5' } } }],
  ['HowToTool', HowToToolStructuredData, { data: { name: 'Scissors', requiredQuantity: '1' } }],
  ['ItemPage', ItemPageStructuredData, { data: { name: 'Item Page', url: 'https://mdwrk.test/item', mainEntity: 'https://mdwrk.test/#item' } }],
  ['ItemList', ItemListStructuredData, { data: { name: 'Items', items: [{ name: 'Item 1', url: 'https://mdwrk.test/item-1' }] } }],
  ['Integer', IntegerStructuredData, { data: {} }],
  ['SoftwareSourceCode', SoftwareSourceCodeStructuredData, { data: { name: 'Source', url: 'https://mdwrk.test/source' } }],
  ['Product', ProductStructuredData, { data: { name: 'Product', url: 'https://mdwrk.test/product' } }],
  ['Dataset', DatasetStructuredData, { data: { name: 'Dataset', url: 'https://mdwrk.test/dataset' } }],
  ['Event', EventStructuredData, { data: { name: 'Launch', url: 'https://mdwrk.test/event', startDate: '2026-05-13' } }],
  ['VideoObject', VideoObjectStructuredData, { data: { name: 'Video', url: 'https://mdwrk.test/video', thumbnailUrl: 'https://mdwrk.test/video.png', uploadDate: '2026-05-13', clip: [{ name: 'Key moment', url: 'https://mdwrk.test/video?t=10', startOffset: 10, endOffset: 20 }], publication: [{ name: 'Live stream', startDate: '2026-05-13T10:00:00Z', isLiveBroadcast: true }] } }],
  ['ImageObject', ImageObjectStructuredData, { data: { name: 'Image', url: 'https://mdwrk.test/image.png' } }],
  ['Language', LanguageStructuredData, { data: { name: 'English', alternateName: 'en-US' } }],
  ['LifestyleModification', LifestyleModificationStructuredData, { data: { name: 'Lifestyle coaching', code: { '@type': 'MedicalCode', name: 'LM-1' } } }],
  ['QuantitativeValue', QuantitativeValueStructuredData, { data: { name: 'Latency', value: 120, unitText: 'ms' } }],
  ['LoanOrCredit', LoanOrCreditStructuredData, { data: { name: 'Equipment financing', amount: '25000', loanTerm: 'P24M', requiredCollateral: 'Laptop inventory' } }],
  ['QuantitativeValueDistribution', QuantitativeValueDistributionStructuredData, { data: { name: 'Latency band', median: 130, percentile10: 100, percentile90: 180 } }],
  ['MonetaryAmount', MonetaryAmountStructuredData, { data: { name: 'Budget', currency: 'USD', value: 5000 } }],
  ['Rating', RatingStructuredData, { data: { name: 'Operator score', ratingValue: 4.8, author: { '@type': 'Organization', name: 'MdWrk' } } }],
  ['ProfilePage', ProfilePageStructuredData, { data: { name: 'Profile', url: 'https://mdwrk.test/profile', mainEntity: 'https://mdwrk.test/#org' } }],
  ['Review', ReviewStructuredData, { data: { name: 'Review', url: 'https://mdwrk.test/review', itemReviewed: 'https://mdwrk.test/product', reviewBody: 'Solid.' } }],
  ['AggregateRating', AggregateRatingStructuredData, { data: { ratingValue: 5, reviewCount: 1 } }],
  ['Course', CourseStructuredData, { data: { name: 'Course', url: 'https://mdwrk.test/course' } }],
  ['CourseInstance', CourseInstanceStructuredData, { data: { name: 'Course Instance', url: 'https://mdwrk.test/course-instance' } }],
  ['Country', CountryStructuredData, { data: { name: 'United States', containedInPlace: { '@type': 'Place', name: 'North America' } } }],
  ['CreativeWork', CreativeWorkStructuredData, { data: { name: 'Creative Work', text: 'Visible body text.', author: { '@type': 'Person', name: 'MdWrk' } } }],
  ['CreativeWorkSeason', CreativeWorkSeasonStructuredData, { data: { name: 'Season One', seasonNumber: 1, numberOfEpisodes: 8, episode: [{ '@type': 'Episode', name: 'Episode 1' }] } }],
  ['CreativeWorkSeries', CreativeWorkSeriesStructuredData, { data: { name: 'Series', issn: '1234-5678', startDate: '2025-01-01' } }],
  ['Credential', CredentialStructuredData, { data: { name: 'Release badge', credentialCategory: 'badge', recognizedBy: { '@type': 'Organization', name: 'MdWrk' } } }],
  ['CreditCard', CreditCardStructuredData, { data: { name: 'Prompt rewards card', interestRate: 14.9, feesAndCommissionsSpecification: 'No annual fee.' } }],
  ['CssSelectorType', CssSelectorTypeStructuredData, { data: {} }],
  ['DataCatalog', DataCatalogStructuredData, { data: { name: 'Catalog', dataset: [{ '@type': 'Dataset', name: 'Release metrics' }], measurementMethod: 'survey' } }],
  ['DataDownload', DataDownloadStructuredData, { data: { name: 'Download', contentUrl: 'https://mdwrk.test/export.csv', encodingFormat: 'text/csv' } }],
  ['DataFeed', DataFeedStructuredData, { data: { name: 'Feed', dataFeedElement: [{ '@type': 'DataFeedItem', name: 'Release one' }], dateModified: '2026-05-27' } }],
  ['DataFeedItem', DataFeedItemStructuredData, { data: { name: 'Release one', item: { '@type': 'Thing', name: 'Prompt Studio' }, dateCreated: '2026-05-27' } }],
  ['DiscussionForumPosting', DiscussionForumPostingStructuredData, { data: { name: 'Forum Post', url: 'https://mdwrk.test/forum-post' } }],
  ['DefinedRegion', DefinedRegionStructuredData, { data: { name: 'US Midwest', addressCountry: 'US', postalCodePrefix: '60' } }],
  ['DefinedTerm', DefinedTermStructuredData, { data: { name: 'Prompt drift', termCode: 'PD-01', about: { '@type': 'Thing', name: 'Model behavior change' } } }],
  ['DefinedTermSet', DefinedTermSetStructuredData, { data: { name: 'Prompt glossary', hasDefinedTerm: [{ '@type': 'DefinedTerm', name: 'Prompt drift' }] } }],
  ['DeliveryChargeSpecification', DeliveryChargeSpecificationStructuredData, { data: { name: 'Domestic shipping', price: '15.00', priceCurrency: 'USD' } }],
  ['Demand', DemandStructuredData, { data: { name: 'Enterprise seats', itemOffered: { '@type': 'Product', name: 'Prompt Studio Enterprise' }, seller: { '@type': 'Organization', name: 'MdWrk' } } }],
  ['Distance', DistanceStructuredData, { data: {} }],
  ['Duration', DurationStructuredData, { data: {} }],
  ['EducationalOccupationalCredential', EducationalOccupationalCredentialStructuredData, { data: { name: 'Release badge', credentialCategory: 'badge', educationalLevel: 'Intermediate', competencyRequired: ['Prompt validation'] } }],
  ['EducationalOrganization', EducationalOrganizationStructuredData, { data: { name: 'MdWrk Academy', url: 'https://mdwrk.test/academy', address: 'Chicago, IL' } }],
  ['Energy', EnergyStructuredData, { data: {} }],
  ['EnergyConsumptionDetails', EnergyConsumptionDetailsStructuredData, { data: { name: 'Washer profile', description: 'Efficiency profile.' } }],
  ['EntryPoint', EntryPointStructuredData, { data: { name: 'Prompt API entry', urlTemplate: 'https://mdwrk.test/api/prompts/{id}', httpMethod: 'GET' } }],
  ['Enumeration', EnumerationStructuredData, { data: { name: 'PromptStates', description: 'Enumeration of prompt states.' } }],
  ['Episode', EpisodeStructuredData, { data: { name: 'Pilot', episodeNumber: 1, partOfSeries: { '@type': 'CreativeWorkSeries', name: 'Prompt Ops Series' } } }],
  ['FinancialProduct', FinancialProductStructuredData, { data: { name: 'Prompt Rewards', annualPercentageRate: 18.2, provider: { '@type': 'Organization', name: 'MdWrk Finance' } } }],
  ['Gene', GeneStructuredData, { data: { name: 'PROMPT1', hasBioPolymerSequence: 'ATCGATCG', associatedDisease: [{ '@type': 'MedicalCondition', name: 'Prompt fatigue' }] } }],
  ['GeoCoordinates', GeoCoordinatesStructuredData, { data: { latitude: 41.8781, longitude: -87.6298, addressCountry: 'US' } }],
  ['GeospatialGeometry', GeospatialGeometryStructuredData, { data: { name: 'Service boundary', geoContains: { '@type': 'Place', name: 'Chicago' }, geoWithin: { '@type': 'Place', name: 'Illinois' } } }],
  ['GeoShape', GeoShapeStructuredData, { data: { box: '41.8 -87.7 41.9 -87.6', addressCountry: 'US' } }],
  ['Grant', GrantStructuredData, { data: { name: 'Prompt research grant', fundedItem: [{ '@type': 'CreativeWork', name: 'Prompt research' }] } }],
  ['HyperTocEntry', HyperTocEntryStructuredData, { data: { name: 'Section A', text: 'Jump here.', position: 1, target: { '@type': 'Thing', name: 'Section A', url: 'https://mdwrk.test/guide#a' } } }],
  ['HealthInsurancePlan', HealthInsurancePlanStructuredData, { data: { name: 'PromptCare Gold', healthPlanId: 'HIOS-12345', contactPoint: { '@type': 'ContactPoint', name: 'Support' }, healthPlanDrugTier: 'Generic' } }],
  ['HealthPlanCostSharingSpecification', HealthPlanCostSharingSpecificationStructuredData, { data: { name: 'Primary care', healthPlanCoinsuranceRate: 0.2, healthPlanCopay: { '@type': 'PriceSpecification', price: '25.00', priceCurrency: 'USD' } } }],
  ['HealthPlanFormulary', HealthPlanFormularyStructuredData, { data: { name: 'Drug list', healthPlanDrugTier: 'Generic', offersPrescriptionByMail: true } }],
  ['HealthPlanNetwork', HealthPlanNetworkStructuredData, { data: { name: 'Preferred network', healthPlanNetworkId: 'NW-100', healthPlanNetworkTier: 'Tier 1' } }],
  ['ImageGallery', ImageGalleryStructuredData, { data: { name: 'Image gallery', hasPart: [{ '@type': 'ImageObject', name: 'Overview panel' }] } }],
  ['InteractionCounter', InteractionCounterStructuredData, { data: { name: 'Views', userInteractionCount: 42, interactionService: { '@type': 'WebSite', name: 'Docs' } } }],
  ['Book', BookStructuredData, { data: { name: 'Book', url: 'https://mdwrk.test/book' } }],
  ['ReadAction', ReadActionStructuredData, { target: 'https://mdwrk.test/book' }],
  ['RealEstateListing', RealEstateListingStructuredData, { data: { name: 'Listing', url: 'https://mdwrk.test/listing', offers: [{ '@type': 'Offer', price: '3000', priceCurrency: 'USD' }] } }],
  ['ClaimReview', ClaimReviewStructuredData, { data: { name: 'Claim Review', url: 'https://mdwrk.test/claim-review', claimReviewed: 'Claim text' } }],
  ['EmployerAggregateRating', EmployerAggregateRatingStructuredData, { data: { ratingValue: 4.9, reviewCount: 10 } }],
  ['MonetaryAmountDistribution', MonetaryAmountDistributionStructuredData, { data: { name: 'Salary', currency: 'USD', minValue: 10, maxValue: 20, unitText: 'HOUR' } }],
  ['JobPosting', JobPostingStructuredData, { data: { name: 'Engineer', title: 'Engineer', url: 'https://mdwrk.test/jobs/engineer', datePosted: '2026-05-13', hiringOrganization: 'https://mdwrk.test/#org' } }],
  ['ListItem', ListItemStructuredData, { data: { name: 'Step 1', item: { '@type': 'Thing', name: 'Prompt audit' }, position: 1 } }],
  ['LocalBusiness', LocalBusinessStructuredData, { data: { name: 'Local Biz', url: 'https://mdwrk.test/local' } }],
  ['LocationFeatureSpecification', LocationFeatureSpecificationStructuredData, { data: { name: 'Accessible entrance', propertyID: 'entrance_access', value: true, hoursAvailable: ['Mo-Fr 09:00-17:00'] } }],
  ['Mass', MassStructuredData, { data: {} }],
  ['Map', MapStructuredData, { data: { name: 'Campus map', text: 'Level one and level two.', mapType: 'Venue' } }],
  ['MedicalAudience', MedicalAudienceStructuredData, { data: { name: 'Adults with hypertension', audienceType: 'Adult patients' } }],
  ['MedicalCause', MedicalCauseStructuredData, { data: { name: 'Smoking' } }],
  ['MedicalCode', MedicalCodeStructuredData, { data: { name: 'ICD sample', codeValue: 'I10', codingSystem: 'ICD-10' } }],
  ['MedicalCondition', MedicalConditionStructuredData, { data: { name: 'Hypertension' } }],
  ['MedicalConditionStage', MedicalConditionStageStructuredData, { data: { name: 'Stage 1 hypertension' } }],
  ['MedicalContraindication', MedicalContraindicationStructuredData, { data: { name: 'Do not combine therapies' } }],
  ['MedicalDevice', MedicalDeviceStructuredData, { data: { name: 'Blood pressure cuff' } }],
  ['MedicalEntity', MedicalEntityStructuredData, { data: { name: 'Clinical guidance entity' } }],
  ['MedicalGuideline', MedicalGuidelineStructuredData, { data: { name: 'Hypertension guidance' } }],
  ['MedicalIntangible', MedicalIntangibleStructuredData, { data: { name: 'Clinical recommendation' } }],
  ['MedicalProcedure', MedicalProcedureStructuredData, { data: { name: 'Blood pressure monitoring' } }],
  ['MedicalRiskFactor', MedicalRiskFactorStructuredData, { data: { name: 'Smoking risk factor' } }],
  ['MedicalSign', MedicalSignStructuredData, { data: { name: 'Elevated blood pressure' } }],
  ['MedicalSignOrSymptom', MedicalSignOrSymptomStructuredData, { data: { name: 'Headache' } }],
  ['MedicalStudy', MedicalStudyStructuredData, { data: { name: 'Longitudinal hypertension study', status: 'Active' } }],
  ['MedicalTest', MedicalTestStructuredData, { data: { name: 'Blood pressure reading' } }],
  ['MedicalTherapy', MedicalTherapyStructuredData, { data: { name: 'Lifestyle counseling' } }],
  ['MedicalWebPage', MedicalWebPageStructuredData, { data: { name: 'Medical page', lastReviewed: '2026-05-31' } }],
  ['MemberProgram', MemberProgramStructuredData, { data: { name: 'Member Program', url: 'https://mdwrk.test/member-program' } }],
  ['MaximumDoseSchedule', MaximumDoseScheduleStructuredData, { data: { name: 'Maximum daily dose', doseUnit: 'mg', frequency: 'daily' } }],
  ['MediaGallery', MediaGalleryStructuredData, { data: { name: 'Media gallery', hasPart: [{ '@type': 'MediaObject', name: 'Walkthrough clip' }] } }],
  ['MediaObject', MediaObjectStructuredData, { data: { name: 'Release montage', contentUrl: 'https://mdwrk.test/media.mp4', encodingFormat: 'video/mp4' } }],
  ['MediaSubscription', MediaSubscriptionStructuredData, { data: { name: 'Pro streaming', authenticatingAuthority: { '@type': 'Organization', name: 'MDWRK ID' }, expectsAcceptanceOf: [{ '@type': 'Thing', name: 'Terms of service' }] } }],
  ['MenuItem', MenuItemStructuredData, { data: { name: 'Launch latte', offers: [{ '@type': 'Offer', name: 'Cup', price: '6.00', priceCurrency: 'USD' }], suitableForDiet: ['https://schema.org/VegetarianDiet'] } }],
  ['MenuSection', MenuSectionStructuredData, { data: { name: 'Release drinks', hasMenuItem: [{ '@type': 'MenuItem', name: 'Launch latte' }] } }],
  ['MemberProgramTier', MemberProgramTierStructuredData, { data: { name: 'Gold tier', membershipPointsRequired: 5000, hasTierBenefit: ['Priority support'] } }],
  ['MathSolver', MathSolverStructuredData, { data: { name: 'Math Solver', url: 'https://mdwrk.test/math-solver', potentialAction: { '@type': 'SolveMathAction', target: 'https://mdwrk.test/math?q={mathExpression}' }, learningResource: { '@type': 'LearningResource', name: 'Math Solver', learningResourceType: 'Math Solver' } } }],
  ['LearningResource', LearningResourceStructuredData, { data: { name: 'Learning Resource', url: 'https://mdwrk.test/learning-resource', learningResourceType: 'Math Solver', teaches: ['Algebra'] } }],
  ['SolveMathAction', SolveMathActionStructuredData, { data: { target: 'https://mdwrk.test/math?q={mathExpression}', mathExpressionInput: 'required name=mathExpression', eduQuestionType: ['Algebra'] } }],
  ['MerchantReturnPolicy', MerchantReturnPolicyStructuredData, { data: { name: 'Returns' } }],
  ['MerchantReturnPolicySeasonalOverride', MerchantReturnPolicySeasonalOverrideStructuredData, { data: { name: 'Holiday returns', merchantReturnDays: 60, startDate: '2026-11-15', endDate: '2027-01-15' } }],
  ['OfferShippingDetails', OfferShippingDetailsStructuredData, { data: { name: 'Shipping' } }],
  ['Movie', MovieStructuredData, { data: { name: 'Movie', url: 'https://mdwrk.test/movie' } }],
  ['MusicAlbum', MusicAlbumStructuredData, { data: { name: 'Release Waves', byArtist: [{ '@type': 'MusicGroup', name: 'MDWRK Ensemble' }], track: [{ '@type': 'MusicRecording', name: 'Deploy Overture' }], numTracks: 1 } }],
  ['MusicComposition', MusicCompositionStructuredData, { data: { name: 'Deploy Overture', composer: [{ '@type': 'Person', name: 'Casey Prompt' }], lyricist: [{ '@type': 'Person', name: 'Jordan Schema' }] } }],
  ['MusicGroup', MusicGroupStructuredData, { data: { name: 'MDWRK Ensemble', album: [{ '@type': 'MusicAlbum', name: 'Release Waves' }], track: [{ '@type': 'MusicRecording', name: 'Deploy Overture' }] } }],
  ['MusicPlaylist', MusicPlaylistStructuredData, { data: { name: 'Launch queue', track: [{ '@type': 'MusicRecording', name: 'Deploy Overture' }], numTracks: 1 } }],
  ['MusicRecording', MusicRecordingStructuredData, { data: { name: 'Deploy Overture', byArtist: [{ '@type': 'MusicGroup', name: 'MDWRK Ensemble' }], inAlbum: [{ '@type': 'MusicAlbum', name: 'Release Waves' }], duration: 'PT3M' } }],
  ['MusicRelease', MusicReleaseStructuredData, { data: { name: 'Release Waves v1', catalogNumber: 'REL-001', musicReleaseFormat: 'Digital', recordLabel: { '@type': 'Organization', name: 'MDWRK Audio' } } }],
  ['NutritionInformation', NutritionInformationStructuredData, { data: { name: 'Nutrition facts', servingSize: '1 bar', calories: '200 kcal', proteinContent: '10 g' } }],
  ['Occupation', OccupationStructuredData, { data: { name: 'Prompt operations engineer', educationRequirements: 'BS or equivalent', skills: ['Prompt evaluation'] } }],
  ['OccupationalExperienceRequirements', OccupationalExperienceRequirementsStructuredData, { data: { name: 'Prompt operations track record', monthsOfExperience: 24, occupationalExperienceProperties: { '@type': 'PropertyValue', name: 'Incidents handled', value: 12 } } }],
  ['Offer', OfferStructuredData, { data: { name: 'Starter offer', price: '10.00', priceCurrency: 'USD', seller: { '@type': 'Organization', name: 'MdWrk' } } }],
  ['OfferCatalog', OfferCatalogStructuredData, { data: { name: 'Offer catalog', numberOfItems: 2, itemListElement: [{ '@type': 'Offer', name: 'Starter' }] } }],
  ['OpeningHoursSpecification', OpeningHoursSpecificationStructuredData, { data: { name: 'Weekday hours', opens: '09:00', closes: '17:00', dayOfWeek: ['Monday', 'Tuesday'] } }],
  ['Property', PropertyStructuredData, { data: { name: 'deploymentStage', domainIncludes: [{ '@type': 'Class', name: 'PromptEntity' }], rangeIncludes: [{ '@type': 'Class', name: 'PromptStage' }] } }],
  ['PropertyValue', PropertyValueStructuredData, { data: { name: 'Latency', value: 120, unitText: 'ms' } }],
  ['TextObject', TextObjectStructuredData, { data: { name: 'Launch transcript', text: 'Transcript body', encodingFormat: 'text/plain' } }],
  ['Trip', TripStructuredData, { data: { name: 'Operator summit trip', departureTime: '2026-06-10T09:00:00Z', arrivalTime: '2026-06-10T12:00:00Z', tripOrigin: { '@type': 'Place', name: 'Chicago' }, itinerary: [{ '@type': 'Place', name: 'Austin' }], provider: { '@type': 'Organization', name: 'MdWrk' } } }],
  ['TypeAndQuantityNode', TypeAndQuantityNodeStructuredData, { data: { name: 'Bundle quantity', amountOfThisGood: 2, typeOfGood: { '@type': 'Product', name: 'Prompt Device' }, unitCode: 'C62' } }],
  ['UnitPriceSpecification', UnitPriceSpecificationStructuredData, { data: { name: 'Seat price', price: '29.00', priceCurrency: 'USD', unitCode: 'MON', referenceQuantity: { '@type': 'QuantitativeValue', value: 1 } } }],
  ['Clip', ClipStructuredData, { data: { name: 'Clip', url: 'https://mdwrk.test/video?t=10', startOffset: 10, endOffset: 20 } }],
  ['BroadcastEvent', BroadcastEventStructuredData, { data: { name: 'Broadcast', startDate: '2026-05-13T10:00:00Z', isLiveBroadcast: true } }],
  ['ProductGroup', ProductGroupStructuredData, { data: { name: 'Product Group', url: 'https://mdwrk.test/product-group' } }],
  ['ProductModel', ProductModelStructuredData, { data: { name: 'Prompt Device 2', brand: { '@type': 'Brand', name: 'MDWRK' }, model: 'PD-2', isVariantOf: { '@type': 'ProductGroup', name: 'Prompt Device Family' } } }],
  ['ProgramMembership', ProgramMembershipStructuredData, { data: { name: 'Partner program', hostingOrganization: { '@type': 'Organization', name: 'MdWrk' }, membershipNumber: 'PM-42', programName: 'Partners' } }],
  ['Recipe', RecipeStructuredData, { data: { name: 'Recipe', url: 'https://mdwrk.test/recipe', recipeIngredient: ['salt'], recipeInstructions: 'Mix.' } }],
  ['PublicationEvent', PublicationEventStructuredData, { data: { name: 'Launch publication', publishedBy: { '@type': 'Organization', name: 'MdWrk' }, startDate: '2026-05-27T10:00:00Z' } }],
  ['RepaymentSpecification', RepaymentSpecificationStructuredData, { data: { name: 'Standard repayment', numberOfLoanPayments: 12, loanPaymentFrequency: 1 } }],
  ['SpeakableSpecification', SpeakableSpecificationStructuredData, { data: { cssSelector: ['.answer'] } }],
  ['Schedule', ScheduleStructuredData, { data: { name: 'Release calendar', repeatFrequency: 'P1W', byDay: ['Monday'], startDate: '2026-05-27', endDate: '2026-06-27' } }],
  ['SearchResultsPage', SearchResultsPageStructuredData, { data: { name: 'Search', url: 'https://mdwrk.test/search', significantLinks: ['https://mdwrk.test/search/result-1'] } }],
  ['Series', SeriesStructuredData, { data: { name: 'Operations series', startDate: '2026-01-01', endDate: '2026-12-31' } }],
  ['Service', ServiceStructuredData, { data: { name: 'Prompt advisory', serviceType: 'Consulting', areaServed: { '@type': 'AdministrativeArea', name: 'Illinois' }, provider: { '@type': 'Organization', name: 'MdWrk' } } }],
  ['ServiceChannel', ServiceChannelStructuredData, { data: { name: 'Web support', processingTime: 'P1D', serviceUrl: 'https://mdwrk.test/support' } }],
  ['ServicePeriod', ServicePeriodStructuredData, { data: { name: 'Handling window', cutoffTime: '17:00:00-05:00', startDate: '2026-05-27', endDate: '2026-06-27' } }],
  ['ShippingConditions', ShippingConditionsStructuredData, { data: { name: 'Domestic parcel conditions', shippingDestination: { '@type': 'DefinedRegion', name: 'US' }, shippingOrigin: { '@type': 'Place', name: 'Chicago' } } }],
  ['ShippingDeliveryTime', ShippingDeliveryTimeStructuredData, { data: { name: 'Ground delivery', cutoffTime: '17:00:00-05:00' } }],
  ['ShippingRateSettings', ShippingRateSettingsStructuredData, { data: { name: 'US shipping rates', shippingDestination: { '@type': 'DefinedRegion', name: 'US' } } }],
  ['ShippingService', ShippingServiceStructuredData, { data: { name: 'Ground shipping', shippingConditions: { '@type': 'Thing', name: 'Standard conditions' } } }],
  ['StatisticalVariable', StatisticalVariableStructuredData, { data: { name: 'Incident volume', measurementMethod: 'count', measurementTechnique: 'manual review', populationType: { '@type': 'Class', name: 'OperatorCohort' } } }],
  ['Substance', SubstanceStructuredData, { data: { name: 'Caffeine', activeIngredient: 'Caffeine' } }],
  ['Taxon', TaxonStructuredData, { data: { name: 'Promptidae', parentTaxon: { '@type': 'Taxon', name: 'Automation' }, taxonRank: 'family' } }],
  ['SuperficialAnatomy', SuperficialAnatomyStructuredData, { data: { name: 'Upper arm', associatedPathophysiology: 'Localized inflammation.' } }],
  ['RuntimePlatform', RuntimePlatformStructuredData, { data: { name: 'Node.js runtime', applicationCategory: 'DeveloperApplication', operatingSystem: 'Cross-platform' } }],
  ['OperatingSystem', OperatingSystemStructuredData, { data: { name: 'PromptOS', applicationCategory: 'SystemApplication', softwareVersion: '1.0.0' } }],
  ['URL', UrlStructuredData, { data: {} }],
  ['TherapeuticProcedure', TherapeuticProcedureStructuredData, { data: { name: 'Guided breathing exercise' } }],
  ['WarrantyPromise', WarrantyPromiseStructuredData, { data: { name: 'Limited warranty', durationOfWarranty: { '@type': 'QuantitativeValue', value: 12, unitCode: 'MON' } } }],
  ['XPathType', XPathTypeStructuredData, { data: {} }],
  ['VacationRental', VacationRentalStructuredData, { data: { name: 'Rental', url: 'https://mdwrk.test/rental' } }],
  ['Vehicle', VehicleStructuredData, { data: { name: 'Vehicle', url: 'https://mdwrk.test/vehicle' } }],
  ['VirtualLocation', VirtualLocationStructuredData, { data: { name: 'Virtual office', url: 'https://mdwrk.test/meet' } }],
  ['VideoGallery', VideoGalleryStructuredData, { data: { name: 'Video Gallery', url: 'https://mdwrk.test/gallery', video: [{ '@type': 'VideoObject', name: 'Demo' }] } }],
  ['WebContent', WebContentStructuredData, { data: { name: 'Knowledge base article', text: 'Visible body text.', author: { '@type': 'Person', name: 'MdWrk' } } }],
  ['WebPageElement', WebPageElementStructuredData, { data: { name: 'Hero banner', text: 'Top of page banner.', cssSelector: ['.hero-banner'], xpath: ["//*[@id='hero-banner']"] } }],
];

for (const [type, Component, props] of typedCases) {
  const markup = renderToStaticMarkup(React.createElement(Component, props));
  assert.ok(markup.includes('"@type":"'), `missing script payload for ${type}`);
  assert.ok(markup.includes(`"${type}"`), `missing ${type} payload`);
}

const jsonLdMarkup = renderToStaticMarkup(React.createElement(JsonLd, { graph }));
assert.ok(jsonLdMarkup.includes('application/ld+json'));
assert.ok(jsonLdMarkup.includes('"@context":"https://schema.org"'));

assert.ok(Object.keys(landerStructuredDataIntentRegistry).length > 207);
assert.equal(landerStructuredDataIntentRegistry.WebPage.componentName, 'WebPageStructuredData');
const intentMarkup = renderToStaticMarkup(renderStructuredDataIntent({
  id: 'intent:webpage',
  kind: 'WebPage',
  pagePath: '/packages/structured-data/',
  source: 'schema',
  data: { name: 'Intent Page', url: 'https://mdwrk.test/intent-page' },
}));
assert.ok(intentMarkup.includes('"WebPage"'));

const educationPreset = createEducationPathPreset({ baseSlug: '/academy' });
const educationPages = buildPageSpecsFromGraph(educationPreset.graph).pages;
const pageBySlug = Object.fromEntries(educationPages.map((entry) => [entry.slug, entry]));

function compiledEducationPage(pageSpec) {
  return {
    ...pageSpec,
    path: pageSpec.slug,
    canonicalUrl: `https://mdwrk.test${pageSpec.slug}`,
    breadcrumbs: [
      { label: 'MdWrk', href: '/' },
      { label: pageSpec.title, href: pageSpec.slug },
    ],
    internalLinks: [],
    wordCount: 120,
    seo: {},
  };
}

for (const [slug, expectedType] of [
  ['/academy/learn/', 'ItemList'],
  ['/academy/learn/course/', 'Course'],
  ['/academy/learn/course/module/', 'TechArticle'],
  ['/academy/learn/course/quiz/', 'Quiz'],
  ['/academy/learn/course/test/', 'Quiz'],
]) {
  const educationGraphForPage = buildLanderJsonLdGraph(site, compiledEducationPage(pageBySlug[slug]));
  assert.ok(educationGraphForPage['@graph'].some((node) => node['@type'] === expectedType), `missing ${expectedType} for ${slug}`);
}

fs.rmSync(presetsSmokeRoot, { recursive: true, force: true });
fs.rmSync(templatesSmokeRoot, { recursive: true, force: true });
