export * from "./version.js";
export * from "./generated-semantic-tokens.js";

export const MDWRK_PAGES_UI_ROOT_TOKEN_NAMES = [
  "mdwrk-font-ui",
  "mdwrk-font-head",
  "mdwrk-font-mono",
  "mdwrk-radius-sm",
  "mdwrk-radius-md",
  "mdwrk-radius-lg",
  "mdwrk-space-2",
  "mdwrk-space-3",
  "mdwrk-space-4",
  "mdwrk-space-6",
  "mdwrk-shadow-soft",
  "mdwrk-shadow-strong",
] as const;

export type MdwrkPagesUiRootTokenName = typeof MDWRK_PAGES_UI_ROOT_TOKEN_NAMES[number];

export const MDWRK_PAGES_UI_PRIMITIVE_TOKEN_STYLES = [
  "./styles/primitive-actions.css",
  "./styles/primitive-content.css",
  "./styles/primitive-feedback.css",
  "./styles/primitive-forms.css",
  "./styles/primitive-layout.css",
  "./styles/primitive-media.css",
  "./styles/primitive-navigation.css",
  "./styles/primitive-overlays.css",
] as const;

export type MdwrkPagesUiPrimitiveTokenStyle = typeof MDWRK_PAGES_UI_PRIMITIVE_TOKEN_STYLES[number];

export const MDWRK_PAGES_UI_PRIMITIVE_TOKEN_NAMES = [
  "mdwrk-primitive-action-bg",
  "mdwrk-primitive-action-fg",
  "mdwrk-primitive-action-border",
  "mdwrk-primitive-action-primary-bg",
  "mdwrk-primitive-action-primary-fg",
  "mdwrk-primitive-action-focus",
  "mdwrk-primitive-action-radius",
  "mdwrk-primitive-action-padding",
  "mdwrk-primitive-action-gap",
  "mdwrk-primitive-action-disabled-opacity",
  "mdwrk-primitive-content-bg",
  "mdwrk-primitive-content-strong-bg",
  "mdwrk-primitive-content-code-bg",
  "mdwrk-primitive-content-fg",
  "mdwrk-primitive-content-muted",
  "mdwrk-primitive-content-border",
  "mdwrk-primitive-content-radius",
  "mdwrk-primitive-content-padding",
  "mdwrk-primitive-content-gap",
  "mdwrk-primitive-feedback-bg",
  "mdwrk-primitive-feedback-fg",
  "mdwrk-primitive-feedback-border",
  "mdwrk-primitive-feedback-accent",
  "mdwrk-primitive-feedback-focus",
  "mdwrk-primitive-feedback-radius",
  "mdwrk-primitive-feedback-padding",
  "mdwrk-primitive-feedback-gap",
  "mdwrk-primitive-form-bg",
  "mdwrk-primitive-form-fg",
  "mdwrk-primitive-form-muted",
  "mdwrk-primitive-form-border",
  "mdwrk-primitive-form-focus",
  "mdwrk-primitive-form-radius",
  "mdwrk-primitive-form-padding",
  "mdwrk-primitive-form-gap",
  "mdwrk-primitive-form-disabled-opacity",
  "mdwrk-primitive-layout-gap",
  "mdwrk-primitive-layout-surface",
  "mdwrk-primitive-layout-border",
  "mdwrk-primitive-layout-radius",
  "mdwrk-primitive-layout-padding",
  "mdwrk-primitive-media-bg",
  "mdwrk-primitive-media-fg",
  "mdwrk-primitive-media-border",
  "mdwrk-primitive-media-radius",
  "mdwrk-primitive-media-padding",
  "mdwrk-primitive-media-gap",
  "mdwrk-primitive-nav-bg",
  "mdwrk-primitive-nav-fg",
  "mdwrk-primitive-nav-border",
  "mdwrk-primitive-nav-active-bg",
  "mdwrk-primitive-nav-active-fg",
  "mdwrk-primitive-nav-focus",
  "mdwrk-primitive-nav-radius",
  "mdwrk-primitive-nav-padding",
  "mdwrk-primitive-nav-gap",
  "mdwrk-primitive-overlay-bg",
  "mdwrk-primitive-overlay-fg",
  "mdwrk-primitive-overlay-border",
  "mdwrk-primitive-overlay-radius",
  "mdwrk-primitive-overlay-padding",
  "mdwrk-primitive-overlay-gap",
  "mdwrk-primitive-overlay-shadow",
] as const;

export type MdwrkPagesUiPrimitiveTokenName = typeof MDWRK_PAGES_UI_PRIMITIVE_TOKEN_NAMES[number];
