import React from "react";

const familyByName = {
  AboutPage: "Page family",
  AggregateRating: "Commerce family",
  Answer: "Education family",
  Article: "Article family",
  BlogPosting: "Article family",
  Book: "Catalog family",
  BroadcastEvent: "Media family",
  BreadcrumbList: "Identity family",
  CheckoutPage: "Page family",
  ClaimReview: "Article family",
  Clip: "Media family",
  CollectionPage: "Page family",
  ContactPage: "Page family",
  Course: "Education family",
  CourseInstance: "Education family",
  Dataset: "Catalog family",
  DiscussionForumPosting: "Article family",
  EmployerAggregateRating: "Commerce family",
  Event: "Catalog family",
  FAQPage: "Education family",
  HowTo: "Education family",
  ImageObject: "Media family",
  ItemList: "Catalog family",
  ItemPage: "Page family",
  JobPosting: "Catalog family",
  LearningResource: "Education family",
  LocalBusiness: "Identity family",
  MathSolver: "Education family",
  MemberProgram: "Identity family",
  MerchantReturnPolicy: "Commerce family",
  MonetaryAmountDistribution: "Commerce family",
  Movie: "Media family",
  NewsArticle: "Article family",
  OfferShippingDetails: "Commerce family",
  Organization: "Identity family",
  Product: "Commerce family",
  ProductGroup: "Commerce family",
  ProfilePage: "Identity family",
  QAPage: "Education family",
  Question: "Education family",
  Quiz: "Education family",
  ReadAction: "Catalog family",
  RealEstateListing: "Page family",
  Recipe: "Catalog family",
  Review: "Commerce family",
  SearchResultsPage: "Page family",
  SolveMathAction: "Education family",
  SoftwareApplication: "Catalog family",
  SoftwareSourceCode: "Catalog family",
  SpeakableSpecification: "Identity family",
  TechArticle: "Article family",
  VacationRental: "Catalog family",
  Vehicle: "Catalog family",
  VideoGallery: "Page family",
  VideoObject: "Media family",
  WebApplication: "Catalog family",
  WebPage: "Identity family",
  WebSite: "Identity family",
};

export const showcaseFamilyDescriptions = {
  "Article family": "Editorial, publishing, discussion, and fact-check surfaces.",
  "Education family": "Courses, Q&A, quizzes, learning assets, and how-to flows.",
  "Commerce family": "Product, review, shipping, pricing, and return-policy semantics.",
  "Media family": "Video, clips, broadcasts, images, and movie-style media shells.",
  "Identity family": "Profiles, organizations, local entities, breadcrumbs, and site identity.",
  "Catalog family": "Datasets, recipes, software, rentals, vehicles, job posts, and action surfaces.",
  "Page family": "Specialized web-page variants for about, contact, listings, search, and galleries.",
};

export const showcaseFamilyOrder = [
  "Article family",
  "Education family",
  "Commerce family",
  "Media family",
  "Identity family",
  "Catalog family",
  "Page family",
];

export const showcaseEntries = [
  { name: "AboutPage", description: "About-page variant with entity framing.", props: { name: "About MDWRK", description: "Company overview.", about: "Prompt delivery systems", mainEntity: "https://mdwrk.test/#org" }, visible: ["About MDWRK", "Prompt delivery systems"] },
  { name: "AggregateRating", description: "Aggregate rating summary block.", props: { ratingValue: 4.8, reviewCount: 12, ratingCount: 14, body: "Ratings body" }, visible: ["Rating value: 4.8", "12"] },
  { name: "Answer", description: "Answer block with lightweight attribution.", props: { text: "Prompt drift is behavior change over time.", author: { name: "MDWRK" }, upvoteCount: 3 }, visible: ["Prompt drift is behavior change over time.", "MDWRK"] },
  { name: "Article", description: "Primary editorial story shell.", props: { title: "Prompt Delivery Studio", description: "Ship prompt systems.", body: React.createElement("p", null, "Article body") }, visible: ["Prompt Delivery Studio", "Ship prompt systems."] },
  { name: "BlogPosting", description: "Blog variant with the article visual pattern.", props: { title: "Prompt Notebook", description: "Blog description.", body: React.createElement("p", null, "Blog body") }, visible: ["Prompt Notebook", "Blog description."] },
  { name: "Book", description: "Book catalog entity.", props: { name: "Prompt Reliability", author: { name: "MDWRK" }, isbn: "978-1-23456-789-0" }, visible: ["Prompt Reliability", "MDWRK"] },
  { name: "BroadcastEvent", description: "Live broadcast event surface.", props: { name: "Prompt Ops Live", startDate: "2026-06-01", isLiveBroadcast: true }, visible: ["Prompt Ops Live", "2026-06-01"] },
  { name: "BreadcrumbList", description: "Breadcrumb navigation surface.", props: { items: [{ label: "Home", href: "/" }, { label: "Docs", href: "/docs/" }, { label: "API" }] }, visible: ["Home", "Docs", "API"] },
  { name: "CheckoutPage", description: "Checkout-focused page shell.", props: { name: "Checkout", description: "Finish your purchase.", about: "Secure payment flow", offers: [{ name: "Prompt Studio Pro", price: "USD 49", href: "https://mdwrk.test/buy" }] }, visible: ["Checkout", "Prompt Studio Pro"] },
  { name: "ClaimReview", description: "Fact-check style editorial surface.", props: { title: "Fact Check: Prompt Drift", claimReviewed: "Prompt drift is impossible.", description: "Claim review description." }, visible: ["Fact Check: Prompt Drift", "Prompt drift is impossible."] },
  { name: "Clip", description: "Time-bounded video clip summary.", props: { name: "Latency section", startOffset: 10, endOffset: 30 }, visible: ["Latency section", "10"] },
  { name: "CollectionPage", description: "Collection page with curated entries.", props: { name: "Prompt patterns", description: "Curated pattern collection.", items: [{ name: "Release checklists", summary: "Operational references." }] }, visible: ["Prompt patterns", "Release checklists"] },
  { name: "ContactPage", description: "Contact page with direct channels.", props: { name: "Contact MDWRK", description: "Reach the team.", contactPoints: [{ label: "Email", value: "hello@mdwrk.test", href: "mailto:hello@mdwrk.test" }] }, visible: ["Contact MDWRK", "hello@mdwrk.test"] },
  { name: "Course", description: "Course overview with modules.", props: { name: "Prompt Delivery 101", description: "Ship prompts.", provider: { name: "MDWRK" }, modules: [{ title: "Module A", summary: "Foundations." }] }, visible: ["Prompt Delivery 101", "Module A"] },
  { name: "CourseInstance", description: "Scheduled offering of a course.", props: { name: "Prompt Delivery 101 - July", courseMode: "Remote", startDate: "2026-07-01" }, visible: ["Prompt Delivery 101 - July", "Remote"] },
  { name: "Dataset", description: "Dataset entity shell.", props: { name: "Prompt Eval Benchmarks", creator: "MDWRK", keywords: ["prompt", "eval"] }, visible: ["Prompt Eval Benchmarks", "MDWRK"] },
  { name: "DiscussionForumPosting", description: "Discussion post shell with article-body semantics.", props: { title: "How should we measure drift?", articleBody: "Use baseline checks." }, visible: ["How should we measure drift?", "Use baseline checks."] },
  { name: "EmployerAggregateRating", description: "Employer reputation summary.", props: { ratingValue: 4.4, reviewCount: 7, employerName: "MDWRK" }, visible: ["MDWRK", "4.4"] },
  { name: "Event", description: "General event shell.", props: { name: "Prompt Summit", startDate: "2026-08-01", location: "Chicago" }, visible: ["Prompt Summit", "Chicago"] },
  { name: "FAQPage", description: "FAQ landing surface.", props: { items: [{ question: "What is prompt drift?", answer: "Behavior change over time." }] }, visible: ["Frequently Asked Questions", "What is prompt drift?"] },
  { name: "HowTo", description: "Step-by-step procedural guide.", props: { name: "Ship a prompt release", steps: [{ name: "Baseline", text: "Capture current behavior." }] }, visible: ["Ship a prompt release", "Baseline"] },
  { name: "ImageObject", description: "Image asset shell.", props: { name: "Prompt dashboard", contentUrl: "https://mdwrk.test/image.png", width: 1200, height: 630 }, visible: ["Prompt dashboard", "1200"] },
  { name: "ItemPage", description: "Single-entity page shell.", props: { name: "Prompt Studio package", description: "Package detail page.", mainEntity: "pkg:@mdwrk/lander-react" }, visible: ["Prompt Studio package", "pkg:@mdwrk/lander-react"] },
  { name: "ItemList", description: "Curated item list surface.", props: { name: "Prompt links", items: [{ name: "Docs", url: "/docs/" }, { name: "Pricing" }] }, visible: ["Prompt links", "Docs"] },
  { name: "JobPosting", description: "Job listing shell.", props: { name: "AI Reliability Team", title: "Prompt Operations Engineer", datePosted: "2026-05-27", hiringOrganization: "MDWRK" }, visible: ["Prompt Operations Engineer", "MDWRK"] },
  { name: "LearningResource", description: "General learning asset shell.", props: { name: "Prompt release guide", learningResourceType: "Guide", teaches: ["Prompt validation"] }, visible: ["Prompt release guide", "Guide"] },
  { name: "LocalBusiness", description: "Local business entity surface.", props: { name: "MDWRK Chicago", address: "Chicago, IL", telephone: "+1-312-555-0100" }, visible: ["MDWRK Chicago", "Chicago, IL"] },
  { name: "MathSolver", description: "Math assistance surface.", props: { name: "Algebra helper", mathExpression: "2x+4=10" }, visible: ["Algebra helper", "2x+4=10"] },
  { name: "MemberProgram", description: "Membership program summary.", props: { name: "Prompt Pro", provider: "MDWRK" }, visible: ["Prompt Pro", "MDWRK"] },
  { name: "MerchantReturnPolicy", description: "Return-policy terms surface.", props: { name: "Return policy", merchantReturnDays: 30, returnPolicyCategory: "https://schema.org/MerchantReturnFiniteReturnWindow" }, visible: ["Return policy", "30"] },
  { name: "MonetaryAmountDistribution", description: "Compensation or price-range distribution.", props: { name: "Salary band", currency: "USD", median: 120000 }, visible: ["Salary band", "USD"] },
  { name: "Movie", description: "Movie-style media entity.", props: { name: "Prompt City", director: { name: "MDWRK" } }, visible: ["Prompt City", "MDWRK"] },
  { name: "NewsArticle", description: "News-focused article wrapper.", props: { title: "Prompt Ops Breaking News", description: "Latest release notes.", body: React.createElement("p", null, "News body") }, visible: ["Prompt Ops Breaking News", "Latest release notes."] },
  { name: "OfferShippingDetails", description: "Shipping details summary.", props: { name: "Shipping details", shippingDestination: "US", shippingRate: "Free" }, visible: ["Shipping details", "US"] },
  { name: "Organization", description: "Organization identity shell.", props: { name: "MDWRK", sameAs: ["https://github.com/groupsum/mdwrk-pages"] }, visible: ["MDWRK", "https://github.com/groupsum/mdwrk-pages"] },
  { name: "Product", description: "Primary product offer shell.", props: { name: "Prompt Delivery Studio", description: "Operational prompt delivery.", price: 49, priceCurrency: "USD" }, visible: ["Prompt Delivery Studio", "USD 49"] },
  { name: "ProductGroup", description: "Grouped product variants.", props: { name: "Prompt Delivery Studio", variesBy: ["Region"], hasVariant: [{ name: "US" }, { name: "EU" }] }, visible: ["Prompt Delivery Studio", "US"] },
  { name: "ProfilePage", description: "Person or entity profile page.", props: { name: "Jacob Stewart", mainEntity: "https://mdwrk.test/authors/jacob" }, visible: ["Jacob Stewart", "https://mdwrk.test/authors/jacob"] },
  { name: "QAPage", description: "Question-and-answer landing surface.", props: { question: "What is prompt drift?", answer: "Behavior change over time.", answerCount: 2 }, visible: ["What is prompt drift?", "Behavior change over time."] },
  { name: "Question", description: "Single question block with accepted answer.", props: { name: "What is prompt drift?", acceptedAnswer: { text: "Behavior change over time." }, answerCount: 1 }, visible: ["What is prompt drift?", "Behavior change over time."] },
  { name: "Quiz", description: "Assessment shell with question cards.", props: { name: "Prompt QA", description: "Review core concepts.", questions: [{ prompt: "What is latency?", answer: "Elapsed time." }] }, visible: ["Prompt QA", "What is latency?"] },
  { name: "ReadAction", description: "Read action surface.", props: { target: "https://mdwrk.test/docs" }, visible: ["https://mdwrk.test/docs"] },
  { name: "RealEstateListing", description: "Real-estate listing page shell.", props: { name: "Prompt loft", description: "Workspace-forward rental.", location: "Chicago, IL", offers: [{ name: "Lease option", price: "USD 3200/mo" }] }, visible: ["Prompt loft", "USD 3200/mo"] },
  { name: "Recipe", description: "Recipe-style checklist shell.", props: { name: "Prompt review checklist", recipeIngredient: ["Baseline", "Eval"], recipeInstructions: "Review each release." }, visible: ["Prompt review checklist", "Baseline"] },
  { name: "Review", description: "Review surface for an item.", props: { name: "Launch review", itemReviewed: "Prompt Delivery Studio", reviewBody: "Great release." }, visible: ["Launch review", "Prompt Delivery Studio"] },
  { name: "SearchResultsPage", description: "Search results page with query context.", props: { name: "Search results", description: "Query matches.", query: "prompt delivery", results: [{ name: "Prompt Studio", summary: "Product page." }] }, visible: ["Search results", "prompt delivery"] },
  { name: "SolveMathAction", description: "Action wrapper for math solving.", props: { target: "https://mdwrk.test/math", mathExpressionInput: "x+2=4" }, visible: ["https://mdwrk.test/math", "x+2=4"] },
  { name: "SoftwareApplication", description: "Software application landing shell.", props: { name: "Prompt Studio", applicationCategory: "ProductivityApplication", operatingSystem: "Web" }, visible: ["Prompt Studio", "ProductivityApplication"] },
  { name: "SoftwareSourceCode", description: "Source-code catalog entry.", props: { name: "Prompt CLI", codeRepository: "https://github.com/groupsum/mdwrk-pages", programmingLanguage: "TypeScript" }, visible: ["Prompt CLI", "TypeScript"] },
  { name: "SpeakableSpecification", description: "Speakable content selector surface.", props: { cssSelector: [".hero", ".summary"] }, visible: [".hero", ".summary"] },
  { name: "TechArticle", description: "Technical article specialization.", props: { title: "Prompt SDK internals", description: "Implementation notes.", body: React.createElement("p", null, "Tech body") }, visible: ["Prompt SDK internals", "Implementation notes."] },
  { name: "VacationRental", description: "Rental listing shell.", props: { name: "Prompt Cabin", address: "Remote", containsPlace: [{ name: "Workspace" }] }, visible: ["Prompt Cabin", "Remote"] },
  { name: "Vehicle", description: "Vehicle inventory surface.", props: { name: "Prompt Van", brand: { name: "MDWRK Motors" }, vehicleIdentificationNumber: "VIN123" }, visible: ["Prompt Van", "VIN123"] },
  { name: "VideoGallery", description: "Gallery shell for multiple videos.", props: { name: "Prompt video gallery", description: "All release walk-throughs.", videos: [{ name: "Prompt demo", uploadDate: "2026-05-27" }] }, visible: ["Prompt video gallery", "Prompt demo"] },
  { name: "VideoObject", description: "Video preview shell.", props: { name: "Prompt demo", thumbnailUrl: "https://mdwrk.test/thumb.png", uploadDate: "2026-05-27" }, visible: ["Prompt demo", "2026-05-27"] },
  { name: "WebApplication", description: "Browser-oriented app shell.", props: { name: "Prompt Web", applicationCategory: "BusinessApplication", operatingSystem: "Browser" }, visible: ["Prompt Web", "BusinessApplication"] },
  { name: "WebPage", description: "Generic web page shell.", props: { name: "Prompt docs", description: "Documentation page." }, visible: ["Prompt docs", "Documentation page."] },
  { name: "WebSite", description: "Site-level identity surface.", props: { name: "MDWRK Docs", publisher: "MDWRK" }, visible: ["MDWRK Docs", "MDWRK"] }
].map((entry) => ({
  ...entry,
  family: familyByName[entry.name],
}));

export const showcaseEntriesByFamily = showcaseFamilyOrder.map((family) => ({
  family,
  description: showcaseFamilyDescriptions[family],
  entries: showcaseEntries.filter((entry) => entry.family === family),
}));
