import type { PageSpec } from "@mdwrk/lander-content-contract";
import { createProductSitePreset } from "@mdwrk/lander-page-template-presets";
import {
  buildPageSpecsFromGraph,
  compilePageTemplateGraph,
  createGeneratedPageTemplateContentPack,
  deriveTemplateNavigation,
  resolveLinkSlots,
} from "@mdwrk/lander-page-templates";
import { pageTemplateDemoMarkdownFiles } from "./generated/markdown-pages.js";
import { createPageTemplateDemoMarkdownPreset } from "./markdown-preset.js";
import { PAGE_TEMPLATE_DEMO_CONTENT_PACK_VERSION } from "./version.js";

export { PAGE_TEMPLATE_DEMO_CONTENT_PACK_VERSION };

export const PAGE_TEMPLATE_DEMO_CONTENT_PACK_NAME = "@mdwrk/page-template-demo-content-pack";

export const pageTemplateDemoPreset = createProductSitePreset({
  baseSlug: "/demo",
  title: "Acme Notebook",
  description: "A demo product site generated from page-template presets.",
  pages: {
    home: {
      title: "Acme Notebook",
      description: "A template-generated product home page.",
      data: {
        summary: "A notebook app demo that shows page templates wiring a content pack.",
        intro: "This page is generated from a product-site page-template preset with authored content overrides.",
        sections: [
          {
            id: "hero",
            kind: "markdown",
            title: "Template-authored product site",
            body: "The content pack owns the page content while the preset owns graph shape, links, schema, and page intent wiring.",
          },
          {
            id: "workflow",
            kind: "markdown",
            title: "Downstream implementation shape",
            body: "An app can import this content pack, iterate pages, and render the PageSpec objects with lander-react.",
          },
        ],
      },
    },
    feature: {
      title: "Offline Notes",
      description: "Feature page generated from the product feature template.",
      data: {
        summary: "Keep notes available locally and ready for publishing.",
        intro: "This feature page is linked from the generated home page through the preset graph.",
      },
    },
    pricing: {
      title: "Simple Pricing",
      description: "Pricing page generated from the product pricing template.",
      data: {
        summary: "A pricing page included as a default graph child.",
      },
    },
    support: {
      title: "Acme Notebook Support",
      description: "Support hub generated by the product site preset.",
      data: {
        summary: "Route users to support answers and policies.",
      },
    },
    privacy: {
      title: "Acme Notebook Privacy",
      description: "Privacy page generated from a trust template.",
      data: {
        summary: "Explain how the demo product treats customer content.",
      },
    },
  },
  links: {
    home: {
      children: ["feature", "pricing"],
      support: ["support"],
      legal: ["privacy", "terms"],
    },
  },
});

const compiled = buildPageSpecsFromGraph(pageTemplateDemoPreset.graph);

export { pageTemplateDemoMarkdownFiles };

export const pageTemplateDemoMarkdownPreset = createPageTemplateDemoMarkdownPreset(pageTemplateDemoMarkdownFiles);

export const pageTemplateDemoMarkdownCompiled = compilePageTemplateGraph({
  id: pageTemplateDemoMarkdownPreset.id,
  graph: pageTemplateDemoMarkdownPreset.graph,
});

export const pageTemplateDemoGeneratedContentPack = createGeneratedPageTemplateContentPack({
  packageName: PAGE_TEMPLATE_DEMO_CONTENT_PACK_NAME,
  version: PAGE_TEMPLATE_DEMO_CONTENT_PACK_VERSION,
  compiled: pageTemplateDemoMarkdownCompiled,
});

export interface PageTemplateDemoContentPack {
  packageName: typeof PAGE_TEMPLATE_DEMO_CONTENT_PACK_NAME;
  version: typeof PAGE_TEMPLATE_DEMO_CONTENT_PACK_VERSION;
  presetId: string;
  domain: string;
  pages: readonly PageSpec[];
  diagnostics: Readonly<typeof compiled.diagnostics>;
  generated: typeof pageTemplateDemoGeneratedContentPack;
}

export const pageTemplateDemoContentPack: PageTemplateDemoContentPack = Object.freeze({
  packageName: PAGE_TEMPLATE_DEMO_CONTENT_PACK_NAME,
  version: PAGE_TEMPLATE_DEMO_CONTENT_PACK_VERSION,
  presetId: pageTemplateDemoPreset.id,
  domain: pageTemplateDemoPreset.domain,
  pages: Object.freeze(compiled.pages),
  diagnostics: Object.freeze(compiled.diagnostics),
  generated: pageTemplateDemoGeneratedContentPack,
});

export function getPageTemplateDemoPage(slug: string): PageSpec | undefined {
  return pageTemplateDemoContentPack.pages.find((page) => page.slug === slug);
}

export function getPageTemplateDemoHomeNavigation() {
  return deriveTemplateNavigation(pageTemplateDemoPreset.graph, "product:home");
}

export function getPageTemplateDemoHomeLinks() {
  return resolveLinkSlots(pageTemplateDemoPreset.graph, "product:home");
}
