export { SchemaPropertyReturnPolicySeasonalOverride } from "./components/schema-property-return-policy-seasonal-override.js";
export type { SchemaPropertyReturnPolicySeasonalOverrideProps } from "./components/schema-property-return-policy-seasonal-override.js";
export { SchemaPropertyReturnShippingFeesAmount } from "./components/schema-property-return-shipping-fees-amount.js";
export type { SchemaPropertyReturnShippingFeesAmountProps } from "./components/schema-property-return-shipping-fees-amount.js";
export { SchemaPropertyReview } from "./components/schema-property-review.js";
export type { SchemaPropertyReviewProps } from "./components/schema-property-review.js";
export { SchemaPropertyReviewAspect } from "./components/schema-property-review-aspect.js";
export type { SchemaPropertyReviewAspectProps } from "./components/schema-property-review-aspect.js";
export { SchemaPropertyReviewBody } from "./components/schema-property-review-body.js";
export type { SchemaPropertyReviewBodyProps } from "./components/schema-property-review-body.js";
export { SchemaPropertyReviewCount } from "./components/schema-property-review-count.js";
export type { SchemaPropertyReviewCountProps } from "./components/schema-property-review-count.js";
export { SchemaPropertyReviewedBy } from "./components/schema-property-reviewed-by.js";
export type { SchemaPropertyReviewedByProps } from "./components/schema-property-reviewed-by.js";
export { SchemaPropertyReviewRating } from "./components/schema-property-review-rating.js";
export type { SchemaPropertyReviewRatingProps } from "./components/schema-property-review-rating.js";
export { SchemaPropertyReviews } from "./components/schema-property-reviews.js";
export type { SchemaPropertyReviewsProps } from "./components/schema-property-reviews.js";
export { SchemaPropertyRiskFactor } from "./components/schema-property-risk-factor.js";
export type { SchemaPropertyRiskFactorProps } from "./components/schema-property-risk-factor.js";
export { SchemaPropertyRisks } from "./components/schema-property-risks.js";
export type { SchemaPropertyRisksProps } from "./components/schema-property-risks.js";
export { SchemaPropertyRuntimePlatform } from "./components/schema-property-runtime-platform.js";
export type { SchemaPropertyRuntimePlatformProps } from "./components/schema-property-runtime-platform.js";
export { SchemaPropertyRxcui } from "./components/schema-property-rxcui.js";
export type { SchemaPropertyRxcuiProps } from "./components/schema-property-rxcui.js";
export { SchemaPropertySameAs } from "./components/schema-property-same-as.js";
export type { SchemaPropertySameAsProps } from "./components/schema-property-same-as.js";
export { SchemaPropertySaturatedFatContent } from "./components/schema-property-saturated-fat-content.js";
export type { SchemaPropertySaturatedFatContentProps } from "./components/schema-property-saturated-fat-content.js";
export { SchemaPropertyScheduleTimezone } from "./components/schema-property-schedule-timezone.js";
export type { SchemaPropertyScheduleTimezoneProps } from "./components/schema-property-schedule-timezone.js";
export { SchemaPropertySchemaVersion } from "./components/schema-property-schema-version.js";
export type { SchemaPropertySchemaVersionProps } from "./components/schema-property-schema-version.js";
export { SchemaPropertyScreenshot } from "./components/schema-property-screenshot.js";
export type { SchemaPropertyScreenshotProps } from "./components/schema-property-screenshot.js";
export { SchemaPropertySdDatePublished } from "./components/schema-property-sd-date-published.js";
export type { SchemaPropertySdDatePublishedProps } from "./components/schema-property-sd-date-published.js";
export { SchemaPropertySdLicense } from "./components/schema-property-sd-license.js";
export type { SchemaPropertySdLicenseProps } from "./components/schema-property-sd-license.js";
export { SchemaPropertySdPublisher } from "./components/schema-property-sd-publisher.js";
export type { SchemaPropertySdPublisherProps } from "./components/schema-property-sd-publisher.js";
export { SchemaPropertySeasonalOverride } from "./components/schema-property-seasonal-override.js";
export type { SchemaPropertySeasonalOverrideProps } from "./components/schema-property-seasonal-override.js";
export { SchemaPropertySeasonNumber } from "./components/schema-property-season-number.js";
export type { SchemaPropertySeasonNumberProps } from "./components/schema-property-season-number.js";
export { SchemaPropertySecondaryPrevention } from "./components/schema-property-secondary-prevention.js";
export type { SchemaPropertySecondaryPreventionProps } from "./components/schema-property-secondary-prevention.js";
export { SchemaPropertySeeks } from "./components/schema-property-seeks.js";
export type { SchemaPropertySeeksProps } from "./components/schema-property-seeks.js";
export { SchemaPropertySeller } from "./components/schema-property-seller.js";
export type { SchemaPropertySellerProps } from "./components/schema-property-seller.js";
export { SchemaPropertySerialNumber } from "./components/schema-property-serial-number.js";
export type { SchemaPropertySerialNumberProps } from "./components/schema-property-serial-number.js";
export { SchemaPropertySeriousAdverseOutcome } from "./components/schema-property-serious-adverse-outcome.js";
export type { SchemaPropertySeriousAdverseOutcomeProps } from "./components/schema-property-serious-adverse-outcome.js";
export { SchemaPropertyServiceArea } from "./components/schema-property-service-area.js";
export type { SchemaPropertyServiceAreaProps } from "./components/schema-property-service-area.js";
export { SchemaPropertyServiceAudience } from "./components/schema-property-service-audience.js";
export type { SchemaPropertyServiceAudienceProps } from "./components/schema-property-service-audience.js";
export { SchemaPropertyServiceLocation } from "./components/schema-property-service-location.js";
export type { SchemaPropertyServiceLocationProps } from "./components/schema-property-service-location.js";
export { SchemaPropertyServiceOutput } from "./components/schema-property-service-output.js";
export type { SchemaPropertyServiceOutputProps } from "./components/schema-property-service-output.js";
export { SchemaPropertyServicePhone } from "./components/schema-property-service-phone.js";
export type { SchemaPropertyServicePhoneProps } from "./components/schema-property-service-phone.js";
export { SchemaPropertyServicePostalAddress } from "./components/schema-property-service-postal-address.js";
export type { SchemaPropertyServicePostalAddressProps } from "./components/schema-property-service-postal-address.js";
export { SchemaPropertyServiceSmsNumber } from "./components/schema-property-service-sms-number.js";
export type { SchemaPropertyServiceSmsNumberProps } from "./components/schema-property-service-sms-number.js";
export { SchemaPropertyServiceType } from "./components/schema-property-service-type.js";
export type { SchemaPropertyServiceTypeProps } from "./components/schema-property-service-type.js";
export { SchemaPropertyServiceUrl } from "./components/schema-property-service-url.js";
export type { SchemaPropertyServiceUrlProps } from "./components/schema-property-service-url.js";
export { SchemaPropertyServingSize } from "./components/schema-property-serving-size.js";
export type { SchemaPropertyServingSizeProps } from "./components/schema-property-serving-size.js";
export { SchemaPropertySha256 } from "./components/schema-property-sha256.js";
export type { SchemaPropertySha256Props } from "./components/schema-property-sha256.js";
export { SchemaPropertySharedContent } from "./components/schema-property-shared-content.js";
export type { SchemaPropertySharedContentProps } from "./components/schema-property-shared-content.js";
export { SchemaPropertyShippingConditions } from "./components/schema-property-shipping-conditions.js";
export type { SchemaPropertyShippingConditionsProps } from "./components/schema-property-shipping-conditions.js";
export { SchemaPropertyShippingDestination } from "./components/schema-property-shipping-destination.js";
export type { SchemaPropertyShippingDestinationProps } from "./components/schema-property-shipping-destination.js";
export { SchemaPropertyShippingDetails } from "./components/schema-property-shipping-details.js";
export type { SchemaPropertyShippingDetailsProps } from "./components/schema-property-shipping-details.js";
export { SchemaPropertyShippingOrigin } from "./components/schema-property-shipping-origin.js";
export type { SchemaPropertyShippingOriginProps } from "./components/schema-property-shipping-origin.js";
export { SchemaPropertyShippingRate } from "./components/schema-property-shipping-rate.js";
export type { SchemaPropertyShippingRateProps } from "./components/schema-property-shipping-rate.js";
export { SchemaPropertySibling } from "./components/schema-property-sibling.js";
export type { SchemaPropertySiblingProps } from "./components/schema-property-sibling.js";
export { SchemaPropertySiblings } from "./components/schema-property-siblings.js";
export type { SchemaPropertySiblingsProps } from "./components/schema-property-siblings.js";
export { SchemaPropertySignDetected } from "./components/schema-property-sign-detected.js";
export type { SchemaPropertySignDetectedProps } from "./components/schema-property-sign-detected.js";
export { SchemaPropertySignificance } from "./components/schema-property-significance.js";
export type { SchemaPropertySignificanceProps } from "./components/schema-property-significance.js";
export { SchemaPropertySignificantLink } from "./components/schema-property-significant-link.js";
export type { SchemaPropertySignificantLinkProps } from "./components/schema-property-significant-link.js";
export { SchemaPropertySignificantLinks } from "./components/schema-property-significant-links.js";
export type { SchemaPropertySignificantLinksProps } from "./components/schema-property-significant-links.js";
export { SchemaPropertySignOrSymptom } from "./components/schema-property-sign-or-symptom.js";
export type { SchemaPropertySignOrSymptomProps } from "./components/schema-property-sign-or-symptom.js";
export { SchemaPropertySize } from "./components/schema-property-size.js";
export type { SchemaPropertySizeProps } from "./components/schema-property-size.js";
export { SchemaPropertySkills } from "./components/schema-property-skills.js";
export type { SchemaPropertySkillsProps } from "./components/schema-property-skills.js";
export { SchemaPropertySku } from "./components/schema-property-sku.js";
export type { SchemaPropertySkuProps } from "./components/schema-property-sku.js";
export { SchemaPropertySlogan } from "./components/schema-property-slogan.js";
export type { SchemaPropertySloganProps } from "./components/schema-property-slogan.js";
export { SchemaPropertySmokingAllowed } from "./components/schema-property-smoking-allowed.js";
export type { SchemaPropertySmokingAllowedProps } from "./components/schema-property-smoking-allowed.js";
export { SchemaPropertySodiumContent } from "./components/schema-property-sodium-content.js";
export type { SchemaPropertySodiumContentProps } from "./components/schema-property-sodium-content.js";
export { SchemaPropertySoftwareAddOn } from "./components/schema-property-software-add-on.js";
export type { SchemaPropertySoftwareAddOnProps } from "./components/schema-property-software-add-on.js";
export { SchemaPropertySoftwareHelp } from "./components/schema-property-software-help.js";
export type { SchemaPropertySoftwareHelpProps } from "./components/schema-property-software-help.js";
export { SchemaPropertySoftwareRequirements } from "./components/schema-property-software-requirements.js";
export type { SchemaPropertySoftwareRequirementsProps } from "./components/schema-property-software-requirements.js";
export { SchemaPropertySoftwareVersion } from "./components/schema-property-software-version.js";
export type { SchemaPropertySoftwareVersionProps } from "./components/schema-property-software-version.js";
export { SchemaPropertySourceOrganization } from "./components/schema-property-source-organization.js";
export type { SchemaPropertySourceOrganizationProps } from "./components/schema-property-source-organization.js";
export { SchemaPropertySpatial } from "./components/schema-property-spatial.js";
export type { SchemaPropertySpatialProps } from "./components/schema-property-spatial.js";
export { SchemaPropertySpatialCoverage } from "./components/schema-property-spatial-coverage.js";
export type { SchemaPropertySpatialCoverageProps } from "./components/schema-property-spatial-coverage.js";
export { SchemaPropertySpeakable } from "./components/schema-property-speakable.js";
export type { SchemaPropertySpeakableProps } from "./components/schema-property-speakable.js";
export { SchemaPropertySpecialOpeningHoursSpecification } from "./components/schema-property-special-opening-hours-specification.js";
export type { SchemaPropertySpecialOpeningHoursSpecificationProps } from "./components/schema-property-special-opening-hours-specification.js";
export { SchemaPropertySpecialty } from "./components/schema-property-specialty.js";
export type { SchemaPropertySpecialtyProps } from "./components/schema-property-specialty.js";
export { SchemaPropertySponsor } from "./components/schema-property-sponsor.js";
export type { SchemaPropertySponsorProps } from "./components/schema-property-sponsor.js";
export { SchemaPropertySpouse } from "./components/schema-property-spouse.js";
export type { SchemaPropertySpouseProps } from "./components/schema-property-spouse.js";
export { SchemaPropertyStage } from "./components/schema-property-stage.js";
export type { SchemaPropertyStageProps } from "./components/schema-property-stage.js";
export { SchemaPropertyStageAsNumber } from "./components/schema-property-stage-as-number.js";
export type { SchemaPropertyStageAsNumberProps } from "./components/schema-property-stage-as-number.js";
export { SchemaPropertyStartDate } from "./components/schema-property-start-date.js";
export type { SchemaPropertyStartDateProps } from "./components/schema-property-start-date.js";
export { SchemaPropertyStartOffset } from "./components/schema-property-start-offset.js";
export type { SchemaPropertyStartOffsetProps } from "./components/schema-property-start-offset.js";
export { SchemaPropertyStartTime } from "./components/schema-property-start-time.js";
export type { SchemaPropertyStartTimeProps } from "./components/schema-property-start-time.js";