export { SchemaPropertyInteractionType } from "./components/schema-property-interaction-type.js";
export type { SchemaPropertyInteractionTypeProps } from "./components/schema-property-interaction-type.js";
export { SchemaPropertyInteractivityType } from "./components/schema-property-interactivity-type.js";
export type { SchemaPropertyInteractivityTypeProps } from "./components/schema-property-interactivity-type.js";
export { SchemaPropertyInterestRate } from "./components/schema-property-interest-rate.js";
export type { SchemaPropertyInterestRateProps } from "./components/schema-property-interest-rate.js";
export { SchemaPropertyInterpretedAsClaim } from "./components/schema-property-interpreted-as-claim.js";
export type { SchemaPropertyInterpretedAsClaimProps } from "./components/schema-property-interpreted-as-claim.js";
export { SchemaPropertyInventoryLevel } from "./components/schema-property-inventory-level.js";
export type { SchemaPropertyInventoryLevelProps } from "./components/schema-property-inventory-level.js";
export { SchemaPropertyInverseOf } from "./components/schema-property-inverse-of.js";
export type { SchemaPropertyInverseOfProps } from "./components/schema-property-inverse-of.js";
export { SchemaPropertyIsAccessibleForFree } from "./components/schema-property-is-accessible-for-free.js";
export type { SchemaPropertyIsAccessibleForFreeProps } from "./components/schema-property-is-accessible-for-free.js";
export { SchemaPropertyIsAccessoryOrSparePartFor } from "./components/schema-property-is-accessory-or-spare-part-for.js";
export type { SchemaPropertyIsAccessoryOrSparePartForProps } from "./components/schema-property-is-accessory-or-spare-part-for.js";
export { SchemaPropertyIsAvailableGenerically } from "./components/schema-property-is-available-generically.js";
export type { SchemaPropertyIsAvailableGenericallyProps } from "./components/schema-property-is-available-generically.js";
export { SchemaPropertyIsBasedOn } from "./components/schema-property-is-based-on.js";
export type { SchemaPropertyIsBasedOnProps } from "./components/schema-property-is-based-on.js";
export { SchemaPropertyIsBasedOnUrl } from "./components/schema-property-is-based-on-url.js";
export type { SchemaPropertyIsBasedOnUrlProps } from "./components/schema-property-is-based-on-url.js";
export { SchemaPropertyIsConsumableFor } from "./components/schema-property-is-consumable-for.js";
export type { SchemaPropertyIsConsumableForProps } from "./components/schema-property-is-consumable-for.js";
export { SchemaPropertyIsEncodedByBioChemEntity } from "./components/schema-property-is-encoded-by-bio-chem-entity.js";
export type { SchemaPropertyIsEncodedByBioChemEntityProps } from "./components/schema-property-is-encoded-by-bio-chem-entity.js";
export { SchemaPropertyIsFamilyFriendly } from "./components/schema-property-is-family-friendly.js";
export type { SchemaPropertyIsFamilyFriendlyProps } from "./components/schema-property-is-family-friendly.js";
export { SchemaPropertyIsicV4 } from "./components/schema-property-isic-v4.js";
export type { SchemaPropertyIsicV4Props } from "./components/schema-property-isic-v4.js";
export { SchemaPropertyIsInvolvedInBiologicalProcess } from "./components/schema-property-is-involved-in-biological-process.js";
export type { SchemaPropertyIsInvolvedInBiologicalProcessProps } from "./components/schema-property-is-involved-in-biological-process.js";
export { SchemaPropertyIsLocatedInSubcellularLocation } from "./components/schema-property-is-located-in-subcellular-location.js";
export type { SchemaPropertyIsLocatedInSubcellularLocationProps } from "./components/schema-property-is-located-in-subcellular-location.js";
export { SchemaPropertyIso6523Code } from "./components/schema-property-iso6523-code.js";
export type { SchemaPropertyIso6523CodeProps } from "./components/schema-property-iso6523-code.js";
export { SchemaPropertyIsPartOf } from "./components/schema-property-is-part-of.js";
export type { SchemaPropertyIsPartOfProps } from "./components/schema-property-is-part-of.js";
export { SchemaPropertyIsPartOfBioChemEntity } from "./components/schema-property-is-part-of-bio-chem-entity.js";
export type { SchemaPropertyIsPartOfBioChemEntityProps } from "./components/schema-property-is-part-of-bio-chem-entity.js";
export { SchemaPropertyIsProprietary } from "./components/schema-property-is-proprietary.js";
export type { SchemaPropertyIsProprietaryProps } from "./components/schema-property-is-proprietary.js";
export { SchemaPropertyIsrcCode } from "./components/schema-property-isrc-code.js";
export type { SchemaPropertyIsrcCodeProps } from "./components/schema-property-isrc-code.js";
export { SchemaPropertyIsRelatedTo } from "./components/schema-property-is-related-to.js";
export type { SchemaPropertyIsRelatedToProps } from "./components/schema-property-is-related-to.js";
export { SchemaPropertyIsSimilarTo } from "./components/schema-property-is-similar-to.js";
export type { SchemaPropertyIsSimilarToProps } from "./components/schema-property-is-similar-to.js";
export { SchemaPropertyIssn } from "./components/schema-property-issn.js";
export type { SchemaPropertyIssnProps } from "./components/schema-property-issn.js";
export { SchemaPropertyIssuedBy } from "./components/schema-property-issued-by.js";
export type { SchemaPropertyIssuedByProps } from "./components/schema-property-issued-by.js";
export { SchemaPropertyIsTierOf } from "./components/schema-property-is-tier-of.js";
export type { SchemaPropertyIsTierOfProps } from "./components/schema-property-is-tier-of.js";
export { SchemaPropertyIsUnlabelledFallback } from "./components/schema-property-is-unlabelled-fallback.js";
export type { SchemaPropertyIsUnlabelledFallbackProps } from "./components/schema-property-is-unlabelled-fallback.js";
export { SchemaPropertyIsVariantOf } from "./components/schema-property-is-variant-of.js";
export type { SchemaPropertyIsVariantOfProps } from "./components/schema-property-is-variant-of.js";
export { SchemaPropertyIswcCode } from "./components/schema-property-iswc-code.js";
export type { SchemaPropertyIswcCodeProps } from "./components/schema-property-iswc-code.js";
export { SchemaPropertyItem } from "./components/schema-property-item.js";
export type { SchemaPropertyItemProps } from "./components/schema-property-item.js";
export { SchemaPropertyItemCondition } from "./components/schema-property-item-condition.js";
export type { SchemaPropertyItemConditionProps } from "./components/schema-property-item-condition.js";
export { SchemaPropertyItemDefectReturnFees } from "./components/schema-property-item-defect-return-fees.js";
export type { SchemaPropertyItemDefectReturnFeesProps } from "./components/schema-property-item-defect-return-fees.js";
export { SchemaPropertyItemDefectReturnLabelSource } from "./components/schema-property-item-defect-return-label-source.js";
export type { SchemaPropertyItemDefectReturnLabelSourceProps } from "./components/schema-property-item-defect-return-label-source.js";
export { SchemaPropertyItemDefectReturnShippingFeesAmount } from "./components/schema-property-item-defect-return-shipping-fees-amount.js";
export type { SchemaPropertyItemDefectReturnShippingFeesAmountProps } from "./components/schema-property-item-defect-return-shipping-fees-amount.js";
export { SchemaPropertyItemListElement } from "./components/schema-property-item-list-element.js";
export type { SchemaPropertyItemListElementProps } from "./components/schema-property-item-list-element.js";
export { SchemaPropertyItemListOrder } from "./components/schema-property-item-list-order.js";
export type { SchemaPropertyItemListOrderProps } from "./components/schema-property-item-list-order.js";
export { SchemaPropertyItemOffered } from "./components/schema-property-item-offered.js";
export type { SchemaPropertyItemOfferedProps } from "./components/schema-property-item-offered.js";
export { SchemaPropertyItemReviewed } from "./components/schema-property-item-reviewed.js";
export type { SchemaPropertyItemReviewedProps } from "./components/schema-property-item-reviewed.js";
export { SchemaPropertyItinerary } from "./components/schema-property-itinerary.js";
export type { SchemaPropertyItineraryProps } from "./components/schema-property-itinerary.js";
export { SchemaPropertyJobTitle } from "./components/schema-property-job-title.js";
export type { SchemaPropertyJobTitleProps } from "./components/schema-property-job-title.js";
export { SchemaPropertyKeywords } from "./components/schema-property-keywords.js";
export type { SchemaPropertyKeywordsProps } from "./components/schema-property-keywords.js";
export { SchemaPropertyKnows } from "./components/schema-property-knows.js";
export type { SchemaPropertyKnowsProps } from "./components/schema-property-knows.js";
export { SchemaPropertyKnowsAbout } from "./components/schema-property-knows-about.js";
export type { SchemaPropertyKnowsAboutProps } from "./components/schema-property-knows-about.js";
export { SchemaPropertyKnowsLanguage } from "./components/schema-property-knows-language.js";
export type { SchemaPropertyKnowsLanguageProps } from "./components/schema-property-knows-language.js";
export { SchemaPropertyLabelDetails } from "./components/schema-property-label-details.js";
export type { SchemaPropertyLabelDetailsProps } from "./components/schema-property-label-details.js";
export { SchemaPropertyLastReviewed } from "./components/schema-property-last-reviewed.js";
export type { SchemaPropertyLastReviewedProps } from "./components/schema-property-last-reviewed.js";
export { SchemaPropertyLatitude } from "./components/schema-property-latitude.js";
export type { SchemaPropertyLatitudeProps } from "./components/schema-property-latitude.js";
export { SchemaPropertyLearningResourceType } from "./components/schema-property-learning-resource-type.js";
export type { SchemaPropertyLearningResourceTypeProps } from "./components/schema-property-learning-resource-type.js";
export { SchemaPropertyLeaseLength } from "./components/schema-property-lease-length.js";
export type { SchemaPropertyLeaseLengthProps } from "./components/schema-property-lease-length.js";
export { SchemaPropertyLegalAddress } from "./components/schema-property-legal-address.js";
export type { SchemaPropertyLegalAddressProps } from "./components/schema-property-legal-address.js";
export { SchemaPropertyLegalName } from "./components/schema-property-legal-name.js";
export type { SchemaPropertyLegalNameProps } from "./components/schema-property-legal-name.js";
export { SchemaPropertyLegalRepresentative } from "./components/schema-property-legal-representative.js";
export type { SchemaPropertyLegalRepresentativeProps } from "./components/schema-property-legal-representative.js";
export { SchemaPropertyLegalStatus } from "./components/schema-property-legal-status.js";
export type { SchemaPropertyLegalStatusProps } from "./components/schema-property-legal-status.js";
export { SchemaPropertyLeiCode } from "./components/schema-property-lei-code.js";
export type { SchemaPropertyLeiCodeProps } from "./components/schema-property-lei-code.js";
export { SchemaPropertyLicense } from "./components/schema-property-license.js";
export type { SchemaPropertyLicenseProps } from "./components/schema-property-license.js";
export { SchemaPropertyLifeEvent } from "./components/schema-property-life-event.js";
export type { SchemaPropertyLifeEventProps } from "./components/schema-property-life-event.js";
export { SchemaPropertyLine } from "./components/schema-property-line.js";
export type { SchemaPropertyLineProps } from "./components/schema-property-line.js";
export { SchemaPropertyLoanPaymentAmount } from "./components/schema-property-loan-payment-amount.js";
export type { SchemaPropertyLoanPaymentAmountProps } from "./components/schema-property-loan-payment-amount.js";
export { SchemaPropertyLoanPaymentFrequency } from "./components/schema-property-loan-payment-frequency.js";
export type { SchemaPropertyLoanPaymentFrequencyProps } from "./components/schema-property-loan-payment-frequency.js";
export { SchemaPropertyLoanRepaymentForm } from "./components/schema-property-loan-repayment-form.js";
export type { SchemaPropertyLoanRepaymentFormProps } from "./components/schema-property-loan-repayment-form.js";
export { SchemaPropertyLoanTerm } from "./components/schema-property-loan-term.js";
export type { SchemaPropertyLoanTermProps } from "./components/schema-property-loan-term.js";
export { SchemaPropertyLoanType } from "./components/schema-property-loan-type.js";
export type { SchemaPropertyLoanTypeProps } from "./components/schema-property-loan-type.js";
export { SchemaPropertyLocation } from "./components/schema-property-location.js";
export type { SchemaPropertyLocationProps } from "./components/schema-property-location.js";
export { SchemaPropertyLocationCreated } from "./components/schema-property-location-created.js";
export type { SchemaPropertyLocationCreatedProps } from "./components/schema-property-location-created.js";
export { SchemaPropertyLogo } from "./components/schema-property-logo.js";
export type { SchemaPropertyLogoProps } from "./components/schema-property-logo.js";
export { SchemaPropertyLongitude } from "./components/schema-property-longitude.js";
export type { SchemaPropertyLongitudeProps } from "./components/schema-property-longitude.js";
export { SchemaPropertyLowPrice } from "./components/schema-property-low-price.js";
export type { SchemaPropertyLowPriceProps } from "./components/schema-property-low-price.js";
export { SchemaPropertyLyricist } from "./components/schema-property-lyricist.js";
export type { SchemaPropertyLyricistProps } from "./components/schema-property-lyricist.js";
export { SchemaPropertyLyrics } from "./components/schema-property-lyrics.js";
export type { SchemaPropertyLyricsProps } from "./components/schema-property-lyrics.js";
export { SchemaPropertyMainContentOfPage } from "./components/schema-property-main-content-of-page.js";
export type { SchemaPropertyMainContentOfPageProps } from "./components/schema-property-main-content-of-page.js";
export { SchemaPropertyMainEntity } from "./components/schema-property-main-entity.js";
export type { SchemaPropertyMainEntityProps } from "./components/schema-property-main-entity.js";
export { SchemaPropertyMainEntityOfPage } from "./components/schema-property-main-entity-of-page.js";
export type { SchemaPropertyMainEntityOfPageProps } from "./components/schema-property-main-entity-of-page.js";
export { SchemaPropertyMaintainer } from "./components/schema-property-maintainer.js";
export type { SchemaPropertyMaintainerProps } from "./components/schema-property-maintainer.js";
export { SchemaPropertyMakesOffer } from "./components/schema-property-makes-offer.js";
export type { SchemaPropertyMakesOfferProps } from "./components/schema-property-makes-offer.js";