export { SchemaPropertyAbout } from "./components/schema-property-about.js";
export type { SchemaPropertyAboutProps } from "./components/schema-property-about.js";
export { SchemaPropertyAbstract } from "./components/schema-property-abstract.js";
export type { SchemaPropertyAbstractProps } from "./components/schema-property-abstract.js";
export { SchemaPropertyAcceptedPaymentMethod } from "./components/schema-property-accepted-payment-method.js";
export type { SchemaPropertyAcceptedPaymentMethodProps } from "./components/schema-property-accepted-payment-method.js";
export { SchemaPropertyAccessibilityAPI } from "./components/schema-property-accessibility-api.js";
export type { SchemaPropertyAccessibilityAPIProps } from "./components/schema-property-accessibility-api.js";
export { SchemaPropertyAccessibilityControl } from "./components/schema-property-accessibility-control.js";
export type { SchemaPropertyAccessibilityControlProps } from "./components/schema-property-accessibility-control.js";
export { SchemaPropertyAccessibilityFeature } from "./components/schema-property-accessibility-feature.js";
export type { SchemaPropertyAccessibilityFeatureProps } from "./components/schema-property-accessibility-feature.js";
export { SchemaPropertyAccessibilityHazard } from "./components/schema-property-accessibility-hazard.js";
export type { SchemaPropertyAccessibilityHazardProps } from "./components/schema-property-accessibility-hazard.js";
export { SchemaPropertyAccessibilitySummary } from "./components/schema-property-accessibility-summary.js";
export type { SchemaPropertyAccessibilitySummaryProps } from "./components/schema-property-accessibility-summary.js";
export { SchemaPropertyAccessMode } from "./components/schema-property-access-mode.js";
export type { SchemaPropertyAccessModeProps } from "./components/schema-property-access-mode.js";
export { SchemaPropertyAccessModeSufficient } from "./components/schema-property-access-mode-sufficient.js";
export type { SchemaPropertyAccessModeSufficientProps } from "./components/schema-property-access-mode-sufficient.js";
export { SchemaPropertyAccountablePerson } from "./components/schema-property-accountable-person.js";
export type { SchemaPropertyAccountablePersonProps } from "./components/schema-property-accountable-person.js";
export { SchemaPropertyAcquireLicensePage } from "./components/schema-property-acquire-license-page.js";
export type { SchemaPropertyAcquireLicensePageProps } from "./components/schema-property-acquire-license-page.js";
export { SchemaPropertyActionableFeedbackPolicy } from "./components/schema-property-actionable-feedback-policy.js";
export type { SchemaPropertyActionableFeedbackPolicyProps } from "./components/schema-property-actionable-feedback-policy.js";
export { SchemaPropertyActionApplication } from "./components/schema-property-action-application.js";
export type { SchemaPropertyActionApplicationProps } from "./components/schema-property-action-application.js";
export { SchemaPropertyActionPlatform } from "./components/schema-property-action-platform.js";
export type { SchemaPropertyActionPlatformProps } from "./components/schema-property-action-platform.js";
export { SchemaPropertyActionProcess } from "./components/schema-property-action-process.js";
export type { SchemaPropertyActionProcessProps } from "./components/schema-property-action-process.js";
export { SchemaPropertyActionStatus } from "./components/schema-property-action-status.js";
export type { SchemaPropertyActionStatusProps } from "./components/schema-property-action-status.js";
export { SchemaPropertyActiveIngredient } from "./components/schema-property-active-ingredient.js";
export type { SchemaPropertyActiveIngredientProps } from "./components/schema-property-active-ingredient.js";
export { SchemaPropertyActor } from "./components/schema-property-actor.js";
export type { SchemaPropertyActorProps } from "./components/schema-property-actor.js";
export { SchemaPropertyActors } from "./components/schema-property-actors.js";
export type { SchemaPropertyActorsProps } from "./components/schema-property-actors.js";
export { SchemaPropertyAdditionalName } from "./components/schema-property-additional-name.js";
export type { SchemaPropertyAdditionalNameProps } from "./components/schema-property-additional-name.js";
export { SchemaPropertyAdditionalProperty } from "./components/schema-property-additional-property.js";
export type { SchemaPropertyAdditionalPropertyProps } from "./components/schema-property-additional-property.js";
export { SchemaPropertyAdditionalType } from "./components/schema-property-additional-type.js";
export type { SchemaPropertyAdditionalTypeProps } from "./components/schema-property-additional-type.js";
export { SchemaPropertyAddOn } from "./components/schema-property-add-on.js";
export type { SchemaPropertyAddOnProps } from "./components/schema-property-add-on.js";
export { SchemaPropertyAddress } from "./components/schema-property-address.js";
export type { SchemaPropertyAddressProps } from "./components/schema-property-address.js";
export { SchemaPropertyAddressCountry } from "./components/schema-property-address-country.js";
export type { SchemaPropertyAddressCountryProps } from "./components/schema-property-address-country.js";
export { SchemaPropertyAddressLocality } from "./components/schema-property-address-locality.js";
export type { SchemaPropertyAddressLocalityProps } from "./components/schema-property-address-locality.js";
export { SchemaPropertyAddressRegion } from "./components/schema-property-address-region.js";
export type { SchemaPropertyAddressRegionProps } from "./components/schema-property-address-region.js";
export { SchemaPropertyAdministrationRoute } from "./components/schema-property-administration-route.js";
export type { SchemaPropertyAdministrationRouteProps } from "./components/schema-property-administration-route.js";
export { SchemaPropertyAdvanceBookingRequirement } from "./components/schema-property-advance-booking-requirement.js";
export type { SchemaPropertyAdvanceBookingRequirementProps } from "./components/schema-property-advance-booking-requirement.js";
export { SchemaPropertyAdverseOutcome } from "./components/schema-property-adverse-outcome.js";
export type { SchemaPropertyAdverseOutcomeProps } from "./components/schema-property-adverse-outcome.js";
export { SchemaPropertyAffectedBy } from "./components/schema-property-affected-by.js";
export type { SchemaPropertyAffectedByProps } from "./components/schema-property-affected-by.js";
export { SchemaPropertyAffiliation } from "./components/schema-property-affiliation.js";
export type { SchemaPropertyAffiliationProps } from "./components/schema-property-affiliation.js";
export { SchemaPropertyAgent } from "./components/schema-property-agent.js";
export type { SchemaPropertyAgentProps } from "./components/schema-property-agent.js";
export { SchemaPropertyAgentInteractionStatistic } from "./components/schema-property-agent-interaction-statistic.js";
export type { SchemaPropertyAgentInteractionStatisticProps } from "./components/schema-property-agent-interaction-statistic.js";
export { SchemaPropertyAggregateElement } from "./components/schema-property-aggregate-element.js";
export type { SchemaPropertyAggregateElementProps } from "./components/schema-property-aggregate-element.js";
export { SchemaPropertyAggregateRating } from "./components/schema-property-aggregate-rating.js";
export type { SchemaPropertyAggregateRatingProps } from "./components/schema-property-aggregate-rating.js";
export { SchemaPropertyAlbum } from "./components/schema-property-album.js";
export type { SchemaPropertyAlbumProps } from "./components/schema-property-album.js";
export { SchemaPropertyAlbumProductionType } from "./components/schema-property-album-production-type.js";
export type { SchemaPropertyAlbumProductionTypeProps } from "./components/schema-property-album-production-type.js";
export { SchemaPropertyAlbumRelease } from "./components/schema-property-album-release.js";
export type { SchemaPropertyAlbumReleaseProps } from "./components/schema-property-album-release.js";
export { SchemaPropertyAlbumReleaseType } from "./components/schema-property-album-release-type.js";
export type { SchemaPropertyAlbumReleaseTypeProps } from "./components/schema-property-album-release-type.js";
export { SchemaPropertyAlbums } from "./components/schema-property-albums.js";
export type { SchemaPropertyAlbumsProps } from "./components/schema-property-albums.js";
export { SchemaPropertyAlcoholWarning } from "./components/schema-property-alcohol-warning.js";
export type { SchemaPropertyAlcoholWarningProps } from "./components/schema-property-alcohol-warning.js";
export { SchemaPropertyAlignmentType } from "./components/schema-property-alignment-type.js";
export type { SchemaPropertyAlignmentTypeProps } from "./components/schema-property-alignment-type.js";
export { SchemaPropertyAlternateName } from "./components/schema-property-alternate-name.js";
export type { SchemaPropertyAlternateNameProps } from "./components/schema-property-alternate-name.js";
export { SchemaPropertyAlternativeHeadline } from "./components/schema-property-alternative-headline.js";
export type { SchemaPropertyAlternativeHeadlineProps } from "./components/schema-property-alternative-headline.js";
export { SchemaPropertyAlternativeOf } from "./components/schema-property-alternative-of.js";
export type { SchemaPropertyAlternativeOfProps } from "./components/schema-property-alternative-of.js";
export { SchemaPropertyAlumni } from "./components/schema-property-alumni.js";
export type { SchemaPropertyAlumniProps } from "./components/schema-property-alumni.js";
export { SchemaPropertyAlumniOf } from "./components/schema-property-alumni-of.js";
export type { SchemaPropertyAlumniOfProps } from "./components/schema-property-alumni-of.js";
export { SchemaPropertyAmenityFeature } from "./components/schema-property-amenity-feature.js";
export type { SchemaPropertyAmenityFeatureProps } from "./components/schema-property-amenity-feature.js";
export { SchemaPropertyAmount } from "./components/schema-property-amount.js";
export type { SchemaPropertyAmountProps } from "./components/schema-property-amount.js";
export { SchemaPropertyAmountOfThisGood } from "./components/schema-property-amount-of-this-good.js";
export type { SchemaPropertyAmountOfThisGoodProps } from "./components/schema-property-amount-of-this-good.js";
export { SchemaPropertyAnnualPercentageRate } from "./components/schema-property-annual-percentage-rate.js";
export type { SchemaPropertyAnnualPercentageRateProps } from "./components/schema-property-annual-percentage-rate.js";
export { SchemaPropertyAppearance } from "./components/schema-property-appearance.js";
export type { SchemaPropertyAppearanceProps } from "./components/schema-property-appearance.js";
export { SchemaPropertyApplicableCountry } from "./components/schema-property-applicable-country.js";
export type { SchemaPropertyApplicableCountryProps } from "./components/schema-property-applicable-country.js";
export { SchemaPropertyApplicableLocation } from "./components/schema-property-applicable-location.js";
export type { SchemaPropertyApplicableLocationProps } from "./components/schema-property-applicable-location.js";
export { SchemaPropertyApplication } from "./components/schema-property-application.js";
export type { SchemaPropertyApplicationProps } from "./components/schema-property-application.js";
export { SchemaPropertyApplicationCategory } from "./components/schema-property-application-category.js";
export type { SchemaPropertyApplicationCategoryProps } from "./components/schema-property-application-category.js";
export { SchemaPropertyApplicationSubCategory } from "./components/schema-property-application-sub-category.js";
export type { SchemaPropertyApplicationSubCategoryProps } from "./components/schema-property-application-sub-category.js";
export { SchemaPropertyApplicationSuite } from "./components/schema-property-application-suite.js";
export type { SchemaPropertyApplicationSuiteProps } from "./components/schema-property-application-suite.js";
export { SchemaPropertyAppliesToDeliveryMethod } from "./components/schema-property-applies-to-delivery-method.js";
export type { SchemaPropertyAppliesToDeliveryMethodProps } from "./components/schema-property-applies-to-delivery-method.js";
export { SchemaPropertyArchivedAt } from "./components/schema-property-archived-at.js";
export type { SchemaPropertyArchivedAtProps } from "./components/schema-property-archived-at.js";
export { SchemaPropertyArea } from "./components/schema-property-area.js";
export type { SchemaPropertyAreaProps } from "./components/schema-property-area.js";
export { SchemaPropertyAreaServed } from "./components/schema-property-area-served.js";
export type { SchemaPropertyAreaServedProps } from "./components/schema-property-area-served.js";
export { SchemaPropertyArrivalTime } from "./components/schema-property-arrival-time.js";
export type { SchemaPropertyArrivalTimeProps } from "./components/schema-property-arrival-time.js";
export { SchemaPropertyArticleBody } from "./components/schema-property-article-body.js";
export type { SchemaPropertyArticleBodyProps } from "./components/schema-property-article-body.js";
export { SchemaPropertyArticleSection } from "./components/schema-property-article-section.js";
export type { SchemaPropertyArticleSectionProps } from "./components/schema-property-article-section.js";
export { SchemaPropertyAsin } from "./components/schema-property-asin.js";
export type { SchemaPropertyAsinProps } from "./components/schema-property-asin.js";
export { SchemaPropertyAspect } from "./components/schema-property-aspect.js";
export type { SchemaPropertyAspectProps } from "./components/schema-property-aspect.js";
export { SchemaPropertyAssesses } from "./components/schema-property-assesses.js";
export type { SchemaPropertyAssessesProps } from "./components/schema-property-assesses.js";
export { SchemaPropertyAssociatedAnatomy } from "./components/schema-property-associated-anatomy.js";
export type { SchemaPropertyAssociatedAnatomyProps } from "./components/schema-property-associated-anatomy.js";
export { SchemaPropertyAssociatedArticle } from "./components/schema-property-associated-article.js";
export type { SchemaPropertyAssociatedArticleProps } from "./components/schema-property-associated-article.js";
export { SchemaPropertyAssociatedClaimReview } from "./components/schema-property-associated-claim-review.js";
export type { SchemaPropertyAssociatedClaimReviewProps } from "./components/schema-property-associated-claim-review.js";
export { SchemaPropertyAssociatedDisease } from "./components/schema-property-associated-disease.js";
export type { SchemaPropertyAssociatedDiseaseProps } from "./components/schema-property-associated-disease.js";
export { SchemaPropertyAssociatedMedia } from "./components/schema-property-associated-media.js";
export type { SchemaPropertyAssociatedMediaProps } from "./components/schema-property-associated-media.js";