import { defineTemplateBundle } from "../define.js";
import { createDomainPageTemplate } from "./shared.js";

export const docsTemplates = [
  createDomainPageTemplate({ id: "docs.hub", domain: "docs", kind: "docs_bridge", title: "Docs hub", description: "Documentation hub page.", fallbackSchemaKinds: ["WebPage"], linkSlots: [{ id: "children", relationship: "child", role: "tree_child", cardinality: "optional_many", ordered: true }], topology: { childPolicy: "optional", childSlots: [{ id: "children", relationship: "child", targetTemplateIds: ["docs.guide", "docs.reference", "docs.api", "docs.tutorial", "docs.troubleshooting", "docs.release-note"], min: 0, ordered: true }] } }),
  createDomainPageTemplate({ id: "docs.guide", domain: "docs", kind: "docs_bridge", title: "Guide page", description: "Documentation guide page.", fallbackSchemaKinds: ["TechArticle"], linkSlots: [{ id: "parent", relationship: "parent", role: "navigation", cardinality: "optional_one" }, { id: "previous", relationship: "previous", role: "navigation", cardinality: "optional_one" }, { id: "next", relationship: "next", role: "navigation", cardinality: "optional_one" }], topology: { childPolicy: "optional", childSlots: [{ id: "children", relationship: "child", min: 0, ordered: true }] } }),
  createDomainPageTemplate({ id: "docs.reference", domain: "docs", kind: "docs_bridge", title: "Reference page", description: "Reference documentation page.", fallbackSchemaKinds: ["TechArticle"], linkSlots: [{ id: "parent", relationship: "parent", role: "navigation", cardinality: "optional_one" }, { id: "previous", relationship: "previous", role: "navigation", cardinality: "optional_one" }, { id: "next", relationship: "next", role: "navigation", cardinality: "optional_one" }], topology: { childPolicy: "terminal" } }),
  createDomainPageTemplate({ id: "docs.api", domain: "docs", kind: "docs_bridge", title: "API documentation page", description: "API documentation page.", fallbackSchemaKinds: ["TechArticle"], linkSlots: [{ id: "parent", relationship: "parent", role: "navigation", cardinality: "optional_one" }, { id: "previous", relationship: "previous", role: "navigation", cardinality: "optional_one" }, { id: "next", relationship: "next", role: "navigation", cardinality: "optional_one" }], topology: { childPolicy: "terminal" } }),
  createDomainPageTemplate({ id: "docs.tutorial", domain: "docs", kind: "docs_bridge", title: "Tutorial page", description: "Tutorial documentation page.", fallbackSchemaKinds: ["HowTo"], linkSlots: [{ id: "parent", relationship: "parent", role: "navigation", cardinality: "optional_one" }, { id: "previous", relationship: "previous", role: "navigation", cardinality: "optional_one" }, { id: "next", relationship: "next", role: "navigation", cardinality: "optional_one" }], topology: { childPolicy: "terminal" } }),
  createDomainPageTemplate({ id: "docs.troubleshooting", domain: "docs", kind: "answer", title: "Troubleshooting page", description: "Troubleshooting documentation page.", fallbackSchemaKinds: ["QAPage"], linkSlots: [{ id: "parent", relationship: "parent", role: "navigation", cardinality: "optional_one" }, { id: "previous", relationship: "previous", role: "navigation", cardinality: "optional_one" }, { id: "next", relationship: "next", role: "navigation", cardinality: "optional_one" }], topology: { childPolicy: "terminal" } }),
  createDomainPageTemplate({ id: "docs.release-note", domain: "docs", kind: "docs_bridge", title: "Release note page", description: "Release note page.", fallbackSchemaKinds: ["Article"], linkSlots: [{ id: "parent", relationship: "parent", role: "navigation", cardinality: "optional_one" }, { id: "previous", relationship: "previous", role: "navigation", cardinality: "optional_one" }, { id: "next", relationship: "next", role: "navigation", cardinality: "optional_one" }], topology: { childPolicy: "terminal" } }),
];

export const docsDomainBundle = defineTemplateBundle({
  id: "domain.docs",
  domain: "docs",
  title: "Documentation page templates",
  templates: docsTemplates,
});
